src/index.css
Fixes #135
- Make the links larger on hover, looks cool & interactive as well 💥 
- Demo after merging this PR:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/160"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: increase `scale` on hovering links

Contributing.md
Fixes #182
- Replace Member by LinkFree in contribution guidelines
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix repo name in contribution guidelines

src/Components/Profile.js
Fixes #139
- Position the profile badge as the red notification badges you get on mobile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Change position of profile badge

public/data/ShreyaansJain.json
- Use HTTPS instead of HTTP in `data/ShreeyansJain.json`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Use HTTPS instead of HTTP in `data/ShreeyansJain.json`

public/data/eddiejaoude.json, src/Components/Links.css, src/Components/Links.js
Fixed #377 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: linkedin, catch all links (#377)

src/Components/Home/Home.css, src/Components/Home/Placeholders.js, src/Components/Home/Users.js
fixes #364
This PR replaces the `Avatar` component with `Chip` as it makes it more user-friendly. It also changes the shape of the skeleton to a rectangle as it relates more to a Chip shape 
You can have a look at the screen recording for reference
https://user-images.githubusercontent.com/48324492/135666748-a3de930a-060d-414d-bed2-479092992576.mov
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/406"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Avatar replaced with Chip (#364)

src/Components/Home/Home.js, src/Components/Home/Placeholders.js, src/Components/Home/Users.js
resolves #601 
This PR intends to reduce the differences between the loading skeleton and the Users page.
The `ProgressBar` on the main page has been removed since it overlapped with the skeleton for the `MenuBar`
(*though, I think maybe we can set the `ProgressBar` to appear before the Skeleton for the links gets rendered, in a later PR).
https://user-images.githubusercontent.com/62864373/139380276-ac63d133-9a18-43a7-843c-45f36ab9bf03.mov
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/619"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: more consistent loading skeleton

src/Components/Home/Home.css, src/Components/Home/Placeholders.js, src/Components/Home/Users.js
I have made some changes to the home.css file. Now, the user's list is centered. 
If there are any issues, I would love to do it :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Resolve #620
=> center-users

src/Components/Milestones.js
This fixes https://github.com/EddieHubCommunity/LinkFree/issues/630. Post fix screenshot
NOTE: I have changed the width in PC screen from 70% to 66.6 % cause that was the closest width provided in prime react. I don't think this is breaking anything though. Just a minor change in UI.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: Cards shrinking in mobile breakpoint

src/Components/Profile.js
Fixes https://github.com/EddieHubCommunity/LinkFree/issues/629. The issue was with Image Loader. We don't need the image loader template here. We will already have the image url when this component loads. 
Post fix screenshot
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/632"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: Profile picture is not loading

src/Components/Home/Home.js
closes #638
sort people on homepage by name not by username
Before:
After:
Sorting folks by name due the display-name is the normal name not the username.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/639"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: change sort from username to name

src/Components/UserProfile/ErrorPage.js
fixed the spelling of documentation which was "documendation" earlier.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/666"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed spelling mistake in error page

Contributing.md
The fork icon which was used is similar to the branch icon, so I have changed it into the current version of branch icon 
Few href links (the ones related to fork where redirecting to `https://github.com/EddieHubCommunity/LinkFree/network/members` instead of `https://github.com/EddieHubCommunity/LinkFree/fork`) weren't redirecting to the proper page as expected 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs - Fix the href links and changed the fork icon

src/Components/Milestone.css
Closes #665
Made card text center for mobile view (max width 960px)
Current Alignment:
After Change:
No Change in Desktop View: 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/668"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: card text consistent alignment on mobile

.github/ISSUE_TEMPLATE/config.yml
Hello @eddiejaoude @krishguptadev ,
I have removed the trailing '/' for the issue resolve #717 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/718"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Removed Trailing '/'.

public/data/KaushikK.json
fixes #734 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: usage of static img url

public/data/givenkiban1.json
Cc @givenkiban1 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
fixes #736
=> fix: usage of wrong img url

.github/workflows/prettier.yml
Fixes the issue made in #748 (Is a hotfix, need to do some more work on this later...)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/760"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: failing ci due to auth

public/data/eddiejaoude.json
Added a new milestone (**GitHub Nova, Community Growth Award, 2021**) in `eddiejaoude.json`
Resolve #762 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/764"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: Add a new milestone `eddiejaoude.json`

README.md
Added a short tutorial (_In GIF format_) on how to open **Remote Explorer** on GitPod.
resolve #761
<p align="center"><img src = "https://user-images.githubusercontent.com/51878265/144560140-e23983fd-d227-4f27-bc07-3c51096edd2e.png" height=300></p>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/763"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Add gitpod tutorial gif

README.md
Update the dir path link
Current one:
`data/${yourname}.json`
After Correction:
`public/data/${yourname}.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update directory path link

cypress/integration/search.feature, src/Components/Home/Users.js
Close #792 
In ``cypress/integration/search.feature``
line 21, replaced the current content with the following content:
`Then I see "No users found, please try with another name." text in section "main"`
In ` src/Components/Home/Users.js `
In line 51, replaced the current content with the following content:
`<Message severity="error" text="No users found, please try with another name." />
`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/794"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: add missing comma

public/data/aaquibdev.json
Adding links to linkfree in public/data 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/975"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: add Aaquib Ali

src/Components/ScrollToTopBtn.js
Closes #990 
Simply adding tabIndex attribute to the button did not work in the sense that pressing Enter did not trigger the function.
My solution was to add onKeyPress attribute to the button and pass it the same function as for onClick.
This of course meant that I had to make sure that only pressing 'Enter' and clicking on the button trigger that function.
Hence the condition.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/992"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add tabIndex attribute to scroll to top btn

cypress/integration/user.feature, src/Components/Links.js, src/Components/StyledLink.js
It's better for SEO, UX, and Accessibility
Closes #1016
Repaced button with links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1025"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> change buttons to links #1016

src/Components/Footer.js, src/Components/Navbar.js
Closes #1072 
Previously I added dark color to github icon in the footer.
This PR adds that same dark color for github icon in the navbar. 
Navbar icon now: 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Black GitHub icon

public/data/victoriacheng15.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add victoriacheng15.json

SECURITY.md
Following the conventional way of adding a URL to an MD file. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: MD034/no-bare-urls: Bare URL used

public/data/vishalchauhan.json
I added vishalchauhan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1188"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> created vishalchauhan.json

public/data/vishalchauhan.json, src/Components/Links.js
#948 
Closes #948 
Removed This piece of code from Links.css 
https://user-images.githubusercontent.com/57045550/148688461-efae8a09-e7df-41f0-b003-e6fbef402e23.png
Added this code in Links.js
https://user-images.githubusercontent.com/57045550/148688485-54d1f9ae-5859-4b4a-a921-e6ee23871cae.png
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=>  CSS changes acc to Issue#948

src/Components/ShareProfile.js
Currently, when sharing a profile, URL is always `http://linkfree.eddiehub.org/`.
Here, to allow self-hosting, I changed the link to use the current scheme and domain so that it can be shared for any hosting platform.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use current URL in share buttons

public/data/indigo423.json
Added a link to my fediverse profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: add link to fediverse

src/Components/Home/Users.js
As mentioned in issue #1264, the front page currently loads
avatars from github, which can hit rate limits on the api.
This commit removes the images on from the front page
mentions #1264 
remove images from the front page
[x] - Correct; marked as done
[X] - Correct; marked as done
[ ] - Not correct; marked as **not** done
-->
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> remove profile images on homepage

src/Components/Links.css
Closes #1418 
[x] - Link Button with long text overflows from screen
Initial : 
After changes :
This is my first contribution to the project. I have tried my best to follow the contribution guidelines.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1426"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix : #1418 Mobile view error when text is to long

public/data/AbbeyIT.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: add Abbey Santos profile

package-lock.json, src/Components/UserProfile/User.js
Closes #1478 
- Updated the Link component's to prop to '/search' in Navbar component in User component
https://user-images.githubusercontent.com/47183818/178357822-ff887d86-84f2-4117-9f43-277f29b1d1fe.mov
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1482"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated back arrow to navigate to correct page

.gitignore, components/Footer.js, components/layouts/MultiLayout.js, components/layouts/SingleLayout.js, components/navbar/NavLink.js, components/navbar/Navbar.js, pages/[username].js, pages/index.js, pages/search.js
fixes #1470 
- Modified home page.
- Fixed bugs that prevented the deployment.
- Minor UI Changes in the Search tab.
[x] My code follows the code style of this project.
[] My change requires changes to the documentation.
[] I have updated the documentation accordingly.
[x] All new and existing tests passed.
[x] This PR does not contain plagiarized content.
[x] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Migration to NextJs

reviewpad.yml
This pull request adds more workflows to the reviewpad configuration with commit linting and waiting for reviewers.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1703"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: add more workflows to reviewpad configuration

.github/workflows/prettier.yml
Now we have `path` in the triggers, I think we can always run this Action?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1713"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: run prettier for data files

.github/workflows/prettier.yml
Only run the prettier action on the our branches, as it can't commit to a forked branch and will fail
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1715"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: gh action format

cypress/integration/common/actions.js, cypress/integration/singleuser.feature
Closes #1215 
- Added basic test case for singe user mode to make sure it loads properly.
- Made sure to put the exact original contents back to `user.json` file, so running tests does not affect git's workspace.
- I think it would be ideal to execute `Given('I use single user mode with {string}'` and `Then('I change back to regular mode'...` only once for all future scenarios within `singleuser.feature`, but I couldn't find the way to do it using `cypress-cucumber-preprocessor` syntax. I am willing to improve it if given any direction.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1467"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add basic single user mode test case

generate.js, public/data/branrm.json, src/Components/UserProfile/ProfilePage.js
Closes [#1334](https://github.com/EddieHubCommunity/LinkFree/issues/1334)
Makes a validation to check if links exists in ProfilePage.js, if true the array of links passes all his values, else an empty array is passed. Then in generate.js another validation is made to check if profile links exists, if true the length is returned, else a default zero is passed.
User profile data without links attribute
Profile user view working without links attribute
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> links property is now optional. generate.js doesn't break when links are not defined.

public/data/2brownc.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1815"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add my profile to public/data

public/data/chints87.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1810"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Profile

public/data/omdxp.json
=> Adding `omdxp` profile

public/data/tcodes27.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1825"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create Tcodes27.json profile page

reviewpad.yml
Update the hacktoberfest-invalid label in the reviewpad file to just be invalid
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1850"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: update hacktoberfest-invalid label to invalid

public/data/favalcodes.json
Added my profile to linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1873"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> my first opensource code pr

public/data/kayjilesen.json
- [] My code follows the code style of this project.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1826"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added profile

icons.md, src/Components/Icons/GetIcons.js
Resolves #1324
Add `Graduation Hat` as a valid icon alongside `graduation hat`, because users have mistaken the icon code for the icon name.
Also, add a notice to icons.md clarifying how to use icons.
- - Changes to icons.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1890"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bug 1324 graduation hat icon missing a hyphen

public/data/aryanbabber.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1898"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create aryanbabber.json profile page

public/data/aladdin.json, src/config/user.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1900"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added link tree

public/data/crazydevlegend.json
Adding my profile...
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1905"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added crazydevlegend

CHANGELOG.md, package-lock.json, package.json, src/App.js, src/Components/Footer.js, src/Components/Home.js, src/Components/Icons/GetIcons.js, src/Components/Links.js, src/Components/Navbar.css, src/Components/Navbar.js, src/Components/Search/Placeholders.js, src/Components/Search/Search.js, src/Components/Search/Searchbar.js, src/Components/Search/Users.js, src/Components/Search/filterProfileType.js, src/ThemeContext.js, src/index.js
resolve #1032
4 PM.png…]()
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1852"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Implemented the Dark/Light-Mode feature

public/data/chidubem.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1934"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create chidubem.json profile page

src/Components/Milestone.css, src/Components/Milestones.js
➜ Fixed image  border-radius to 50px 
➜ border to none (border-0)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1867"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added border-radius and border

.gitpod.yml, docker-compose.yml
Adjustments for Gitpod.yml in the new project setup
=> Update Gitpod.yml for Next.js

components/user/UserPreview.js
Closes #1984 
Changes name text size from text-2xl to text-xl in user preview card in NextJs
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1985"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: NextJs user preview card name size

package-lock.json, src/Components/Home.js, src/Components/Search/Searchbar.js
closes #1937
shortcut key for searchbox
Made changes in Home.js & Searchbar.js
On main page shortcut key 'ctrl+k' takes us to the search box.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1971"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> keyboard shortcut added for seachbox

src/Components/Home.js
Closes #1926 
- Changed Link color from purple to blue
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1929"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed Color of Links in Dark Mode

src/Components/Search/Search.css
Closes https://github.com/EddieHubCommunity/LinkFree/issues/1999
When the user hovers over the items in the list, box shadow of white was causing eye strain, and the text was not visible. Hence as part of this PR I have removed the box shadow and updated the color to black on hover which will fix the above issue. 
Before fix:
After fix:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2014"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix(#1999) : color issue in the dark mode

.gitignore, playwright.config.js, tests/global-setup.js, tests/global-teardown.js, tests/profile.spec.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2060"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> NextJS Profile tests

tests/search.spec.js
Closes #2080 
-Added the skeleton for the test of searching the profile when provided with the whole user name.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2087"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test for full user name

tests/popular.spec.js, tests/search.spec.js
Closes #2084 
- skeleton for testing wheather the popular profile is displayed at the top in the popular page.
##Screenshot:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2088"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add test for popular profile search

cypress/integration/search.feature, src/Components/Search/Search.js, src/Components/Search/Users.js
1) profile picture for particular user added in chips in the search page 
2) in chip element "templet" attribute removed and using default "label" attribute and also using "image" attribute for profile picture
3.chips will come after user enters 3 or more characters in search bar this will solve github api limit issue.
it s also presentable for long names :
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2024"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add : adding profile picture in chip

reviewpad.yml
due hacktoberfest is over I would suggest removing the hacktoberfest invalid labler by reviewpad due the label `invalid` is not serving value anymore
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2097"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: remove hacktoberfest-exclude labler

README.md
I changed line 98. I also noticed that there's a line that says "public data file". Should that one be changed to?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed line 98.

src/Components/Navbar.css, src/Components/Navbar.js
Fix Issue #1927 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixing Dark mode toggle is not reachable with keyboard navigation

src/Components/Search/Users.js
Closes Issue #1928 
changed the color of the text in users when hovered in dark mode since it was not readable.
Old:
New:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1954"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed color of the text on hover in dark mode

src/Components/Home.js
before:
after:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1992"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add: visible links

src/Components/ShareProfile.js
Profile Share icon on profile page was not visible in the dark mode, now it is fixed.
Changes are highlighted in red color:
Before changes:
After changes:
It is a small UI bug fix.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2002"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix dark mode profile share icon 

src/Components/ShareProfile.css, src/Components/ShareProfile.js
ShareProfile Popup doesn't have close button or cross icon to close the popup box. I have added this feature which closes popup while clicking upon.
i have hidden this feature for mobile view , its for large to medium size screens .
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2020"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> (feat #1995) : Cross icon feature to close shareprofile popup

src/Components/Profile.css, src/Components/Search/Search.css, src/Components/Search/Search.js, src/Components/Search/Searchbar.js, src/Components/Search/Users.js
#1928 
I have made the profile names visible on hovering in dark mode and also made the **share icon** visible.
I closed the previous PR that I raised for this issue due to some error and raised this one.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2026"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Made Profile names  visible on hovering in dark mode

src/ThemeContext.js
Closes #2034 
Enable Dark or Light mode automatically depending on a user's system settings
This change looks at the System settings for the user's preference but does not store the user's chosen value locally. For that, Issue #2032 will need to be solved.
You may want to enable Dark Mode system-wide to test. For example, this is in Windows:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2039"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Check Dark/Light Mode From System Settings

src/Components/Links.js
One example is if you want to use LinkFree as your "home page", and want to add a link to your Mastodon profile, adding `rel="me"` in the link allows to make your mastodon account "verified" (similar to what twitter blue does but with less certainty and safety).
Since "rel" is a standard attribute, instead of just a flag for `rel="me"`, this PR allows supporting **any** value for `rel`, up to the user 👍
For instance, I'm using it on my self-hosted LinkFree instance on https://links.piers.tech and it works great 🚀
N/A
N/A
=> Allow using the "rel" attribute for specific link types

pages/search.js
**Updated:**
user not found under the search bar.
**Old:**
This change prevents that the search bar is jumping on the page when the error message appears
Further added a warning message if the search string is less than 3 characters
Remove the results list if the search string is less than 3 characters
=> fix: refactor search page structure

config/mongo.js
Added a check in `config/mongo.js` to check if the `LINKFREE_MONGO_CONNECTION_STRING` mongo connection string is present inside `env.local` :
```js
// config/mongo.js
if (!process.env.LINKFREE_MONGO_CONNECTION_STRING) {
throw new Error(
"Please define LINKFREE_MONGO_CONNECTION_STRING to .env.local"
);
}
```
Hello 😁
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add MongoDB .env error handler

.gitpod.Dockerfile, .gitpod.dockerfile, .gitpod.yml, playwright.config.js
Closes #2257
Install playwright dependencies on init.
Set Playwright to not run parallel tests on Gitpod 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix Playwright setup on Gitpod

.github/workflows/prettier.yml
- change the GitHub Token to PAT (`GH_PAT`) 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2321"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: change the GitHub Token to PAT

components/Page.js, pages/[username].js, pages/events.js, pages/popular.js, pages/search.js
As described in #2288 there is some inconsistency between the main pages.
This PR adds a `Page` component that can be used on the main pages to make sure the styling is consistent.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: create Page component to unify padding and sizing of the main pages

components/navbar/Navbar.js, pages/index.js
Fix aria-expanded on mobile menu to match the open / closed status of the menu.
Removed a `legacybehavior` attribute on an anchor tag that is not relevant and produces a warning.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2308"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix aria-expanded

components/user/UserLink.js, styles/globals.css
Fixes UserLink issue for #2382 
Use icon color for icon & hover border
Use black for text color
Current link style:
New link style:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2424"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix text contrast  ratio on UserLink

pages/events.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: events key #2414

data/mohit1607.json, pages/docs/environments/local-development.mdx
Addition of new profile mohit1607.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile Addition

components/ClipboardCopy.js, package-lock.json, package.json, pages/docs/quickstart.mdx
Closes #2521 
Added the copy to clipboard button to the code blocks in the quick start page.
https://linkfree.eddiehub.io/docs/quickstart
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2551"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> copy to clipboard feature added

components/user/UserCard.js
Closes #2576
[X] - Added user viewed to profile badge in user cards of popular profile page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2579"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Feature] Popular profiles to display profile view count

pages/docs/quickstart.mdx
The json object for only links is updated to the whole json of a profile, so that no furher confusion about the structure of json happen.
Quckstart improvement - explain json structure #2538
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2593"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: where to put links confusion

next.config.mjs
Fixed issue that arises by using `http` for getting the GitHub avatar. Check #2637 issue for details
Changed `HTTP` to `HTTPS` in 4 files of the `data/`
Before
After
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2638"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> issue #2637 fix

.github/workflows/testimonial.yml
Closes #2659 
- Add an extra step to validate JSON before merging a testimonial
> **Note** Testing GitHub Actions has always been a little bit flakey for me, and I know I need to spend some time figuring it out. I'm pretty sure this works correctly, if not it shouldn't be off by much because it works here locally.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2660"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> GitHub Action testimonial should valid json before committing file #2659

data/Pradumnasaraf.json
**Changes Proposed**:
`icon="website"`
to
`icon="FaLink"`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated icon reference to Pradumna's website

components/user/UserCard.js
Closes #2866 
changed the `userCard` width to be fixed `14rem`, previously it was `max-width: 14rem` and this was causing the cards with lesser bio content to sharing and take lesser spacing causing the alignment issue
Before: 
After:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed the random usercards and popular usercards allignment 

pages/docs/how-to-guides/milestones.mdx
PR for issue #2840. Correction in `pages/docs/how-to-guides/milestones.mdx`
Closes #2840 
```diff
- 24. "color": "grey", 
+ 24. "color": "grey", // or #808080
```
```diff
- 36.  | color       | What color would you like this milestone to be displayed in |
+ 36. | color       | What color would you like this milestone to be displayed in. Use hex codes or name of the color |
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2861"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: add usage of hexcode in milestones docs

README.md
- chnage the example profile image to the latest one
- Fix the docker command. That was one for compose - v1, which is now deprecated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3070"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: updated docker command and image in README

pages/events.js
Closes #3069 
Wrong avatars being loaded was caused by React not properly following the `key` properties on `EventCard` components.
I've added a workaround, by adding an `id` property to the event objects after they're being fetched. 
I imagine later down the road, the event object structure will be changed and they will come with ids from the database, so those can be used as a `key`.
This is more or less my first pull request, I apologize if I'm doing something wrong.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix event card wrong avatar issue

pages/docs/how-to-guides/milestones.mdx, pages/docs/index.js
[DOCS] Typo in docs under Milestones closes #3063 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3158"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: fix typo 

.github/workflows/community.yml
- Remove the push: part from the workflow because the main branch is protected, and push operations can't be done. Also, it will stop the messages on the temp branches created by Deploy and Releases.
- Added a name to the workflow for better understanding. Currently, it shows the file name with the path.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3398"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: remove the push part form community workflow

.github/workflows/json-check.yml
Remove the `push:` part from the **JSON check** workflow because the `main` branch is protected, and push operations can't be done. So, everything will go via PR, and PR is already been checked by the workflow. 
**Technically, the workflow's push part will never run.**
Part removed:
```yaml
push:
paths:
- "data/**.json"
```
=> ci: remove the push part from the JSON check workflow

pages/docs/how-to-guides/bio.mdx, pages/docs/index.js
changed from allow to allows.
closes #3042 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3421"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Typo in docs under Bio

data/iqrafirdose.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:iqrafirdose

data/Madhavi210.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3623"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Madhavi210

data/rayeesrather99.json
Done
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3677"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:rayeesrather99

components/user/UserTestimonials.js
Added Markdown support for Testimonials
Closes #3638 
Before
After
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add markdown support fot testimonial

components/Footer.js
The PowerOff icon beside **Powered by Eddiefub** looks a bit odd as it resembles the shutdown icon.
A better alternative would be to use the FaSuperpowers icon, which will bring a positive perspective.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3474"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3782"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed PowerOff icon to FaSuperpowers icon

components/user/UserLinks.js
closes #3434 
This was happening due to not having the correct key property while mapping over the link
Instead of using `index` as key, changed it to `link.name`
the Link has `name, icon and url` values in it, the name seemed the most optimal
If having `link.name` as the key is not the appropriate option, we can add an `id` on each link before mapping over it like this
```
data.links = data.links.map((link, i) => ({ id: i, ...link }));
```
By this, each link will also have a unique `id` field which can be used as a key
<a …
=> [FIX] fixes the links view count not being sorted

.github/workflows/prettier.yml
Add workflow dispatch to the prettier action.
The need for this is merging from main is causing misc profiles to be included in PRs.
=> Add workflow dispatch to prettier action

.github/workflows/build.yml, components/user/UserLink.js
Changes made to the `config/icons.json` caused Si icons to be added to our profile test.
The SI icons are generated in a different way to Fa icons which causes accessibility issues.
This PR fixes the test and adds the config directory to the list of changes to run tests.
=> Fix Si icons failing accessability test

data/midhundevasia1.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4295"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:midhundevasia1

pages/discover.js
Solves the issue #3596 i created
fix #3596 
Aligned the text properly. Attaaching a ss below to show proposed changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3597"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> alignment of headings

components/user/UserTestimonials.js
Due we display usernames in the testimonials I would mark them with an @ sign at the beginning.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4381"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add @ sign for usernames in testimonials

components/layouts/DocsLayout.js
Removed the extra words on DocsLayout.js. Fixed #4506
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed #4506

public/robots.txt
Currently when a crawler requests `robots.txt`, LinkFree returns the search page using `robots.txt` as the search term.
This PR adds a `robots.txt` to public allowing all crawlers
=> Add robots.txt for SEO

.github/workflows/storybook.yml, .storybook/main.js
Fix storybook warning for `.storybook/main.js`
Deploy storybook on workflow_dispatch
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix storybook warning & deploy on dispatch

.github/workflows/data-filenames.yml
Changes released by [tj-actions/changed-files](https://github.com/tj-actions/changed-files) have caused the data-filenames action to be erratic.
This PR pins the version to the latest one known to work while the changes are investigated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Pin changed-files action to working version

pages/map.js, services/github/getLocationByUsername.js
Remote is a valid location in Oregon .
This is not likely the location of people who set their location on GitHub to Remote.
This PR will ignore the location.
=> Ignore remote as a location

pages/api/users/[username]/index.js
When creating the initial user record we don't save the result.
The _id field is used later, but for the initial user record this wouldn't exist.
This PR saves the returned document from the initial creation.
It also fixes some logging spelling mistakes.
=> Fix daily stats init

pages/account/statistics.js
Closes #4708 
There is a typo on line 101 in the Alert message of the [pages/account/statistics.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L101) file. 
The word `proile` was changed to `profile`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4724"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix typo in statistics.js

components/navbar/Navbar.js, components/user/UserProfile.js
Add the priority option on the image component for:
1. NavBar image
2. Profile picture
This will start fetching the images earlier in the process of loading the page.
=> Use Image Priority on above the fold images for profile pages

components/ClipboardCopy.js
Closes #4903 
This rolls back the logger change from #4837 as the logger is incompatible with webpack
=> roll back logger change for CopyClipboard

components/Badge.js, components/Tag.js, components/user/UserProfile.js, pages/events.js, pages/search.js
This change updates the Profile page so that the QR code no longer has a bouncing effect, which can be distracting for certain individuals.
<details>
<summary>Video description</summary>
<div>The video shows a LinkFree Profile page showing the QR code no longer having a bounce effect. Clicking the QR code expands the QR code.</div>
</details>
[](https://user-images.githubusercontent.com/478770/218995971-eaa26730-6eb1-4457-b104-77f51d3feeba.mov)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Accessibility: Remove bounce effect on QR codes

package-lock.json, package.json
- Update the **LinkFree-CLI** to `v2.0.0` after new relaese.
Now we can 
- Creating a LinkFree profile.
- Updating a LinkFree profile.
- Giving a testimonial to a LinkFree profile.
- Adding events (conferences, meetups, etc).
And change the script to `cli: npx linkfree-cli`
```
npm run cli
```
Repo - https://github.com/Pradumnasaraf/LinkFree-CLI
NPM - https://www.npmjs.com/package/linkfree-cli
=> fix: upgarde LinkFree-CLI version to v2.0.0

package-lock.json, package.json
- Fix version to `v2.0.1` there was an accessibility issue in `v2.0.0`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5033"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: fix LinkFree CLI version to `v2.0.1`

pages/docs/environments/linkfree-cli.mdx, pages/docs/index.js
- Add a section in docs for LinkFree CLI.
https://user-images.githubusercontent.com/51878265/220897863-3bdc4057-1d19-48db-be5c-ca2c0c65b185.mov
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5027"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Add docs for LinkFree CLI

.husky/pre-commit, package-lock.json, package.json
Closes #5142 
Remove lint-staged from the husky config
lint-staged was used to call prettier on data directory files.
This has caused more problems than it solves  by adding changes for merges from main.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove lint-staged & prettier from husky config

components/user/UserProfile.js
Closes #5003 
- Navigating to different tabs ("My Links", "Milestones", .... ) in user profile. Top hero section of user  flickers. 
- Cause: As navigating to different tabs cause re-rendering of userProfile component.
- Solution: Memoize userProfile component, as user data doesn't change on a simple tab change. So no need to re-render component on every change.
https://www.loom.com/share/c0b4d8c001734d86931668b43d53e51f
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5158"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: Memoize user profile for performance improvement

data/VarchasvH.json
I was having an Internal error 500, when I was trying to access my LinkFree page. One suggestion that I found was to change my "Socials" to "links". Refer to this [Q&A](https://github.com/EddieHubCommunity/LinkFree/discussions/5068)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5323"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed my "Socials" to "links"

package-lock.json, package.json
- Bump LinkFree-CLI version to `v2.2.2` to add support for new features
NPM Release - https://www.npmjs.com/package/linkfree-cli/v/2.2.2
Chnagelog - https://github.com/Pradumnasaraf/LinkFree-CLI/releases/tag/v2.2.2
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: bump LinkFree-CLI version to v2.2.2

data/Amalks920.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5456"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Amalks920

pages/[username].js, pages/account/statistics.js, pages/api/users/[username]/index.js
Tweaking https://github.com/EddieHubCommunity/LinkFree/pull/5595
closes #5311
---------
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5626"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: account stats own visitor (#5595)

pages/account/statistics.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5628"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: stats page increment

pages/map.js
Closes #5420 
This commit updates the user filtering logic to use the tags in the `updatedSelectedTags` as filter conditions. 
If there are any concerns or suggestions regarding this approach, please let me know. Thank you for your time and consideration.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: map toggle off tag filter (#5420)

components/navbar/NavLink.js, components/navbar/Navbar.js
fixes #5190 
The proposed change replaces a direct string comparison between the `path` and `item` variables with a more flexible check that extracts a specific substring from the path and compares it to a modified version of the `url` property of the item object. This change allows for more robust matching of URLs with different structures, while still achieving the same functional outcome.
Here is the video of the resulted behavior:
- For desktop screen:
https://user-images.githubusercontent.com/94737463/222326307-e8cb0aa5-4d42-46e1-819d-147a73c53bc4.mp4
- For mobile screen:
https://user-images.githubusercontent.com/94737463/222326364-0464f1d6-8550-450c-98a8-9551eddfe317.mp4
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5197"><img …
=> fix: NavLink active state not persist

components/Badge.js, components/Button.js, pages/map.js
closes #5500
Currently `Clear/Reset` button in Map section is active even when no filter is selected, hence a fix to this issue is proposed through my PR which disables the button if no filters are selected.
Before:
After:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added a feature which disables the clear button when nothing is selected.

components/Badge.js, components/Button.js, pages/map.js
Tweaking PR https://github.com/EddieHubCommunity/LinkFree/pull/5588
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5678"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Map disable button

components/statistics/ProfileProgress.js, pages/account/statistics.js
closes #5496 
Created UI for the progress bar using tailwind
Created a array which represents the sections that are required to fully complete the profile named it `profileSections`
```jsx
let profileSections = [
"bio",
"links",
"milestones",
"tags",
"socials",
"location"
]
```
Created an object called `progress` which keeps track of :
- The completion percentage
- An array of sections that are missing (This serves can be used later to add specific hints related to the missing sections below the progress bar )
```jsx
progress = {
percentage:0,
missing:[]
}
``` 
Used filter to find the missing items, calculated the percentage
```jsx
progress.missing = profileSections.filter((property)=> !Object.keys(profile).includes(property) )
progress.percentage = (((profileSections.length - …
```
=> Profile Progress section in the Account page

pages/docs/map.mdx
Closes #5473 
- Add information on why user markers not appearing in local dev to the [Map Information Doc](https://linkfree.io/docs/map)
The documentation now explains why user markers do not appear on the map page during local development and provide a solution to populate the database with location information. This change aims to help beginner developers who may face this issue while working on the project.
As discussed in issue #5473, I plan to create a new issue for adding a `seed` script to populate mock user location information to the database for local development purposes. This would make it easier for developers to test the map functionality without manually visiting multiple user profiles.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5766"><im …
=> docs: add information on why user markers not appearing in local dev

components/Tag.js, pages/search.js
This PR resolves the Update UI fixes in Search bar #5828 
closes #5828 
UI changes were added accordingly.
Below SnapShot shows the UI Issue 
After changes were made, the UI looks like
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5829"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Fixed issue#5828 Updated UI of the Search bar 

components/Button.js
closes #5968;
On hovering the button in light mode the text color remains the same 
On dark mode it's white
So I added a small fix in the button component
Before :
After : 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5927"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5928"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add text-color white on hover in light mode to button component

pages/search.js
Hi @eddiejaoude this is regarding Toggle information in the search bar and the profile panel reset issue #6002
I have made some code changes such that the Badge in the search bar be zero and the profile panel be empty when the search field is empty
The code changes fixes this #6002 issue
fixes #6002 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> User profile reset issue - SearchBar

package-lock.json, package.json, tailwind.config.js
Remove the line-clamp plugin to get rid of the warning from tailwind
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6108"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove line-clamp plugin as the functinality is now built into tailwind core

components/modals/ProfilePreview.js
DarkMode Issue on preview of JSON on playground #5911
fixes #5911 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> DarkMode Issue on preview of JSON on playground #5911

data/sandramsc.json
fix json syntax error at "Web3"
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sandramsc

pages/docs/environments/environment-variables.mdx
Fixed #6341
Just changed the domain to `https://linkfree.io`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6342"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: changed the old URL #6341

config/mongo.js
Force mongoose to connect by IPv4
GitPod is now configured with IPv6 available which is causing connection errors trying to access `::1`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> force IPv4 on mongoose connect

.github/workflows/issue-lock.yml
GitHub supports the rendering of issue labels in Markdown. Now, Instead of plain `ready for dev` text, now it will show the actual issue label, and it's clickable as well.
_To reduce notifications, issues are locked until they are https://github.com/EddieHubCommunity/LinkFree/labels/%F0%9F%8F%81%20status%3A%20ready%20for%20dev and to be assigned_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6398"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: Improve message of issue locking Action

pages/api/statistics/totals.js
Currently the total views & clicks stats for the index page are obtained by getting an array of stats from MongoDB, then looping over the array to sum the values.
This PR uses the MongoDB aggregate function to get the database to sum the values for us.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6539"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use Mongoose aggregate to sum views & clicks

pages/account/statistics.js
fixes #6532 
By adding some style it solves the problem of not showing the date in the tooltip of profile visit count.
Here is how `it was` vs `it is` 
| Then | Now |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/77217706/235549951-c4f7f195-1d88-41b0-ae11-c43707887246.png) | ![image](https://user-images.githubusercontent.com/77217706/235549981-0ba0069c-a3ab-4b0e-85cf-0acf7be7a98c.png) | 
```js
<Tooltip contentStyle={{
color: "black"
}} />
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6549"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> (fix): date visibility on stats page

.github/workflows/prettier.yml
Change the cron time from `12:00 UTC` to `01:01 UTC` because most actions run at that time on GitHub, and this will reduce the overall load. This was also recommended by @martinwoodward in one of Eddie's live streams.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: update cron time - prettier.yml

pages/map.js
Because the map can't be server side rendered, space needs to be reserved for it in the statically generated HTML.
This will improve the CLS Core Web Vitals metric
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6944"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix map layout shift

components/PageHead.js, components/map/Map.js, pages/map.js
The background of the map is a tiled collection of PNGs.
Because the map generation runs on the client, the request of these images happens later and slows down the loading.
This PR will preload all the images for the start zoom level.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6961"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Preload Map Tiles

.github/workflows/publish-ghcr.yml, Dockerfile
use the `secret-files` option on the docker build action to pass the MongoDB URL in securely
Docker Documentation
https://docs.docker.com/engine/reference/commandline/buildx_build/#secret
https://docs.docker.com/engine/reference/builder/#run---mounttypesecret
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7031"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use secret file to pass Mongo URL to docker build

components/event/EventCard.js, components/event/EventKey.js, components/user/UserEvents.js, data/eddiejaoude.json, data/eddiejaoude/events/2023-05-27-eddie-con.json, models/Profile.js, pages/api/system/reload.js, pages/docs/how-to-guides/events.mdx, pages/events.js, pages/search.js
* Added filter to show free and paid events
* Move import position for tb coin icon
---------
fix PR #4759
TODO
=> feat: filter to show free and paid events (#4759)

components/map/MarkerCluster.js
The map loads markers for all users on initial load.
This PR tells leaflet to load in chunks to avoid hogging the main thread.
=> Load map markers in chunks to minimize blocking

components/navbar/NavLink.js
By default, Next pre-fetches links.
On mobile, with less powered devices on lower bandwidth networks, this can cause performance issues.
=> Don't prefetch nav links on mobile

config/app.json, pages/index.js, pages/map.js, pages/search.js
Closes #7142 
* add  a new `isr` object in `config/app.json` to store `revalidate` values for different pages
* imported the config file into the `getStaticProps` function for each page
* utilized the appropriate `revalidate` value from the config object in each page's `getStaticProps`
* updated the config file with desired `revalidate` intervals for each page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: improved management of  ISR revalidation

package-lock.json, package.json, pages/index.js, tailwind.config.js
fixes #7229 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: promo video on homepage (#7229)

components/event/EventCard.js
Modifying a prop inside a component does not force a re-render.
Use state to manage the formatted start & end times to re-render the local time.
=> Fix events display in local timezone

pages/api/discover/tags.js
have used the MongoDB aggregation framework to convert tags to lowercase using the "$toLower" operator
Hey [this](https://github.com/EddieHubCommunity/LinkFree/pull/5534#discussion_r1208740227) i have checked 
as in [Search.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js) the tags already converted to lowercase 
As here the results returning filtered value only 
Also have checked and tested by my side every tag is working fine 
Need Your reviews Thanks 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix : duplicate tags in search #5534

.github/workflows/publish-ghcr.yml
Closes #7281
I realise we were versioning the GHCR image incorrectly. The Docker image should be versioned like `image-name:version` eg: `mongo:6.0` without a `v`
Image from LinkFree GHCR image
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7280"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: change GHCR image versioning pattern

package-lock.json, package.json
Bump the [linkfree-cli](https://www.npmjs.com/package/linkfree-cli/v/2.3.1) version from `2.2.2` to `2.3.1`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7323"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: update linkfree-cli version

components/embeds/Youtube.js
Closes #7273 
<details>
<summary>Smaller screens - Before</summary>
</details>
<details>
<summary>Smaller screens - After</summary>
</details>
<details>
<summary>Larger screens - Before</summary>
</details>
<details>
<summary>Larger screens - After</summary>
</details>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7308"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: add responsive height to youtube embeds (#7273)

data/funmilolaadebisi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7332"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:funmilolaadebisi

.github/workflows/vercel.yml
Vercel GH Action deploys when merged to `main` and also when the release is created (so 2 deploys that are the same)
- we want to deploy on release
- but we also want to deploy when data files are merged to `main` because no release us created
- this will only deploy on `main` for data files
From GitHub docs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs
=> fix: vercel single deploy

components/user/UserCard.js, pages/api/users/index.js, pages/search.js
Remove unused fields returned from `getUsers()`.
This reduces the data size by ~60kb.
Don't allow links in user cards as they are already a link to the user.
=> Search page cleanup

pages/index.js
Fix the screenshots on the home page to avoid cropping or stretching
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7414"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix home page screenshots

pages/docs/quickstart.mdx
Where \<a> tag and \<li> are misaligned in certain browsers (See screenshots)
Closes #6967
Broken
Fixed
Pre HTML5 \<a> tags could not contain \<p> tags. In HTML5 it is acceptable, however some browsers are flakey about the implementation. Setting the <a> tag's display property to block resolves this.
How do we feel about this solution? Not a big fan of duplicating so many classes, but adding classes to <Link> overrides the default classes and we still want the default classes so this seems the best solution to keep them.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: resolves issue where <a> tag and <li> are misaligned (#6967)

components/user/UserTabs.js
Closes #7049 
* Increased the text size in profile page tabs. Initially it was `text-sm` , but now I have changed it to `text-lg`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7473"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: increase profile page tabs text size (EddieHubCommunity#7049)

components/Modal.js
To fix the issue with playground preview theme have added required dark mode tailwind classes 
https://github.com/EddieHubCommunity/LinkFree/assets/29349136/162b874b-6bcd-4d34-b45a-11a5cb220514
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix : Playground preview theme

data/piaseckijulian.json, data/victorchrollo14.json
Remove `type` property from the remaining profile JSON.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: remove type key from profiles

components/user/UserLinks.js
Closes #7041 
components/user/UserLinks.js
```diff
-<h3 className="ml-2 mt-2 text-lg font-medium leading-6 dark:text-primary-low text-primary-high">{name}</h3>
+<h2 className="ml-2 mt-2 text-lg font-medium leading-6 dark:text-primary-low text-primary-high">{name}</h2>
```
Changed the headings from ``<h3>`` to ``<h2>``
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Changed Profile page group link headings from h3 to h2.

pages/[username].js
fixes #7604
Fix formatting of PR https://github.com/EddieHubCommunity/LinkFree/pull/7609/files
=> Fix pr 7609 formatting

models/Profile.js, pages/search.js
Closes #3467
- Added city, state and country fields to profile schema
- Added search by location feature on search page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: search by location

package-lock.json, package.json
Update the LinkFree CLI version to `v2.5.0`. Now to CLI use ES6 standards
With this, the package has 0 vulnerabilities.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7638"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: update the LinkFree CLI version

pages/account/statistics.js, pages/playground.js
fixes #7507
When clicking on username(hyperlink) on statistics page, it points you to a localhost url. 
<br>
**_To reproduce issue, see the ISSUE page for this PR._**
Same happens with links on Playground page.
- Getting `BASE_URL` as props
- For reference see `[username].js`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7640"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [FIX] getting localhost in BASE_URL on statistics and playground page

data/Saha-7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7665"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Saha-7.json

.github/ISSUE_TEMPLATE/bug.yml
Add a title in the bug issue template
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7821"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: add title in bug issue template

models/Link.js, pages/api/profiles/[username]/links/[_id].js
The relationship should be one sided because
- it will grow large in the profile
- we will never do a join but query the stats model directly
=> fix: link and linkstats relationship

pages/404.js
Closes #7981 
Fixed bug - 404 page button was not looking good in small screen
*Desktop*
*Mobile*
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8019"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> bug fixed - #7981

components/user/UserLinks.js
Removed the "0" which is displayed when there are no links by modifying the condition.
fixes #7968
Modified only the condition to check if the links have a length greater than 0.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove 0 when there are no links

.github/workflows/vercel-pr-preview.yml
- Create a Vercel Preview env with every PR that has a change in the JS file.
The reason why I added branches-ignore is that if any preview branch is deployed to a custom domain, it will deploy twice - once with the custom domain and once with this action.
```yaml
branches-ignore:    
- revert-logger
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7912"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: Add vercel preview PR workflow

components/user/UserProfile.js, pages/account/manage/profile.js, pages/api/account/manage/profile.js
Closes #8040 
- Empty blocks in the tag list won't appear anymore.
- Updating the tags with the response of the profile-update api.
- Updated the key prop's value to the ```index```, if same-named tags are entered multiple times and also for removing them when user removes them from the tag-input field section. Rendered ```Tag``` Components will not unmount if new tags are added.
- Backend API Changes -> Added filter for removing all of the falsy value and string values which contains only whitespaces to prevent whitespaced link generation for the tags when user clicks on them.
Example
if input is ```" javascript,          nextjs        ,,,,,solidjs, vuejs,"```, then they will be result into the ```"javascript, nextjs,solidjs,vuejs"``` while saving in db.
This is the screenshot of the …
=> [fix]: comma misbehave in profile form section

.github/workflows/testimonial.yml
Closes #8074 
**Fix of broken link in testimonial github action.**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: broken link in testimonial github action

pages/premium.js
When signing to news regarding LinkFree's premium tier, the success banner after signup featured a small typo: `notified` instead of `notify`.
I fixed the typo :)
I failed to take a screenshot in time :/
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes typo in signup success message for premium updates

components/user/UserCard.js
Closes #8176
Fixed the issue where the profile card did not display an orange border when hovered in dark mode.
https://github.com/EddieHubCommunity/LinkFree/assets/96465597/56d02566-7191-4531-a286-b1af6d0ab772
This is my first contribution to this project, and I'm excited to be a part of the community. I kindly request your feedback on my changes. If there are any areas for improvement or suggestions, I'm eager to learn and make the necessary updates. Thank you for your time and guidance!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: profile card hover color

components/navbar/Navbar.js, tests/playground.spec.js
fixes #4995
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8276"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: profile link in navbar

.github/workflows/publish-ghcr.yml
`>` to `>>`
```bash 
echo "LINKFREE_MONGO_CONNECTION_STRING=${{ secrets.LINKFREE_MONGO_CONNECTION_STRING }}" >> /tmp/.env
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: GHCR workflow command

pages/api/discover/random.js
Change message when `getRandomProfileApi()` fails in development to be a warning mentioning loading users.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8422"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Change Error to Warning when users not loaded in development

components/user/UserEvents.js
Closes #8413 
Label in event section of profile does not appear in dark mode.
- Add text color class for label to fix text not visible in dark theme.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: Issue with label in dark mode #8413

components/ClipboardCopy.js, components/user/UserProfile.js
fixes #8526 
I fixed the issue by setting the width of the ClipboardCopy component to "w-full" , so the child can have "w-full" applied to it successfully , I also checked pages that contain ClipboardCopy component to check if anything changes in there , and I saw them looking well and working perfectly
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8566"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed #8526 : QR code link width 

components/Modal.js
Closes #8455 
- In the download QR code section, the close tab is highlighted already. It should not be highlighted.
- Fix: Changed the already highlighted close button to highlight on hover. Screenshots are attached.
Before changes: Default button
After changes: Default button
After changes: On hover button
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: close button of download qr code modal fixed (#8455)

components/form/Textarea.js
fixes #8664 
closes #8664 
i fixed a bug that, the in `account/manage/profile` page, the **BIO** label is not visible in dark mode, i changed the color of this label to white and fixed the issue. So that, it resolves issue where the bio label was not visible in dark mode.
no screenshots taken, but check the issue, it won't repeat again
This pull request addresses the issue where the bio label was not being displayed correctly in dark mode. I've fixed the styling so that the bio label now shows up properly even in dark mode.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix dark mode display issue for bio label

components/ThemedImage.js, pages/index.js
Create ThemedImage component which will display different images base on theme.
Use this component for homepage screenshots.
(It currently uses the same image for both while dark mode images are obtained).
=> Add ThemedImage component to allow different images based on theme

models/Link.js, pages/account/manage/link/[[...data]].js
Increases the max length of a link display name from 64 to 128.
Closes #7851 
Changes to the following files: models/Links.js and pages/account/manage/link/[[...data]].js to increase maxLength of link display name.
Examples of successfully adding display names of 66 characters and 128 characters:
=> fix: (issue #7851) increased max length of link display name

components/Link.js
Closes #8686
To fix the issue I added tailwind `break-all` to `Link` component class in order to allow the link name to break and go to new line it it is considered as a only word by the browser
=> [fix] overflow issue in repos section

tests/changelog.spec.js, tests/discover.spec.js, tests/docs/docs.spec.js, tests/events.spec.js, tests/home.spec.js, tests/playground.spec.js, tests/profile.spec.js, tests/repos.spec.js, tests/search.spec.js
Wait on link clicks to complete before checking.
The current way works most of the time, but is entirely based on the testing systems performance.
Explicitly checking should minimize the false failures.
=> In Playwright tests, explicitly wait for link clicks to complete

components/user/UserEvents.js
fixes #8700
- Added a check that if there is no future events(which is default action), then it shows every **event instead** of showing **No event found**. 
Using `/amandamartin-dev` profile as an example. Since this profile doesn't have any future events, which was the default event type. So instead of showing no events, now it shows all events.
=> fix: All events should show every event instead of no events

pages/api/profiles/[username]/links/[_id].js
The redirect code for link URLs would decode them.
This may be a leftover from before we used link IDs.
It can create problems from multi-byte characters that are encoded.
=> Don't decode link URLs

components/user/UserHorizontal.js
fixes #8521 
- I removed only the scaling animation on hover, The hover color and duration, have not been changed.
Before I made the changes
After I removed the scaling animation on hover
- The text blurring is more noticeable when using FireFox than Safari.
- The scaling seems to affect the users text on the cards with tags than the cards with no tags.
- Due to the scaling animation the space between the search bar and the top line of row of cards was maybe 4px and     without the scaling the space about 8px. (I am just estimating the px)
=> Removed hover:scale-105 to fix issue #8521

components/map/UserMarker.js
Adds the `Link` classes to the `UserMarker` component.
Alternatively it could probably be better to add a prop to `Link` to dynamically disable dark mode text colour.
Closes #8979
=> fix: map usermarker link in darkmode

components/Modal.js
fixes #8959 
Removes the big margin from small screens, so the layout isn't cut.
Before: 
After:
Thank you!
=> Fix QR-Code layout cut issue in small screens

package-lock.json, package.json
Upgrade the BioDrop CLi to 2.7 that adds the support for Font Awesome 6 icons
=> fix: upgrade the BioDrop CLI

pages/account/manage/testimonials.js
fixes #8947
Wrapped the profile picture element in a flex div.
The testimonials in the account page currently look off from a spacing perspective. I would suggest to also adjust it by using the public testimonials as an example since it looks way better. I think it's best to open another issue for that as it is a bit more broad in scope than the current one.
=> Fix avatar size testimonials

components/Link.js, components/form/Label.js, components/navbar/Navbar.js
Adding an `aria-label` to links using children adds garbage when children are components.
Using `hidden` on labels removes them from the DOM, changing to `sr-only`.
=> Fix accessibility issues on profile page

tests/profile.spec.js, tests/setup/global-setup.js
=> fix: test to check repo tab

components/layouts/Alert.js
Closes #9299 
- Adjusted the alignment of the "give us a star" banner to enhance readability on mobile devices.
- Addressed the reported issue regarding improper alignment, aiming to improve UI/UX consistency within the application.
Mobile Original         
:--------------------:
Mobile Updated       
:--------------------:
=> Fix mobile give us a star banner styling

pages/docs/open-source-roadmap/where.js
Closes #9327 
Changed Typo mistake on page https://www.biodrop.io/docs/open-source-roadmap/where, changed `Join` to `Joining`
=> Changed join to joining

.github/workflows/check-author-issues.yml
Fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9642
YAML error https://github.com/EddieHubCommunity/BioDrop/actions/runs/6675840481/workflow
=> ci: fix gh action issue

components/Footer.js
Closes #9653 
- Fixed a typo mistake in Footer section for Open **_Souce_** Roadmap to Open **_Source_** Roadmap link
=> fix: typo in footer links

components/layouts/MultiLayout.js
Closes #9618 
- By increasing the `z-index` of the `<main>` element, the Icon copy notification now displays over the navbar correctly.  
- This fixes the issue where the notification text elements were hidden under the navbar menu. The intended stacking order now functions properly without conflict.
After Fix:
To visualize how these z-index values affect the layering,
https://github.com/EddieHubCommunity/BioDrop/assets/57263951/0bee8633-bc1f-4d18-9408-5de30aeed71b
To resolve this issue, after increasing the z-index value in the `<main>` element from 10 to 40. The video displays the notification above the navbar in the layer hierarchy.
https://github.com/EddieHubCommunity/BioDrop/assets/57263951/11d1cbad-1949-4c53-9420-f3ad21bcdde5
Check PR #9652 for full Triage details
=> fix: Navbar overlaps with Icon notification

components/navbar/Navbar.js
Closes #9731
- Increased the `z-index` of the mobile navbar menu element specifically for dark mode to make it stack above the main content.
- The mobile menus are now functioning correctly on dark mode.
After fix:
This bug was missed to check in PR #9726
=> fix: navbar menu layering bug in dark mode

tests/search.spec.js
Closes #9727 
Use test profiles for all search tests
use `waitForURL` to ensure URL changes before check
=> Fix Search tests

styles/animation.module.css
In Safari a background is shown when adding the `glow` animation effect to the Social Media Buttons (Links Section on Profile). This is due Safari and Safari on iOS currently not supporting animation and transition on CSS pseudo-elements like `:after`, while other browsers do.
Resources: https://developer.mozilla.org/en-US/docs/Web/CSS/::after
Closes #9461 
By setting the `background-size` to `100%` to the `:after` animation, the bug disappears. Setting the value more or less than `100%` retains the bug, setting it to `0` would remove the glow as a whole, which is neither wanted nor needed. 
💡 Due to this settings, notice that the heavy glow effect is now gone in general in all browsers.
Please see screenshots of the changes in Safari Browser.
I added a `/* comment */` to the `line 43` of …
=> Reduce bg-size on :after to fix Safari bug

.github/ISSUE_TEMPLATE/bug.yml
Closes #9742 
To add a required "Steps to Reproduce" section in the bug issue template to reduce the workload for maintainers and help them to reproduce bugs more quickly and easily, which will lead to faster fixes.
In `bug.yml` template:
- Added new `Steps to Reproduce` property 
- Added guidelines/instruction in comment line of value.
- This section is mandatory to provide the bug steps.
YML Github Preview (not from actual user issue creation)
I added instruction in comment line of textarea field instead of placeholder. So that, contributor can copy the sample template and provide the steps. In case of placeholder, they need to manually type and it usually disappear when we type something in Textarea.
Please let me know if you have any feedback on whether to use a placeholder or a value …
=> feat: New 'Steps to Reproduce' section in bug template

components/navbar/SideNav.js
Closes #9486 
Now, the docs side-nav link click will not refresh the full page. All docs pages will load without refreshing the URL.
https://github.com/EddieHubCommunity/BioDrop/assets/49125977/8ef33efd-52c7-475e-b14b-667c4139bab7
=> Fixed : Docs URL refresh when using side nav issue #9486

components/tag/TagsInput.js, pages/account/manage/event/[[...data]].js, pages/account/manage/profile.js, pages/docs/how-to-guides/editing-forms.mdx
=> [FEATURE] Improvement - char limit on tags

components/ConfirmDialog.js
Closes #9765
- By increasing the base `z-index` style of the Dialog component, the modal now appears above main content properly in dark modes.
- Increased `z-index` value of from 10 to 40.
**Before fix:**
**After fix:**
- I have manually validated that the modal now displays properly when deleting events, links, milestones, and repos.
- Please test that the modal also appears on the testimonials page when deleting a testimonial in dark mode.
> Note: Might be a better solution
This issue occurs only in dark mode. Should we use the `dark:z-40` class instead of updating the `z-10` class? I wanted your opinion on the best solution for proceeding further.
=> fix: z-index issue of confirmation dialog modal in dark mode

pages/account/manage/profile.js
Closes #9829
I've added a character count next to the note `You can use Markdown syntax.` on bio textarea.
<details>
<summary>Mobile</summary>
https://github.com/EddieHubCommunity/BioDrop/assets/22430210/9b7349c5-597e-4abd-9400-539bd840482b
</details>
<details>
<summary>Desktop</summary>
https://github.com/EddieHubCommunity/BioDrop/assets/22430210/2e60609b-3433-4dfb-8bc7-37b447a3a243
</details>
=> feat: show current character length on bio

components/navbar/SideNav.js
Closes #9517 
Changed the following lines, to control the collapsing of the main menu (prevent them from collapsing), when sub-menu links are clicked:
```diff
--- <Disclosure as="div">
+++ <Disclosure defaultOpen={item.children.some(subItem => subItem.href === pathname)}>
```
After:
https://github.com/EddieHubCommunity/BioDrop/assets/71211731/e59650e8-fd6b-4ed5-9260-76389696ca95
Before:
https://github.com/EddieHubCommunity/BioDrop/assets/71211731/335df6f2-59ef-444b-b0d8-4b0f16107cae
=> feat(docs): improve navbar navigation to prevent menu collapsing

components/user/UserMilestone.js
Closes #9824
- Removed `rounded-full` class from DisplayIcon component
- Confirmed overflow no longer occurs with **FaCodeBranch** and **FaDev** icons as well as other milestone icons I tested.
- Tested on accounts milestones page
| Light | Dark | 
|---|---|
| ![image](https://github.com/EddieHubCommunity/BioDrop/assets/57263951/5f265e30-be2b-4e1d-8e33-dba254ad75dc)  | ![image](https://github.com/EddieHubCommunity/BioDrop/assets/57263951/087f4ca7-7433-4c54-a587-63064d2da10d) |
=> fix: Milestone Icon Overflow by Removing Rounded Styling

components/tag/TagsInput.js
Fixes #9869 
Screenshot 1: 
Above image shows the case when no tags are added to profile or events page. In this case the tags section is hidden.
Screenshot 2:
This images shows visibility of the tags section when tags are added.
=> [Fix]: Dragging Input field for Tags gives Error

data/Prashanth-bokkala.json
=> data: Prashanth-bokkala

data/Prashanth-bokkala.json, data/gekkowrld.json
- Did a check and found `avatar`, `displayStatsPublic`, & `type` keys in these 2 files, which are no longer used. 
- Removes these unwanted keys from JSON files.
- Please be careful with data PRs too & request contributors to remove `avatar`, `displayStatsPublic`, or `type` keys if used in their `json`,  as they no longer need to set these keys manually in their json.
=> fix: remove avatar & type keys from json files.

pages/docs/how-to-guides/testimonials-json.mdx
Closes #10055 
Updated the Testimonial addition process in the docs, now that the `Add Testimonial` button has been removed.
The new process now includes the following steps:
- Go to the Issues Tab
- Create a new Issue
- Select the type `🏆 Testimonial`
- Fill in your testimonial
Before:
After:
=> fix(docs-testimonial): Update Testimonial Addition Process

.github/workflows/vercel.yml
The following warning appears on every run:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dorny/paths-filter@v2.
```
This PR updates the `paths-filter` action to a version that uses Node 20.
=> Update paths-filter action version

pages/docs/environments/local-development.mdx
fixes #9830 
Added an extra step that informes users to check if their docker daemon is running, which is required to handle docker commands. The optimal way is to launch the Docker Desktop applications, available for Windows, Mac and Linux, which will start the daemon automatically in the background. If the users have installed docker through the cli, I've asked them to refer to the official documentation [here](https://docs.docker.com/config/daemon/start/) which lists the commands to run the daemon, based on the operating system.
Before:
After:
=> Docs(local-development guide): Add a step to local development using Docker

components/IconSearch.js
Closes #10203
Normal Mode:
Dark Mode:
I have added a screenshot, and it's working fine in both normal and dark mode.
=> Fixed the Issue #10203 - The icon drop-down suggestions are not visible properly

pages/icons.js
Closes #10249
Typo is fixed. filterredIcons is modified to filteredIcons
=> fix: Typo in pages/icons.js

data/MhL5.json
=> data: MhL5

config/app.json
=> fix: archive alert message

components/layouts/MultiLayout.js, middleware.js, pages/account/manage/premium.js, pages/account/statistics/index.js, pages/account/statistics/link/[id].js, pages/account/statistics/locations.js, pages/account/statistics/referers.js, pages/api/account/statistics/link/[id].js, pages/pricing.js, tests/account/stats/location.spec.js, tests/account/stats/referer.spec.js
closes #10360 
- Premium features will be available to everyone
- Custom domain is no longer available (form field disabled)
- Existing custom domains will still work
=> feat: removed premium plan

pages/search.js
Closes #9839
[clearfilter.webm](https://github.com/EddieHubCommunity/BioDrop/assets/65010518/fe3e2479-4648-4f9e-99e0-d77e216b0980)
=> feat: clear all tags in one click button added in search page

components/Loading.js, pages/search.js
Closes #9738 
- Add reusable `Loading` component in the `components` folder (The `Loading` is aligned both, vertically and horizontally inside the parent)
- Set a local state for handling the loading status (set it to `true` when the `fetchUsers` function is called and false when it ends)
Extra:
- Remove duplicate logic for rendering the list of the users
- Render one piece of content at the time by chaining all the `if`s
https://github.com/EddieHubCommunity/BioDrop/assets/1851658/8b2863d9-55a6-4d4f-895d-c4fb85ca19fa
Do you think I should include a fix for this warning as well? 
```
./pages/search.js
153:6  Warning: React Hook useEffect has missing dependencies: 'BASE_URL', 'pathname', and 'replace'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
```
=> Fix (9738):  Prevent showing the initial state when changing query [search page]

components/navbar/Navbar.js
Closes #10305 
The proposed enhancement aims to maintain consistency in the color scheme throughout the navbar. By unifying the color scheme to red/pink for all elements, including during hover states and across different modes (light/dark), the visual aesthetic of the navbar will be improved, providing users with a more cohesive and seamless experience.
I've made adjustments to the code to accommodate specific circumstances. Please review the changes and let me know if anything further is needed.
=> feat: update navbar hover effect (#10305)

components/Footer.js, pages/account/statistics/index.js
• Closes  #10327 
* Call the authentication library to check for user connectivity.
* Add conditional rendering for the "Login" link in the footer navigation. The link is only shown if the user is not logged in.
https://github.com/EddieHubCommunity/BioDrop/assets/147720951/29fa3da0-0bcd-4601-9fbc-7fd2c9d0b57a
* In the uploaded screen record, I used the login button in the footer section to show that it's still working correctly.
=> Solved Issue #10327 : Remove login link from footer section

.github/workflows/build.yml, components/layouts/MultiLayout.js, middleware.js
Redirect all profile requests to their GitHub profile
For example `BioDrop.io/eddiejaoude` -> `GitHub.com/eddiejaoude`
=> feat: archiving project redirect to github profile

components/user/UserRepos.js, pages/account/manage/repos.js, pages/api/account/manage/repos.js
While trying to solve the issue https://github.com/EddieHubCommunity/BioDrop/issues/10364 I noticed the ```Add Repo``` button wasnot working as expected the button would remain disabled once I one repo since the ```isDisabled``` value is never turned to false after adding the repo.
=> fix: add repo button in manage repo page 
