data/Shashankzz0007.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> username.json file added

data/CodingSpecies.json
#2307 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2312"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Profile

data/rossanodan.json
This pull request adds a new profile page for Rossano D'Angelo (myself)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2319"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> rossanodan: creating profile page

data/RotrixLOL.json
Added my profile!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2313"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add RotrixLOL

tests/search.spec.js
Add a playwright test that navigates to the homepage, clicks on the search link, and checks if the Search page contains an h1 with "Search" in it.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2291"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test: implement navigate to the search page

README.md
Closes #2229
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2324"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Docs: Improve Hacktoberfest Guidelines

data/panquesito7.json
- Update my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2327"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: update my profile

data/rossanodan.json
This pull request updates Rossano D'Angelo's website URL (got a new fancy domain 🤩 )
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> rossanodan: update website url

README.md
This PR responds to some aspects brought up by issue #1221. 
I'm suggesting a different wording for the 'To Add Your Profile' section. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2326"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update To Add Your Profile section

components/user/UserTabs.js, pages/[username].js
closes #2334 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: show count in tabs + hide tabs (#2334)

data/mrabro.json
Added my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [data]: added mrabro profile

tests/search.spec.js
Add test that checks if there are no results displayed when you only type 2 characters into the search field.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2340"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test: typing 2 characters in search

tests/search.spec.js
Add test that checks if no results are shown when no search term has been entered
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2338"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test: no search term used

components/Event.js, components/user/UserMilestone.js, data/Klaus.json
closes #2332 
Let me know if there is any changes required !
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added Markdowns to milestones and events description

components/Event.js, data/eddiejaoude.json
- removed console error
- centered icon(s) in event list item
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2345"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: markdown for events

components/Footer.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2346"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: footer improvements

components/user/UserProfile.js, components/user/UserSocials.js
fixes #2305 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: social icons increment stats

.github/ISSUE_TEMPLATE/testimonial.yml, .github/workflows/deploy.yml, .github/workflows/testimonial.yml
Not testable via a branch
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Testimonials via issues

data/loftwah.json
[#2286](https://github.com/EddieHubCommunity/LinkFree/issues/2286)
Updating my bio.
Fixes the issue where I had too many characters in my bio for the cards in the UI.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2365"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update bio in my profile

tests/search.spec.js
Add test for search page shows result after typing 3 characters
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add test for search result with 3 character

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2371"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [ README ] Outdated Gitpod demo Removed

data/Aadarsh805.json
Added my profile to the data folder named Aadarsh805.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2387"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added my profile Aadarsh805.json

data/Chimise.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2393"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add profile data Chimise.json

data/Aadarsh805.json
Fixed the twitter icon from my profile Aadarsh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2399"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile update icon fix

data/Saurav-Pant.json
I want to add my profile on LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile Updatation For LinkFree

pages/api/statistics/today.js, pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2391"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Homepage statistics

pages/api/events.js, pages/api/users/index.js, pages/api/users/popular.js
closes #2405 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2406"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: ignore invalid json files #2405

data/Jaideep25-tech.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2403"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create my profile and added data to it for generation of linkfree link

data/Manda-supraja26.json
updated json file with name Manda-supraja26
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2410"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Supraja's Contribution

components/user/UserProfile.js
Closes #2411 
Added cursor-pointer class to wrapping div.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2412"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Simple cursor fix

next.config.js
Lang attribute fix for #2382 
Sets html tag to 
```html
<html lang="en">
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add lang attribute to html tag

data/Jisan-mia.json
updated json file with name Jisan-mia
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2417"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Jisan's Contribution

data/bhattabhi013.json
Added my links and created JSON file for the same.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added bhattabhi013 profile

data/AngelofVerdant.json
:x:  Added and updated LinkFree profile JSON file 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2418"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added my LinkFree Profile💪

data/agung2001.json
- Add my profile to data directory `data/agung2001.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2419"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add agung2001.json to data directory

data/eddiejaoude2.json
do **not** merge
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2422"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Eddiejaoude2 patch 1

docs/contributing/contributing-your-profile.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1916"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile adding guide for beginners

data/adityasimant.json
Added links to my Linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated my Linkfree

data/Stevenovak123.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2299"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated Stevenovak123.json

data/indigo423.json
Deleted the Twitter account from my profile which is deleted.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2433"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: Remove Twitter account

public/samsorrahman.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2435"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> file added for LinkFree project

data/Sativarsainath-26.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2434"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> created personal profile

data/rupeshexe.json
Added rupeshexe.json file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2439"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added rupeshexe.json

data/Krishnapro.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2438"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Krishna profile update

data/mahesh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2442"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Mahesh Profile Added

data/anurag-rajawat.json
Added `anurag-rajawat.json` file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: Add my profile to LinkFree

data/panquesito7.json
- Update my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2455"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update my profile

data/ItsPiyusha.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2457"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Add ItsPiyusha.json

data/eddiejaoude.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Sara jaoude patch 7

components/user/UserProfile.js
fixes #2459
The vertical gap between the QR code and select on the profile page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix QR code margin for mobile

pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2469"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: strapline

data/Rishav-12.json
Update Rishav-12's profile by adding `tags` and `displayStatsPublic`
N/A
N/A
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2462"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: update Rishav-12's profile

data/OleanjiKingCode.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2475"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: OleanjiKingCode

data/md-abid-hussain.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2473"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: md-abid-hussain

data/yesayajones.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: add twitter account info for yesayajones

README.md
Closes #2478
Changed the number of ways to 4 from 3 in README.md file where it says number of ways to contribute.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Corrected number of ways to 4 in README.md

data/Priyanshii677.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Priyanshii677

data/sharatkatwa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Create sharatkatwa.json

data/sharatkatwa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update: sharatkatwa.json

data/GaganpreetKaurKalsi.json
PR adds profile of [**GaganpreetKaurKalsi**](https://github.com/GaganpreetKaurKalsi)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2490"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add GaganpreetKaurKalsi Profile

components/Page.js, components/layouts/DocsLayout.js, pages/docs/advanced/single-user-mode.mdx, pages/docs/contributing/automated-tests.mdx, pages/docs/contributing/hacktoberfest.mdx, pages/docs/contributing/storybook.mdx, pages/docs/environments/github-ui.mdx, pages/docs/environments/gitpod.mdx, pages/docs/environments/local-development-docker-compose.mdx, pages/docs/environments/local-development.mdx, pages/docs/faqs.mdx, pages/docs/full-profile-example.mdx, pages/docs/how-to-guides/bio.mdx, pages/docs/how-to-guides/editing.mdx, pages/docs/how-to-guides/events.mdx, pages/docs/how-to-guides/links.mdx, pages/docs/how-to-guides/milestones.mdx, pages/docs/how-to-guides/socials-shortcuts.mdx, pages/docs/how-to-guides/statistics.mdx, pages/docs/how-to-guides/tags.mdx, pages/docs/how-to-guides/testimonials.mdx, pages/docs/index.js, pages/docs/quickstart.mdx
closes #2495 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: docs to have titles #2495

pages/docs/index.js, tests/docs/docs.spec.js, tests/docs/quickstart.spec.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2500"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> test: for docs

data/tobySolutions.json
Add tobySolutions' profile 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:tobySolutions

data/kartiklk.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2499"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Kartik khode

components/IconCard.js, pages/docs/index.js, pages/docs/quickstart.mdx, pages/icons.js, tests/icon.spec.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2512"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: searching icons (#2472)

data/iamr-kumar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2480"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create profile for iamr-kumar

components/user/UserProfile.js
Closes https://github.com/EddieHubCommunity/LinkFree/issues/2466 and https://github.com/EddieHubCommunity/LinkFree/pull/2468 issue
Before 
After 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2514"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed QR code mobile view issue 

components/navbar/Navbar.js
I made line 77 more accessible
[2382](https://github.com/EddieHubCommunity/LinkFree/issues/2382)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2506"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added aria-label

.github/workflows/json-check.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2517"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: only run json check on data file changes

data/Gauravkumar2701.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2518"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> profile addition

data/panquesito7.json
- Remove a duplicate link in my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: remove a duplicate link in my profile

data/Skagra42.json
Create data/Skagra42.json, which contains the data for Skagra42.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Skagra42

components/Event.js
Closes #2467 
- Made event Page responsive on Mobile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Fix]:Responsiveness-Event Page

components/user/UserProfile.js
Closes #2465
- Made the profile page responsive on mobile sceens
@eddiejaoude  I made the whole PR again and solved the issues we had in the other one I closed
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2530"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [add]:responsiveness-profile page

data/iamrahul8.json
Added my Profile data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2534"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added my Profile : iamrahul8.json

data/adityassharma-ss.json
Added My details, links & milestones in the data folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2543"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Created] data: adityassharma-ss.json

pages/index.js
closes #2544 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2546"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: homepage features + screenshots #2544

data/Valentine-chinedu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2547"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Valentine-chinedu

components/Footer.js, components/user/UserProfile.js, components/user/UserSocials.js, pages/docs/index.js
Fixes the remaining issues in #2382 
Increase contrast ratio for footer links
Add labels to profile social links
Fix profile contrast
Fix docs link contrast
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2545"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Accessibility Cleanup

data/uddinArsalan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:uddinArsalan

components/event/EventCard.js, components/event/EventKey.js, components/user/UserEvents.js, pages/events.js
Profile events has key like main events page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: profile events has key

components/user/UserTabs.js
Fixes tab sorting issue
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2553"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: use event propogation to stop changeTab function to reset tabs

data/legendarykamal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2554"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created my data

data/Kaleem-abdull.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2557"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Kaleem abdull patch 4

data/imtiazpy.json
Added my profile info.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:imtiazpy

data/aryasoni98.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create Data aryasoni98.json

data/krupalitrivedi.json
Editing the LinkFree profile already present for @krupalitrivedi 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: krupalitrivedi

data/mocdaniel.json, data/mocdaniel/events/2023-02-07-civo-navigate.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2580"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mocdaniel

data/avie-dev.json
Add Display Status to Public
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2585"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Display Stats to Avie's profile

data/shyam0705.json
Created my LinkFree Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created my LinkFree profile

data/OlojaMuyiwa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2601"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added OlojaMuyiwa.json

data/Kaleem-abdull.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Kaleem-abdull

data/loftwah.json
Updating my profile information.
N/A
Updating my profile to enable the new stuff.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2596"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Couldn't sleep so updating profile

data/Patelrahul4884.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2608"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Patelrahul4884

data/fluentmoheshwar.json
[x] Added website link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2609"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added website

data/accodes21.json
updated profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2612"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated My Profile

data/khalidx3.json
Check List (Check all the applicable boxes)
The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2584"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: khalidx3

data/abhijeet-26.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> abhijeet-26.json file added

data/SivaReddy184.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2613"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:SivaReddy184

data/aravindraveendran7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aravindraveendran7

data/Pradumnasaraf.json
- Added testimonials section `"testimonials": [""],` to my LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Enable testimonials on Pradumnasaraf's profile

components/user/UserCard.js, pages/[username].js, pages/docs/how-to-guides/testimonials.mdx, pages/index.js
fixes #2443 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2627"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Testimonial button added to profile page

data/maina401.json
Add file maina401.json, containing my profile data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Maina401

data/thebarshablog.json, data/thebarshablog/events/2023-05-16-kubehuddle-conference.json
Hurray! Created My LinkFree Profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: thebarshablog

data/ShreeyashGarde.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ShreeyashGarde

pages/api/users/popular.js
#2581 
it will remove those profiles whose stats are not public
Have made the changes now instead of filtering the profiles initially it will do that after checking if the profiles have status public or not and after that if they are public it will show the profiles and from those profiles it will slice the first 10
Do lmk if there is anything to change !
Thank you !
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> removed profiles from popular whose stats are not public

data/jarek-pacocha.json
Add my profile to the LinkFree platform.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: jarek-pacocha

data/xperience001.json, data/yashsharma999.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2634"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Yet another branch

data/CBID2.json
I updated the Links and Milestone sections to my Linkfree profile. 
Feel free to comment on my formatting. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added link to my blog in the Links and Milestones section

data/loftwah.json
Updating LinkFree profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2684"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add testimonial from CBID2

data/CBID2.json
[#2682 ](https://github.com/EddieHubCommunity/LinkFree/issues/2682)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added a testimonial section

pages/docs/index.js
Closes #2673
- Add `break-words` to `index.js` in `pages/docs` to fix the link going off the page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2688"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Line Break To Docs

data/sharipoff-0-1.json
Hey, it is my first open-source contribution, happy to be part of the community.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2693"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:sharipoff-0-1

data/senali-d.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2706"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add senali-d profile

data/RobRuizR.json
Added myself to the list of users
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2709"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RobRuizR

data/ShanmukhiKairuppala.json
added ShanmukhiKairuppala to link free 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2713"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ShanmukhiKairuppala

data/dannyhw.json
Adds links for dannyhw to the data folder
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2722"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: dannyhw

data/A10-g.json
created profile thanks to Eddie's documentation
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2723"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:A10-g

data/Pradumnasaraf.json
- Add MadhuSaini22 testimonial in my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Pradumnasaraf

data/BaileyLuu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2747"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:BaileyLuu

data/Ugyenwangdi.json
Adding Ugyen Wangdi's LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ugyenwangdi

data/Ayaan49.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Ayaan49

data/AftabAhmedAbro.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2736"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AftabAhmedAbro.json

data/mslepko.json
Adding https://github.com/mslepko profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding Mslepko user

data/tobySolutions.json
- [x ] My change requires changes to the documentation.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Toby solutions patch 4

data/shubhsharma19.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2749"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shubhsharma19

data/Avi-88.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2770"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Avi-88

data/Ellah120.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2730"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Ellah120

data/HarshPanchal26.json
hey , I just added my all data , for LinkFree community , Requesting for look up to it and accept my merge request.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2751"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:HarshPanchal26

data/Elozino.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2760"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> created Elozino.json

data/shwetavish.json
Adding Shweta Vishwakarma's LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2761"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shwetavish

data/utkarsh1311.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2764"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:utkarsh1311

data/Mvishal123.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Mvishal123

pages/docs/quickstart.mdx
Closes #2536 
- Added image to step 3. Highlighting the star button
- Updated step 4 image highlighting the fork button
- Added a new image at step 6 showing how to create a file.
step 3
step 4
step 6
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2649"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated images in quickstart.mdx 

data/suchakra012.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:suchakra012

data/AasthaShahCodes.json
It's my first contribution. Edits are appreciated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2776"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:AasthaShahCodes

data/Saha-7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2721"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile update

data/king0203.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: king0203

data/krshkun.json
Made some changes to my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: krshkun

data/Aayush987.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2804"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Aayush987

data/YashPimple.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2784"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:YashPimple

data/Harsh971.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Harsh971

data/priyapahwa.json
This PR incudes:
- `priyapahwa`'s LinkFree
Signed-off-by: priyapahwa [pahwa.priya19@gmail.com](mailto:pahwa.priya19@gmail.com)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2801"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: priyapahwa

data/RoHit4100.json, data/suchakra012.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2800"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RoHit4100

data/KrishChopra22.json
One more contribution to EddieHub Community! 🥳
Created linkfree profile - the open source project ✔
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2780"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data : KrishChopra22 ✅

data/Omar8345.json
Add myself to LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2748"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Omar8345

data/lonebots.json
- added `lonebots.json` file in `data` folder 
The details include the following items
- developer background details
- social media link
- portfolio link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2811"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: added lonebot's profile

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2796"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix-readMe

data/esau-morais.json
This PR adds me as part of the GitHub UI
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2792"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add esau-morais to LinkFree

README.md
Grammar and spell checks.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2816"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated: grammar and spelling checks

data/BruceWangyq.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2793"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: BruceWangyq

data/Trikcode.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2826"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Trikcode

data/ssvali.json
Creating eddiehub linkfree url
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2807"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ssvali

data/Ravi-Rsankar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ravi-Rsankar

data/marlonaesparza.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2827"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: marlonaesparza

pages/docs/quickstart.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed the Typo on line 128

data/Yashkapure06.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2838"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data :  Yashkapure06

data/riteshgharat.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2842"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:riteshgharat

data/karntheai.json
I've made this changes to create my LinkFree Account.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2845"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:karntheai

pages/api/statistics/totals.js, pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: total and active users

data/iamunnip.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed twitter url typo

data/Shumaila-sayed.json
Creating my linkfree profile
This is my first pull request ever to a repository which is not mine. Thank you for this opportunity Eddiehub!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2852"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Shumaila-sayed

data/Njong392.json
Added socials, more links, statistics, and 2022 milestones.
- Added new sections to my profile to update it.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2854"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updating my LinkFree profile

data/hitarth01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2878"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:  hitarth01

data/A10-g.json, data/hong-codes.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2831"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: hong-codes

data/Abdulwahid7027.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2873"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data Abdulwahid7027

data/YashPimple.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2883"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: YashPimple

data/money8203.json
Update my profile:
- Added links to certain social platforms
- Added social shortcuts
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2887"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: money8203

data/WasiqB.json
=> Renamed file to match GitHub username casing

data/adityaiiitL.json
Changed and corrected some links in the file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2859"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Corrected some links in the file

data/YashPimple.json, data/adetoye-dev.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2890"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Add linkefree profile (Adetoye)

data/Aadarsh805.json
Fixed a typo in my own profile and add a tag
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2895"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile update: fixed typo and added one more tag

pages/api/users/discover.js
fixes #2898 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2899"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: discover has no data #2898

components/navbar/Navbar.js, models/ProfileStats.js, pages/api/users/[username].js, pages/api/users/recentPopular.js, pages/recentPopular.js
Added Schema and code for storing daily views on user profiles and added separate section for showing the most popular profiles of the last 28 days.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Schema and code for storing daily view on user profiles

data/fatimakay.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2863"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:fatimakay

data/david-kariuki.json
Create a new profile for David Kariuki [David Kariuki - Github](https://www.github.com/david-kariuki)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create new profile

data/rattandeep1998.json
Added data for @rattandeep1998 LinkFree profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2889"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rattandeep1998

data/ShivangShandilya.json
This PR adds my profile to LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2865"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ShivangShandilya

data/shivaabhishek07.json
- I have created my own linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2860"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:shivaabhishek07

.github/workflows/release.yml
=> fix: debug release action

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2961"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: wrap in json gh action

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2963"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: gh action debug

.github/workflows/release.yml
=> fix: debug gh action

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: removed debug action code

data/ChinmayMhatre.json
Updates on my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2960"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ChinmayMhatre

.github/workflows/release.yml
=> fix: removed gh action path ignore

data/pratikkumar-mohite.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2956"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:pratikkumar-mohite

data/tiyabansal.json
Profile data added
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2954"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:tiyabansal

pages/discover.js
Closes #2686
Refresh the profiles at the Click of a button
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2888"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Feat: Refresh Random Profiles

pages/discover.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2996"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: random profile refresh

pages/index.js
fixes #2632 
Have changed some images since it had some half texts so changed it to make the UI look cleaner
do lmk if there are any changes required !
Thank you !
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> changed 2 images to make the ui clean

data/Parsifal-M.json
Hey :wave: I hope this is okay? Please let me know if otherwise.
Thanks!
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2925"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Parsifal-M

data/Somidh.json
Created my own profile 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2932"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile added data:Somidh

data/vinzvinci.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: updated vinzvinci profile

.github/workflows/testimonial.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3027"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: testimonial action protected main

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3040"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: trigger release action on testimonial

data/amirahnasihah.json
My first open-source contribution
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3008"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: amirahnasihah

data/srijoy-paul.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2769"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:srijoy-paul

data/KiranAminPanjwani.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3073"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : KiranAminPanjwani

data/EddieHubCommunity/testimonials/krshkun.json, data/Pradumnasaraf/testimonials/krshkun.json, data/avie-dev/testimonials/krshkun.json, data/eddiejaoude/testimonials/krshkun.json, data/loftwah/testimonials/krshkun.json, data/thebarshablog/testimonials/krshkun.json, data/tobySolutions/testimonials/krshkun.json, data/web3community/testimonials/krshkun.json
Added testimonials for @Pradumnasaraf @avie-dev @eddiejaoude @loftwah @thebarshblog @tobySolutions @WebXDAO/core-team, if anyone of you would like to add it to your linkfree profile, please refer: [docs](https://linkfree.eddiehub.io/docs/how-to-guides/testimonials)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3101"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: krshkun testimonials

data/Gauravdarkslayer.json
Added Gauravdarkslayer.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3131"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added GauravDarkslayer.json

pages/index.js
- Brought `<Link>` on the inside of `<h3>`
- indigo-600 and an underline on hover
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix anchor placement and style issue

pages/docs/quickstart.mdx
=> docs: quickstart

data/swagataroy30.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2994"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:swagataroy30

data/JenilGajjar20.json
I have updated my profile by adding **tags**, **socials** and **milestones**.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2999"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: JenilGajjar20

data/gabel.json
* Add [gabel](https://github.com/gabel/) profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3074"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gabel

data/souravsk.json
Update
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3085"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:souravsk

data/AkshayAwate.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3095"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AkshayAwate

data/ShivaRapolu01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ShivaRapolu01

data/pritamrajput.json
I want to contribute to the linkfree project by creating my profile on Linkfree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:pritamrajput

data/akebu6.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added GSOC and Hacktoberfest to profile

data/loftwah.json
add a testimonial from krshkun
Updating profile to show new testimonials.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add testimonial from krshkun

data/shubhsharma19.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3071"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated links, Fixed the milestones section.

data/piyush-sri.json
Added my profile with bio and social links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added my Contributor Profile to linkfree

data/Ritika-Agrawal811.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Ritika-Agrawal811

data/sid-khuntwal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:sid-khuntwal

data/priyanshumaitra.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3188"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:priyanshumaitra

data/CristianoFIlho.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update LinkFree CristianoFIlho 

data/abrokinla.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:abrokinla

data/Laxmankohar.json
I have added my own data inside data folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3269"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Laxmankohar

data/abewartech.json
Please add me, thanks
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: abewartech

.gitpod.yml
closes #3090 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3092"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> dx: gitpod first terminal

.github/workflows/prettier.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3284"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: GitHub action race condition

data/krshkun.json
adding toby's testimonial to my profile. Thank you @tobySolutions really really appreciated <3
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: profile krshkun

data/elyanah-aco.json
* Add my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3289"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: elyanah-aco

data/Panquesito7.json, data/Panquesito7/events/bugtrons.json
- Add an event to my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Panquesito7

data/saidurrahmanmisket.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:saidurrahmanmisket

data/Kunaaal13.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Kunaaal13

data/bello-olalekan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: bello-olalekan.json

data/piyush-sri.json
correct typo
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated my credentials

data/thamerla.json
- Add my profile to LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: thamerla

data/Himanshuch8055.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3348"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Himanshuch8055.json

pages/docs/how-to-guides/milestones.mdx
Closes #3294 
Spelling weeoe
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3352"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: typo error

data/nik132-eng.json
Create my linktree
@eddiejaoude 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3338"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:NikunjRohit

.github/workflows/prettier.yml, .github/workflows/release.yml, .github/workflows/testimonial.yml
1. Place Release, Formatter, & Testimonial actions in same concurrency group
2. Only run Formatter once a day at midnight UTC
3. Only create releases for changes outside the data directory.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Avoid main banch update race condition

data/EddieHubCommunity.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3405"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: EddieHubCommunity

data/AbhayKumarMittal.json, data/MitAbhay.json
This PR creates my new profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3278"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created my profile : AbhayKumarMittal.json

data/Tejender1521.json
Updated information and links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Tejender1521

components/Tag.js, components/user/UserProfile.js, pages/api/discover/tags.js, pages/discover.js, pages/search.js
fixes #3383 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3403"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: popular tags on discover page #3383

data/souravsk.json
Incorrect profile picture 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3425"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: souravsk

data/suvm7.json
Applying for LinkFree Profile Link.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3428"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:suvm7

data/krshkun.json
added LinuxGamer's testimonial
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3446"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: add LinuxGamer Testimonial

data/petegordon.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3448"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: petegordon.json

data/Aadarsh805.json, data/Aadarsh805/events/2023-02-03-hack_this_fall_hackathon.json
Added testimonials and an event to my LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3442"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Aadarsh805 added milestones and event

data/imtiazpy.json
Added blogging and freelancing to the milestones section
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3320"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added milestones

data/Megapreneur.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Megapreneur

data/Kel-VinTech.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Kel-VinTech

pages/index.js
On hover of the abbreviated user total, it will show the exact total number
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: total users

data/Pradumnasaraf.json, data/vinay-ksingh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:vinay-ksingh

components/user/UserTestimonials.js, pages/[username].js, pages/api/users/[username].js
fixes #3476 
There are no visual changes, only performance improvements
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3477"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: removed loading all users #3476

data/Tejender1521.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Social Links

data/Rishav-12.json
Added some `milestones` to profile
_N/A_
_N/A_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3449"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: add milestones to Rishav-12's profile

data/OGEmanuel.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Og emanuel patch 2

data/Himanshu-holmes.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Himanshu-holmes

data/kumarsonsoff3.json
updated mine profile, `kumarsonsoff3.json` 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3500"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update kumarsonsoff3

data/arpitghura.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update arpitghura

components/user/UserLink.js, components/user/UserSocials.js, pages/api/users/[username]/index.js, pages/api/users/[username]/links/[url].js, tests/profile.spec.js
* feat: api handle redirects
* broken code
* comment out tests
* tests
* tests
* remove
* directory for username
* directory for links
* api redirect
* changes
* Restore package-lock.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3502"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: api handle redirects (#3246)

components/navbar/Navbar.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Mobile nav

data/Balastrong.json
Added my profile :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Balastrong profile

data/AbbeyIT.json
Updated my bio and links and added milestones, tags, and socials.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3525"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update AbbeyIT

data/Sapnajha19.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3555"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Sapnajha19

data/VishalPraneeth.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> 'data: VishalPraneeth'

data/nickytonline.json
Adds the LinkFree profile for GitHub user nickytonline.
Adds my profile to LinkFree following the JSON format mentioned in https://linkfree.eddiehub.io/docs/quickstart
N/A
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: nickytonline

pages/docs/index.js
Closes #3512
I have changed `profie` to `profile`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3523"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Fix Typo in the Main Docs Page

pages/docs/how-to-guides/testimonials.mdx, pages/docs/quickstart.mdx, pages/index.js
closes #3507
Misspelt words have been corrected
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed misspelt words

data/RedHeadphone.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update RedHeadphone LinkFree

data/Ft4us5.json
fix JSON formatting manually as workflow didn't get triggered.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: fix JSON formatting

data/alroniks.json
I've added links to my profile.
Nothing to add
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3554"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:alroniks

data/nik132-eng.json
According Eddie It was to long so made it sort
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data:nikunj bio updated

data/safeeralehsan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:safeeralehsan

data/prnvtripathi.json
Updated the profile of prnvtripathi.json (Pranav Tripathi)
Please let me know if any updates or modifications are required.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3580"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updates in data:prnvtripathi.json

data/MahekUnnisa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3432"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:MahekUnnisa

data/ibilalkayy.json
Adding a profile to the LinkFree account
Thank you for letting me create a profile on LinkFree!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ibilalkayy

data/bhavanas-jpg.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> `data : bhavanas-jpg`

pages/docs/quickstart.mdx
=> fix: code example

data/thebarshablog.json
- Added MLSA tag to the bio headline.
- Added 2 milestones
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Barsha's Profile Update

pages/docs/index.js
The tags showing difficulty capitalized.
closes #3586 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3587"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs tags capitalized

data/Jagannath8.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3637"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Jagannath8

data/himanshubalani.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3634"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: himanshubalani

data/THammami01.json
Adding a `.json` file for my LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: THammami01

data/Blaize15.json
Added new file data/Blaize15.json
Signed-off-by: Md Moinuddin <noobycox@proton.me>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Blaize15

data/krshkun.json
Updating my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3627"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: krshkun update profile

data/aqib-m31.json
Add my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aqib-m31

data/BMayowa.json
Mayowa Obisesan's LinkFree Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:BMayowa

pages/docs/index.js
added "for"
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs improve under Available icons

pages/search.js
added the autofocus on the search bar in the search.js file .
when someone opens the search page , he/she can directly write without tapping on the search bar 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3565"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added the search focus

data/Aadarsh805.json
Added Eddie's testimonial to my profile
Thanks a lot, Eddie for the testimonial
[x] - Correct; marked as done
[X] - Correct; marked as done
[ ] - Not correct; marked as **not** done
-->
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3663"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Aadarsh805 Adding Eddie's testimonial to my profile

data/PSGitHubUser1.json, data/infoy_bio.json
- [  ] My code follows the code style of this project.
- [  ] My change requires changes to the documentation.
- [  ] I have updated the documentation accordingly.
- [  ] All new and existing tests passed.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3652"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: MyBio @PSGitHubUser1

data/ChinmayMhatre.json
Added Aadarsh's testimonial. Thanks @Aadarsh805 !🚀
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ChinmayMhatre

pages/docs/environments/local-development-docker-compose.mdx
closes #3437
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3670"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated docker compsose commad in docs

data/Manoj-Kumar13.json
This is my first pull request to create a profile on Linkfree and to get started with open-source.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Manoj-Kumar13

data/zishaxn.json
Created a Profile on LinkFree
Thanks For letting me Create a Profile. (:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:zishaxn

data/vidhimakani74.json
portfolio website and milestone section added
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3649"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:vidhimakani74

data/rayben109.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3676"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Rayben109

data/asingh101973.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3690"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:asingh101973

data/Anuj-Kumar-AJ.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:anuj-kumar-aj

data/zakariyahrobiat.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3624"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: zakariyahrobiat

data/lilmubby.json
added my data linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:lilmubby

data/krishnanunnijs.json
Added new profie link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: krishnanunnijs

data/Rishav-12/events/2023-01-24-springone-essentials.json
Added the virtual SpringOne Essentials event to my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3651"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Create 2023-01-24-springone-essentials.json

data/rukundob451.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3654"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:rukundob451

data/rayeesrather99.json
Approve my changes : )
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3697"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:rayeesrather99

data/loftwah.json
Add testimonial from eddie and also add milestones
Thank you very much.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3694"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updating profile to include testimonial and milestones

data/s4shantanu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3686"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: s4shantanu

data/baibhav-tiwari.json
Thanks for letting me to create a profile :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3696"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:BaibhavTiwari

data/kirtiraj22.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3704"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: kirtiraj22.json 

data/eddiejaoude.json
=> data: eddiejaoude

data/amandamartin-dev/events/2023-02-15-developer-week.json
This PR will add the Developer Week event in SF to my profile and the community events page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3710"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added devweek event to profile

data/ShubhamSinghgit.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ShubhamSinghgit

LICENSE
Closes #2834 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: licence year

data/Kirtikagoyal.json
renamed file and updated profile username.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Kirtikagoyal

pages/[username].js, pages/index.js
=> fix: horizontal padding on bottom right buttons (testimonials and help)

data/i-am-amrendra.json
Fixes a profile with invalid JSON
=> Fix JSON action

.github/workflows/reviewpad.yml
Avoid running reviewpad on the 3 actions that automatically create PRs
1. Release
2. Testimonial
3. Formatting
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3397"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Avoid running reviewpad on automated pull requests

.github/workflows/reviewpad.yml
=> fix reviewpad

data/CBID2.json
I could not find the icon for Dev.to so I used the FaFev one. If you can help me add the correct icon, that'd be great! :)
I could not find the icon for Dev.to, so I used the FaFev one. Can help me add the Dev.to one please?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3732"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added another website

data/CBID2.json
Changed icon for Dev.to
I found the right icon. Let me know if it works. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3733"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed icon for Dev.to

data/baibhav-tiwari.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3718"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Baibhav tiwari patch 3

data/prnvtripathi.json
Changed the URL of my portfolio website, due to redeployment
Let me know if any change is required. :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update: Changed the portfolio url.

data/ieshreya.json
Add profile for ieshreya.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3748"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ieshreya

data/MahekRohitGor.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3762"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:MahekRohitGor

data/Naziasuleman.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3751"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Naziasuleman

data/Ertan222.json
I created my linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ertan222

data/AussieDev81.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AussieDev81

components/user/UserMilestone.js, components/user/UserMilestones.js, data/eddiejaoude.json, pages/docs/how-to-guides/events.mdx, pages/docs/how-to-guides/milestones.mdx
Merged PR https://github.com/EddieHubCommunity/LinkFree/pull/2383 in to temporary branch and made tweaks
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3774"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Future goals

data/Haile-08.json
[![HcvHaGp.md.png](https://iili.io/HcvHaGp.md.png)](https://freeimage.host/i/HcvHaGp)
New register to the EddieHub Community
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3739"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Haile-08

data/Pradumnasaraf.json, data/bobbyy16.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3785"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Abhishek

data/Vyvy-vi.json
This PR adds my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3802"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore(data): add Vyvy-vi's profile

data/maheshkasabe.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3804"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update and rename to mahesh.json to maheshkasabe

data/Ertan222.json
I added and modified information to my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update Ertan222

data/Ankur6702.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated bio and icon in Ankur6702.json

data/snehap02.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:snehap02

data/aqib-m31.json
Add tags to my profile. 
Modify names of SM links.
Could you please review my profile! 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3824"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update data: aqib-m31

data/mcgonagle.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3822"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mcgonagle

data/linamiko.json
Initial creation of my LinkFree Page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3833"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:linamiko

data/Kirtikagoyal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3850"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update my linkedin profile link

data/J-Ankit2020.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3846"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:J-Ankit2020

data/Ananya2001-an.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3836"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Ananya2001-an

pages/docs/faqs.mdx
Updated the links as described.
Co-authored-by: Eddie Jaoude <eddie@jaoudestudios.com>
=> docs: faqs links (#3116)

data/sagar-ghub.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3882"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:sagar-ghub

data/priyankarpal.json
I updated my all links, added milestones, added tags etc.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3874"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: priyankarpal

pages/docs/faqs.mdx
- Fixed the incorrect reference to the hacktoberfest page in FAQs
=> fix: hacktoberfest page url

components/user/UserEvents.js
On user profile, it shows past events which is confusing. In the future we can have a toggle, but for now let's filter out the past events and only show the up and coming events
=> fix: show future events only

data/advaith-unnikrishnan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3901"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: advaith-unnikrishnan

data/piyush280599.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3913"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> piyush280599.json

data/lavanyayangala.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:lavanyayangala

data/mdrianislam0or1.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3875"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mdrianislam0or1

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/kubescape.yml, .github/workflows/prettier.yml, .github/workflows/storybook.yml
=> fix: bump node versions from 16 to 18 lts

pages/docs/contributing/storybook.mdx
=> docs: storybook deployed link

pages/events.js
=> fix: event tabs urls

components/event/EventTabs.js, pages/events.js, services/profiles/findOneByUsernameFull.js, tests/discover.spec.js, tests/events.js, tests/home.spec.js, tests/profile.spec.js
=> fix: event tabs url

components/user/UserMilestone.js
=> fix: milestone with no url

components/user/UserLinks.js, data/eddiejaoude.json, pages/docs/how-to-guides/links.mdx
fixes #2437 
NO GROUPs
WITH GROUPs
=> feat: group links #2437

data/prakhartiwari0.json
I have made some corrections to my Linkfree page and added the socials and tags
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Make some corrections and add tags & socials

data/Saadat-B.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3944"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Saadat-B

data/KrishnaTheCoder756.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: KrishnaTheCoder756

data/Tahsin-Zaman-Jilan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3977"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Tahsin-Zaman-Jilan.json

data/gurjeetsinghvirdee.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3972"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gurjeetsinghvirdee

data/Sheikh-JamirAlam.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3980"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sheikh-JamirAlam

data/Uthycloud.json, data/snehalsenapati23.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3982"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:snehalsenapati23

components/user/UserMilestone.js
=> feat: refactored milestones

.storybook/preview.js, components/navbar/Navbar.js
Fixes broken image in Navbar component in Storybook
=> Fix Navbar in Storybook

pages/search.js
Closes #3283 
Changed Search Users to Search Users,, tags or languages.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4001"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Placeholder change

pages/docs/how-to-guides/links.mdx
=> docs: grouped links

components/PageHead.js, pages/[username].js, pages/discover.js, pages/events.js, pages/icons.js, pages/index.js, pages/search.js
Moved `Head` to its own reusable component
=> feat: head to component

.github/scripts/check-filenames.js, .github/workflows/data-filenames.yml
=> Add GitHub Action to check profile filenames

components/event/EventCard.js
used the same hover transition which I used on the cards of the Discover page. Made a change to improve UI.
changed normal hover transition state of event card to scale out transition.
picture:
video:
https://user-images.githubusercontent.com/73755149/214652103-b68617d1-8ea3-4748-ab22-397d15e2b841.mp4
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3981"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added the same hover effect to the event cards.

data/FrancescoXX.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: FrancescoXX

components/hint/HintIcon.js, pages/events.js
`Closes #2903`
Closes #2903 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3738"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4036"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added hint icon

data/FrancescoXX.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4052"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Francesco xx patch 2

data/chriskalmar.json
Adding my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4040"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:chriskalmar

data/pritamrajput.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4039"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: pritamrajput

data/imbeshat.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4025"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: imbeshat

pages/docs/quickstart.mdx
Modified line number. 101 from twitter link to Instagram link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4009"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update quickstart.mdx

data/Dun-sin.json
- add Dun-sin milestones
- fix twitter link
- add socials link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4082"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add updates to Dun-sin

data/mhdamaan79.json
Adding a profile to the LinkFree account
Thanks for letting me create a profile on LinkFree!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4010"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mhdamaan79

data/mjr2595.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3999"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mjr2595

data/AussieDev81.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added testimonials to profile

data/Arceus-sj.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3978"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Arceus-sj

data/afreen0102.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4108"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : afreen0102

data/devsachinsharma.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4101"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Devsachinsharma patch 2

merwinmathew33.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4114"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:merwinmathew33

data/surajyadav1108.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4089"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: surajyadav1108

data/kushvahasumit.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4087"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:kushvahasumit

data/devvsakib.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4126"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: updated profile

data/haseebyousuf.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: haseebyousuf

docker-compose.yml, pages/docs/environments/local-development-docker-compose.mdx
- Improve Docker Compose dev docs
- Add data persistency
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add data persistency and improve docs - Docker Compose

data/Iyanu1396.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4107"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: Iyanu1396

.github/scripts/testimonial.mjs, .github/workflows/testimonial.yml
Closes #2666 
Use `JSON.stringify()` to create JSON with proper escaped characters.
Fix action warnings
=> Improve Testimonials action to handle special characters

stories/components/user/UserTestimonials.stories.js
Add story to test testimonials
=> Add storybook story for UserTestimonial

tests/profile.spec.js
Closes #3962 
Added a playwright test in the profile.spec.js 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4162"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Playwright test for redirecting when tag clicked 

pages/docs/quickstart.mdx
This pull request is regarding this issue:-
Add a link to jsonlint in the quickstart guide #3914
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added JSON Lint link to check for linting error.

data/mustafa-nds.json
adding profile to the LinkFree account
thank you 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mustafa-nds

data/priyankarpal.json
Added my themes links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added my themes

data/salmanakhtar57.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: salmanakhtar57

data/Mutai-Gilbert.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4134"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Mutai-Gilbert

data/Vee339.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Vee339

data/joshlong.json
Adding my profile to LinkTree, for your consideration. Thank you. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: joshlong

pages/api/discover/random.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: removing unused imports(fs and path)

data/Soumya-Kushwaha.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Soumya-Kushwaha

data/imran1509.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding testimonial to profile

data/Mumtaz12.json, data/joshlong.json
- Removed avatar key from rest other profiles which were merged recently. 
- From now on all profiles are using their GitHub profile as avatar. 
These profiles were merged by **me** & **Eddie** after the default GitHub avatar feature was implemented. Fixing this since avatar key is no longer used.
=> fix: use github profile

data/mustafa-edu.json
=> fix: use github avatar

data/Rishav-12.json
_N/A_
_N/A_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4214"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: add socials, update bio, tags and linkedin url

data/gurjeetsinghvirdee.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update gurjeetsinghvirdee

data/Sakshi.json, data/SakshiShah29.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> First Contribution

data/SwapnilPatle01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4233"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SwapnilPatle01

data/Sunkio.json
Thanks for reviewing my PR :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sunkio

data/yatharth1706.json
Added json for my linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yatharth1706

pages/index.js
Closes #4223 
I have now fixed the image alts with proper alts per the landing page illustrations.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Image alts

data/imran1509.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added one more testimonial on profile

pages/index.js
Closes #4252 
Image is higher quality and up to date to match how it looks on discovery page
Before:
After:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: update tags image

models/LinkStats.js, pages/api/users/[username]/links/[url].js
Record stats for daily clicks for each link
=> feat: record daily link clicks

data/SandipPalit/events/2023-02-22-aws-innovate.json
=> Added new event - AWS Innovate

data/souhaibsfaxi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2448"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: souhaibsfaxi

data/Tusharjagi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4285"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: Tusharjagi

data/Zuber8040.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Zuber8040 patch 1

data/ParasGoswami06.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4284"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ParasGoswami06

data/whysid.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: why-sid.json

data/rufilboy.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added rufilboy.json file

components/user/UserMilestone.js
closes #4149 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4312"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: milestone image is not supported

pages/index.js
Example: Closes #4236 
made a clean PR
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> removed extra main tag

components/event/EventCard.js, components/user/UserEvents.js, data/eddiejaoude/events/2023-03-10-devrelcon.json, data/eddiejaoude/events/2023-09-18-talk-infobip.json, pages/docs/how-to-guides/events.mdx
Profile events page 
Communit events page
=> Issue 3711

data/foss2cyber.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> foss2cyber patch 2

data/raghu-007.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4341"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: raghu-007

data/akhil3shh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: akhil3shh

data/Collins-Omariba.json
Added technical articles section.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4290"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update data: Collins-Omariba

data/theVatsal3802.json, data/theVatsal3802/events/25-01-2023-flutter-forward.json
Added `Events` Files.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: theVatsal3802

data/SandipPalit/events/2023-02-22-aws-innovate.json
fixing  event https://github.com/EddieHubCommunity/LinkFree/pull/4275
=> data: SandipPalit #4275

components/Tag.js, pages/discover.js, pages/search.js
closes #3849 
Added filtering option with tags on Search page as well. Users can select and deselect tags to get the desired results based on the combination chosen. For example: if I select tags open source and DevOps then only those users that have both of these tags will be shown. You can click on the tag again to remove the selection. You can also manually type out in the search bar to get the results otherwise use tags directly. When the user selects a tag from the discover page or their LinkFree profile, it will redirect them to the search page showing the results along with the highlighted tag.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Search page UI

components/Icon.js
Dynamically import Fa & Si icons to reduce bundle size.
=> Dynamically import icons

components/user/UserLink.js
=> fix: missing icon #4393

components/Tag.js, components/user/UserProfile.js, pages/discover.js, pages/search.js, tests/profile.spec.js
Minor tweaks from the great work by @Ananya2001-an on https://github.com/EddieHubCommunity/LinkFree/pull/4030
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4375"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Multi tag search

pages/index.js
fixes #4301
`sm` tailwind size
`md` tailwind size
=> fix: change md to sm #4301

pages/index.js, pages/search.js
Fixed tag triggering issue on search page where on clicking 'javascript' tag, 'java' tag was also getting highlighted.
Also updated screenshot for search tags on Home page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixed tag trigger issue

data/aadityadike.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4396"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aadityadike

data/TusharKesarwani.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4390"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: TusharKesarwani

components/user/UserLinks.js
=> fix: user links key

data/Chandupuram.json
Added all the social media links to my accounts with correct icons as mentioned in docs.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4405"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Chandupuram

data/shubhsharma19.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4412"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed the Icon on line 71 in my profile

components/Icon.js
This reverts commit 1f2729b5dc855c325cc0ea0801bac957055f7de0.
=> Revert "feat: dynamically import icons (#4387)"

.github/ISSUE_TEMPLATE/feature_request.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: triage label to features

components/Icon.js, tests/setup/global-setup.js
Re-enable changes from #4387 with working error handling.
Also added a test for a bad icon
=> Re-implement dynamic icons import w/ error handling

data/oyenolaphilipinc.json, data/philipcodes.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4433"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:philipcodes

data/imran1509.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding one more testimonial to profile

data/CBID2.json
Feedback is appreciated 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4452"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added link to Twitter page

data/ParasGoswami06.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> A pull request for my linkfree contribution

components/Footer.js, components/navbar/Navbar.js
Import IconContext directly in NavBar.
Use getIcon to import icons in NavBar & Footer.
=> Reduce _app bundle size to improve load time

package-lock.json
=> fix: package log

pages/docs/index.js, pages/docs/quickstart.mdx
=> docs: number of ways to run project

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/docs.yml
=> fix: issue template label

data/YashPimple.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated bio

.github/workflows/deploy.yml, .github/workflows/prettier.yml, .github/workflows/release.yml
=> fix: do not run GH Action on fork #4537

data/anthonrodgrs01.json
- [yes ] My code follows the code style of this project.
- [ yes] This PR does not contain plagiarized content.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: anthonrodgrs01

data/mohitparmar1.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mohitparmar1

RishiSrivastava.json, data/sri-rishi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4494"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sri-rishi

data/lakshmishreea122003.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:lakshmishreea122003

data/shivam-sharma7.json
update my bio and links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update my bio and links

data/bharat5604.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4534"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bharat5604 patch 1

data/vishal206.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vishal206

pages/search.js
fixes #3259 
The first character search always seems to be a bit laggy it makes the page unresponsive for some time maybe thats because it is filtering out the whole 1250+ profiles with just 1 character not sure?
any suggestions? @Parsifal-M @eddiejaoude 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4476"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: debounce results

components/navbar/Navbar.js
#4499 
Fix this issue by renaming "Community Events" to "Events"
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix: renamed 'Community Events' to 'Events'

data/tplive.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4536"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: tplive

data/deepanshu-rawat6.json
* Updated my **bio** and **links**
* Added **tags** and **social shortcuts** in my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: deepanshu-rawat6

pages/docs/how-to-guides/editing.mdx, pages/docs/quickstart.mdx
Update documentation to mention how to spot approving reviews from a maintainer
=> Update quickstart and editing doc to highlight maintainer reviews

data/mariamadeyemi.json
1. New JSON file was created.
2. Profile data and links included.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mariamadeyemi

data/Anmol-Baranwal.json
- `All new and existing tests passed` : I don't really know how this can be done since it is my first PR to this repo
- I have validated the JSON using the tool mentioned in the docs.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Anmol-Baranwal

data/foss2cyber.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: foss2cyber

Taheer10.json, data/Taheer10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Taheer10

data/abhiraj-ku.json
Created LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4511"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:abhiraj-ku

data/ABHIGYAN-MOHANTA.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ABHIGYAN-MOHANTA.json file added

data/Vikkybliz.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4519"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Vikkybliz

pages/search.js
Closes #3380 
Currently users are sorted alphabetically based on the user's Github username.
An randomizer is added to help randomize the users that show up and help 
promote more profiles to be discovered. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4521"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> search: Add randomize users on tag search.

pages/search.js
=> chore: search code formatting

components/MDXComponentStyle.js, components/layouts/DocsLayout.js, next.config.mjs, styles/onedark.css
closes #4120 
Last time changes that I proposed was confusing. But as per the suggestion i received from the @eddiejaoude i.e to use mdx custom elements here [link](https://nextjs.org/docs/advanced-features/using-mdx#custom-elements) So I have done it now content that is coming from the mdx files can be styled in our own.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4448"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Nav bar fix

components/MDXComponentStyle.js, components/layouts/DocsLayout.js, components/mdx/ComponentStyle.js, next.config.mjs, styles/onedark.css
Refactored this PR https://github.com/EddieHubCommunity/LinkFree/pull/4448
=> Fix docs small screen

components/user/UserCard.js
Added shadows hover effects (mainly scaling up the cards), removed the hover border color, and made the profile username font a bit light and color black
added shadows,
added hover effect,
changed profile username text on the card to light and black
It's a hover effect so moving the cursor pointer on it will show you the changes, although you may see the change I made in the profile username text
Made these changes to make the UI better than before.
The suggestion is to remove the orange box containing profile view numbers which are on the top right of the profile picture. Instead what you can do is:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3893"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added hover effects to the card

components/user/UserCard.js
Tweaking PR https://github.com/EddieHubCommunity/LinkFree/pull/3893
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4568"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: hover effects to user card (#3893)

data/viveksinra.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4299"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: viveksinra

data/ksen21.json
want to create linkfree link
The pull request has been reviewed and merged by [Ksen21].
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ksen21

data/atanda0x.json, data/viveksinra.json
=> Sara fix profiles

.storybook/main.js, package-lock.json, package.json
Closes #4500 
Fixes the error on the Deployed link of Storybook `Cannot read properties of undefined (reading 'data')` & also this error which is shown in the local build of Storybook `[next-auth]: 'useSession' must be wrapped in a <SessionProvider/>`
Added `next-auth-mock` plugin to the project and updated `.storybook/main.js` to include `@tomfreudenberg/next-auth-mock/storybook` as a storybook addon.
```javascript
addons: [
"@storybook/addon-essentials",
"@storybook/addon-a11y",
"@tomfreudenberg/next-auth-mock/storybook",
]
```
`user not authenticated`
`user authenticated`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4566"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Storybook bugfix

.github/workflows/storybook.yml
Run the storybook workflow when changes made to: 
1.  .storybook directory (config files)
2.  package.json
Also allow for manual dispatch if needed.
=> Run storybook workflow on config changes

data/Danny4life.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4477"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Danny4life

data/jennifer-pecky.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : jennifer-pecky

data/davydocsurg.json
=> data: davydocsurg

data/ChinatuL.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4597"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ChinatuL

data/Shukla007.json, data/shukla007.json
Update 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4604"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Shukla007

data/iamravi1.json
- [ :heavy_check_mark: ] My code follows the code style of this project.
- [ :heavy_check_mark: ] My change requires changes to the documentation.
- [:heavy_check_mark:  ] I have updated the documentation accordingly.
- [:heavy_check_mark: ] All new and existing tests passed.
- [:heavy_check_mark: ] This PR does not contain plagiarized content.
- [:heavy_check_mark: ] The title of my pull request is a short description of the requested changes.
=> data: iamravi1

config/user.json, data/singhmohit14072002.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added a more links and user.json

data/kaiwalyakoparkar.json
You'll are doing a great job. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: kaiwalyakoparkar

data/singh-vaibhav08.json
File name: VaibhavSinghDev -> singh-vaibhav08
Twitter: VaibhavSinghDev -> singh_vaibhav08
LinkedIn: vaibhavsinghdev -> singh-vaibhav08
Github: VaibhavSinghDev -> singh-vaibhav08
Added Dev.to link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated and added social links and updated file name

data/kdpuvvadi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update_user kdpuvvadi

data/Abhinav-6.json, data/Abhinav6.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4601"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Abhinav-6

data/VISHAL3545.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:VishalKumar

data/tr-sangale.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:tr-sangale

data/modirocks.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: modirocks

data/rukundob451.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update linkfree profile

data/punitbathija.json
Added My own LinkFree jsonObject file to the data folder
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4631"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:PunitBathija

pages/map.js
Update display check filter to remove remote location correctly
=> Fix remote location check

pages/map.js
Check for remote must be on provided
=> Check provided location for remote

components/navbar/Navbar.js
fixes  #4514 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix Border of Login Button

pages/docs/contributing/commits.mdx, pages/docs/index.js
=> Docs conventional commits

data/kshitij9896.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4662"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile Created

data/SrimanNarayana7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SrimanNarayana7

data/adiati98.json
Add `adiati98` profile to LinkFree.
N/A
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4664"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: adiati98

Ashasindhu.json, data/Ashasindhu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Ashasindhu patch 4

data/ibilalkayy/events/2022-10-24-kubecon.json
Added the testimonial and events
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4702"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding the testimonials and events

data/muzamil-mia.json
i would like to update my link-free-profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: muzamil-mia

data/zaidahmad25.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4710"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: zaidahmad25

data/ta-sakin.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4705"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ta-sakin

data/Deepakktripathy.json
You all are doing amazing! Would love to have my linkfree profile created!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4701"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Deepakktripathy

data/gauravrattan.json
You'll are doing a great job. I would like my LinkFree Profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4699"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Gauravrattan linkfree profile

data/ZendeAditya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ZendeAditya

data/lakshmishreea122003.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4697"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: lakshmishreea122003

data/Yushi5058.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4692"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Yushi5058

data/NikhilRaikwar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4690"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:NikhilRaikwar

data/Sayyed-Salman.json
Adds my shit.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Sayyed-Salman

data/andreyscott.jsoc
And made sure it was error-free
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created and added andreyscott.json

pages/account/no-profile.js, pages/account/statistics.js
Function and file names were not matching
=> Fix function name

components/statistics/BasicCards.js, pages/account/statistics.js
Ignore numbers, my test data is a bit messy
=> feat: account cards

data/FrancescoXX.json
updated newsletter link and testimonials
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update newsletter and testimonials

data/sheriffOladimeji.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4745"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sheriffOladimeji

data/Agrim-Sharma174.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4747"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Agrim-Sharma174

data/Yasshu55.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Yasshu55

data/ibilalkayy.json, data/ibilalkayy/events/2022-10-24-kubecon.json
Added the testimonial to my LinkFree account
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Testimonials

data/SandipPalit/events/2023-02-22-aws-innovate.json
Updated 2023-02-22-aws-innovate.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated 2023-02-22-aws-innovate.json

data/lokeshvasnik.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data lokeshvasnik

data/DeepanshuRohilla15.json
You'll are doing great job. I would like my LinkFree profile updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4754"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: DeepanshuRohilla15

data/shrix1.json
Create Linkfree for the First time
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4758"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shrix1

data/mehmetsaidozsoy.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4649"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mehmetsaidozsoy

data/mkbhru.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mkbhru

data/ayush24k.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ayush24k

data/vishalrathore8oct.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4349"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vishalrathore8oct

data/Odohofre.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Odohofre

data/nidhi333-9.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4713"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: nidhi333-9

data/RashidatJay.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3726"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RashidatJay

data/kingDOM2227.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data kingDOM2227

components/IconCard.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: display copy alert over navbar

dybran.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4270"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> dybran-patch-1

config/mongo.js, models/Account.js, models/Session.js, models/User.js, models/VerificationToken.js, package-lock.json, pages/api/auth/[...nextauth].js, pages/api/auth/db-adapter.js
=> feat: save login user to db #4767

Mutai-Gilbert.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3603"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Mutai-Gilbert

data/ibilalkayy.json
Updated the bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated the bio of my account

data/Sunil8wale.json
You are doing a great job . I would like my LinkFree profile to be updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4770"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sunil8wale

data/timDeHof.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Tim dehof patch 2

data/yamdevv.json, data/yamduran.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4801"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yamduran

data/ShubhamChikane99.json
You'll are doing a great job. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Shubham chikane99 likefree profile

data/paulaxisabel.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: paulaxisabel

data/PrakharSinha-09.json
Thank you Eddie For All The Things You Are Doing For The Community. Your Contribution Towards Uplifting The Community For The Cause Will Be Seen As The Legacy and last but not least, you are truly the gem of Open Source!
Can't Thankyou More!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4797"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: PrakharSinha-09

data/methlox.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4794"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: methlox

data/zaidahmad25.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4809"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add milestones, social shortcuts & tags to profile

components/Button.js, pages/index.js
No visual changes, just refactored buttons to a component
=> fix: refactored buttons

.dockerignore
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4774"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> enhancement: update docker ignore, which can be ignored

data/kaushalnitb.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4492"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:kaushalnitb

data/sansarmaske.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4820"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sansarmaske

data/NikhilRaikwar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4812"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: NikhilRaikwar

data/BejadiRajeshReddy18.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4822"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:BejadiRajeshReddy18

data/akshitagupta15june.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4831"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: akshitagupta15june

pages/docs/contributing/labels.mdx, pages/docs/index.js
=> docs: story points explained

data/Sajiyah-Salat.json
I am updating my old profile. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4829"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Sajiyah update

data/TRohit20/events/2023-06-13-DevRelCon-London.json
Added DevRel Con London to the list of upcoming Community events and Open CFPs
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4845"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added DevRel Con to events

data/ahmedrowaihi.json
- Ahmed Rowaihi to the Data List
I added a ```ahmedrowaihi.json``` data file : D
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4825"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Ahmed Rowaihi to the Data List

data/sudhanshutech.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4823"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sudhanshutech

data/LuqmaanHakeem.json, data/rghdrizzle.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:rghdrizzle

data/zaidahmad25.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4854"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix LinkedIn url and change twitter icon

data/Sudhi27Krishna.json
I like this initiative which helps people begin with open source. I would like my profile to be updated on the linkfree site.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sudhi27Krishna

data/kundangupta1993.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4836"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:add profile kundangupta1993

data/Omdeshkar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4706"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Omdeshkar

pages/docs/environments/environment-variables.mdx, pages/docs/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4878"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: environment variables

data/ashutoshkandpal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4867"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ashutoshkandpal

data/gawadeatul.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gawadeatul

data/md-abid-hussain.json
Added my codepen profile to my linkfree link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4872"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added codepen profile

data/kammy1996.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4877"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Kammy1996 patch 1

data/Muyixone.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4876"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Muyixone

pages/map.js
=> fix: check geo location

data/Langi10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4875"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Langi10

data/VarchasvH.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4897"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: VarchasvH

data/Ajay84sia.json
create my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> create my profile

sourav091.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4803"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sourav091

data/HarshitSharma.json
You all are doing a great job. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:HarshitSharma

data/Ajay84sia.json
File Update
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> file update

data/Azeezkadiri.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4901"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Azeezkadiri

components/Footer.js
Closes #4918 
Removed the 'Donate to LinkFree' link from the footer.
Before | After
:-----:|:-----:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Remove 'Donate to LinkFree' link from footer

pages/docs/environments/local-development-docker-compose.mdx
fixes the typo in local-development-docker-compose.mdx
fixes #4881 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4907"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Chore: removing typo

components/navbar/Navbar.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4771"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: format blank spaces in code

data/RahulRawatji.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4919"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RahulRawatji

data/Ajay84sia.json
Update in links and data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4910"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update in links and data

data/ArvindParekh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4940"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ArvindParekh.json

data/merwinmathew33.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4939"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: merwinmathew33

data/priyankarpal.json
Added another milestone
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4936"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update: added another milestones

data/mahfuztbt.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4929"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mahfuztbt

data/LuqmaanHakeem.json, data/rghdrizzle.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4859"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated profile 

data/ronthetech.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4922"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: add tags, update bio, and add portfolio link

data/thebarshablog/events/2023-02-21-Decoding-CFPs-Twitter-Space.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added 2023-02-21 Twitter Space

data/pravendra93.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4948"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: update github username
