package-lock.json
src/App.js
src/Components/Footer.js

Did not put any style yet so you can adapt it to the page layout.

Add footer (#22)

---

.gitpod.yml
README.md

closes #41 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/Members/pull/44"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: gitpodify project

---

public/data/iasonathanasiosgiatsios.json

Added my data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/57"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add data member iason athanasios giatsios

---

README.md
public/data/FayasNoushad.json

chore: FayasNoushad data

---

public/data/mohammad.json

This is github and twitter info
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/71"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mohammad4kh data

---

src/Components/Links.js

Add navigation functionality to buttons when clicked on it
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/72"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add navigation functionality

---

public/data/Skyhero-admin.json

Added my information
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/78"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my info

---

public/data/vinzvinci.json

I have added my data :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/82"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added vinzvinci data

---

public/data/_list.json

add my info to home page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/87"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add my info to home page

---

public/data/_list.json
public/data/verma-kunal.json

Added my data in the project !!

Added verma-kunal data 

---

public/data/_list.json
public/data/krishdevdb.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/89"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add krishdevdb

---

README.md

fix: Spelling mistake corrected in README.md

---

public/data/_list.json

I have added my data to the homepage
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/94"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: added vinzvinci data to homepage

---

public/index.html

Resolve #97 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/98"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: website name

---

Contributing.md

Adding Contributing.md

---

src/Components/Links.js

Adding the colour hex-code for Twitter!!
related to: #37 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add: Twitter-colour hexcode

---

public/data/_list.json
public/data/roshanmhatre.json
src/Components/Links.js

Add feature Youtube and Github Color and Add My Data
Changed Youtube color from red to #ff0000 and Github from black to #171515
Add my linkfree data
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Changed Youtube and Github color Code and add my data

---

public/data/_list.json
public/data/vikasganiga05.json

Fixes #
Added myself to the project :slightly_smiling_face: .
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: data for vikasganiga05

---

public/data/Nikhil-1503.json

Added my info to the json file. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Nikhil-1503

---

public/data/Nikhil-1503.json
public/data/_list.json

Added my data into _list.json

---

public/data/kaiwalyakoparkar.json

Fixes #171 
Added my name to LinkFree
-
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Kaiwalya Koparkar added (#171)

---

README.md

Fixes #176
- Updated the UI in README file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Update the UI design in the README file #176

---

public/data/itsarghyadas.json

Fixes #
-Profile data Added
-
-
--none--
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Profile Data

---

public/data/ShaileshKumar007.json

- Added my profile @shaileshkumar007
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile

---

public/data/ragibajmal3.json

Fixes #
-adding my profile
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding my profile

---

public/data/jayvirrathi.json

Added jayvirrathi profile

---

public/data/subhodynamics.json

added my profile links to the public file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/190"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile links

---

public/data/omkar342.json

Fixes #
-
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created omkar342.json

---

Contributing.md

One number is mismatched in steps.
Fixes #216
- Mismatched in numbering.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Mismatch numbering in steps.

---

public/data/Akshu-on-github.json

Created a file Akshu-on-github.json to add my profile to the link tree - and placed it in the right folder this time (unlike #228)

Add profile: Akshu-on-github.json

---

src/Components/Footer.js
src/Components/Home.js
src/Components/Links.js
src/Components/Profile.js
src/Components/Socials.js

Fixes #25
- alt text added to all images
- jsx tags changed to be semantically correct eg footer instead of div
- aria labels and roles added to links
- avatars on home page wrapped in an anchor tag to make them tabbable for keyboard users (functionality missing on Avatar inbuilt onclick method)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Accessibility enhancements

---

public/data/infoxicator.json

Add new user 
Look who's joined the party 😉
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/253"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(users): add infoxicator

---

public/data/SimranGupta.json

Add Simran Gupta
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/255"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add SimranGupta

---

CODE_OF_CONDUCT.md

- Update the Code of Conduct to the latest version
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[feat/fix]: Update the Code of Conduct to the latest version

---

README.md

- Use HTTPS instead of HTTP in the readme.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/269"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Use HTTPS instead of HTTP

---

public/data/sumitmukharjeeeeee.json

Fixes #
-
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/270"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added name

---

src/Components/Home.js

change 404 picture to met the requirements from the other json files for profiles.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

refactor: change 404 picture

---

public/data/amittri1025.json

Profile amitri1025 in json format
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Profile amittri1025 added

---

.github/workflows/community.yml

Removed Firebase credentials since they're no longer being used.
Fixes #204
- Remove firebase access token.
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/278"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Removed Firebase credentials (#204)

---

public/data/harshraj8843.json

Fixes #
- added `public/data/harshraj8843.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/288"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add harshraj8843

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/pull_request.md

Things added/changed:
- Improve the pull request/issue templates.

[feat/fix]: Improve the templates

---

public/data/Sejal-16.json

Add  me 😀
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/301"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add Sejal-16

---

public/data/Anirudh.json

Fixes #173 
-
-
-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created Anirudh.json

---

README.md

Removed full stops of commands
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Full stops not needed

---

Contributing.md

Fixes #302 
Fixed my previous pull request #312 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Change fork icon's color in readme

---

public/data/Deephunt3r.json

Added my profile 😃 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add deephunt3r to the list

---

public/data/Tishasoumya-02.json

Opening a PR to contribute to the repo.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Tisha Soumya to the list

---

public/data/khan-droid.json

-Created a file khan-droid.json to add my profile to the link tree

created khan-droid.json

---

public/data/Moeen-Ul-Islam.json

removed the extra space at the end of closing brace
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Moeen Ul Islam to the list

---

README.md

Things added/changed:
- Use HTTPS in the `README.md` file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/348"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Use HTTPS in the `README.md` file

---

public/data/panquesito7.json

Things added/changed:
- Add Panquesito7 (myself) to the list.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add Panquesito7 to the list

---

README.md

Adding a brief note regarding which contributions will be marked for Hacktoberfest eligibility.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/356"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: hacktoberfest note

---

public/data/roshanmhatre.json

fixes #374 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/375"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update my data 

---

.github/ISSUE_TEMPLATE/bug.yml

fixes #381 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/382"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: typo in issue template

---

public/data/praveenscience.json

Added just the three links.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/329"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Praveen's details.

---

public/data/kulkarnigaurav38.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add kulkarnigaurav38 profile

---

src/Components/Links.css

@eddiejaoude 
This PR fixes the following issues:
closes #352

Feat/fix : Fixed the Background color of LinkedIn and Instagram link  (Resolved: #352)

---

public/data/aamita96.json

New aamita96.json file added to this repo. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/355"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Amit Khatri profile

---

public/data/shivamshrivastava.json

Added a json file in linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding Json file for LinkFree

---

public/data/Gajendrakm.json

Hey
I am adding my profile gajendrakm.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/407"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding my profile as gajendrakm.json

---

public/data/evavic44.json

Profile added 
Add Hasnode icon
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/420"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Create my profile.json

---

Contributing.md

This PR includes the following: 	
* Small formatting and wording fixes to the contribution guide.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/428"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Adjust wording and formatting of contribution guide

---

src/Components/Home.css
src/Components/Home.js

resolve #353 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/383"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add Skeleton (#353)

---

public/data/MekongDelta-mind.json

First commit to add the json file containing the required details about the contributor
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/438"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

First commit for Linktree

---

public/data/Kunal0007.json

Added a LinkedIn link in Kunal0007.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(data): add new link Kunal0007

---

src/index.css

resolve #119 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/603"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add margin

---

src/Components/Navbar.js

Fixes #648 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/653"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(accessibility): missing aria-label

---

src/Components/Home/Home.js
src/Components/Home/Users.js

This PR will close #640 .
Also removed the additional filter which was taking place on already filtered data.
Screenshot:
N/A 
This is an internal change. No change in UI.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/647"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[Other]Normalize name for sorting #640

---

public/data/stemount.json

chore: #386: Fix @stemount YouTube URL

---

src/Components/Links.js

closes #649 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/654"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

removed link wrapping the button

---

README.md

Things added/changed:
- Add contributors graph in the readme.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/687"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add contributors graph in the readme

---

.gitpod.dockerfile
.gitpod.yml

Fixes #671
1. Gitpod cold start (e.g. new workspace) should be super speedy
2. Ensure everything still plays nicely.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update .gitpod.yml removing the link to the dockerfile

---

src/App.js
src/Components/Links.css
src/Components/Links.js
src/Components/Profile.css

Reduced Margin for max-screen size 768px
Closes #664 
After change view in mobile - 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Margin and Padding Decrease in Mobile View

---

src/Components/Home/Home.js
src/Components/UserProfile/ErrorPage.js
src/Components/UserProfile/ProfilePage.js
src/Components/UserProfile/User.js

Removed the main element in `User.js` as this was causing a duplicate main element
Closes #651 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: remove main tag in `User.js` causing duplicate

---

.github/PULL_REQUEST_TEMPLATE.md

- Fix spelling errors in the PR template.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/692"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: spelling errors in the PR template

---

public/data/pranay.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/695"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Add pranay's data

---

package.json

- Provide a description and more information
about the project in the `package.json` file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: provide more information in the `package.json` file

---

public/data/khushisaxena.json

Hey! I have added my Linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add khushi-linkfree

---

public/data/khushisaxena.json

- Update `link` to `globe`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/699"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update `link` to `globe`

---

README.md

Updated the readme list of available icons adding the globe icon
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/702"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: add globe icon to the list of valid icons

---

src/Components/Navbar.js

Closes #623
Sorry for a pull request via a new branch, I was facing some issues.
Just added the Version in the navbar.
Thank you.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/705"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add version on Navbar

---

package-lock.json
public/data/avneesh0612.json

I have added my profile :D
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/710"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added avneesh0612

---

public/data/EddieHubCommunity.json

RR: @eddiejaoude 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/703"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(add-profile): EddieHubCommunity

---

public/data/FayasNoushad.json

@FayasNoushad
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: update avatar of FayasNoushad

---

public/data/web3community.json

Cc: @vinzvinci 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/704"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(add-profile): web3community

---

public/data/krishguptadev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/712"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(update-profile): new pic

---

public/data/App-Choreography.json

I added the App-Choreography organisation, as I am the founder of it. Thank you
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Add App-Choreography

---

public/data/avneesh0612.json

docs: add missing comma

---

.github/ISSUE_TEMPLATE/bug.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/725"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs(typo): bugnb `->` bug

---

CODE_OF_CONDUCT.md

fixes #723 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/724"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs(coc): update coc email

---

public/data/krishguptadev.json

fixes #732 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/733"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: appropriately-sized img

---

public/data/Anubhavdevv.json

fixes #730 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: username change

---

public/data/avneesh0612.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/727"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(update-profile): add blog to avneesh0612

---

public/data/Mohasin-Haque.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/741"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Mohasin to the list

---

public/data/Minecodes.json

I want to add me as an example to the repo, could you please merge it? Because I want to make my first commit to a repository.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Minecodes.json

---

public/data/Mohasin-Haque.json

- Add missing endline in `public/data/Mohasin-Haque.json`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/746"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add missing endline in `public/data/Mohasin-Haque.json`

---

src/Components/Links.js

Resolve #752 
[x] fixed alignment issue on the profile page for the check my blog posts button
Before:
After:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

style: fixed the alignment issue on the check blog posts button

---

public/data/Minecodes.json
public/data/avneesh0612.json
public/data/kingwisdom.json

Fixed all typos.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/750"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: improve Avneesh's profile

---

public/data/qwe123coder.json

added my dev.to to my profile
added my dev.to to my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/758"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: added blog links in qwe123coder's profile

---

public/data/ChoudharyTara.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add  ChoudharyTara.json

---

README.md

Update the sample JSON code in the README, according to the latest [`eddiejaoude.json`](https://github.com/EddieHubCommunity/LinkFree/blob/main/public/data/eddiejaoude.json) file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update the sample JSON code

---

Contributing.md
README.md

I recently opened up a similar pr to our [hacktoberfest-practice repo](https://github.com/EddieHubCommunity/hacktoberfest-practice/pull/777), This PR has the same purpose, to fix Grammarly issues and alexjs issues.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/759"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs(grammar): fix using grammarly

---

public/data/rowjay007.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/747"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Add Rowland Adimoha profile

---

public/data/VaibhavUpreti.json

My linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/776"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Vaibhav Upreti

---

public/data/saurabh
public/data/saurabhmehta1601.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/771"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Saurabh Mehta

---

README.md

closes #773 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: update screenshot

---

README.md
public/data/VaibhavUpreti.json
public/data/taravis.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/784"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[BUG] Missing type parameter #779

---

README.md

Closes #769
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/774"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: make template-y

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/789"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Make C to c in the word Connects

---

public/data/carrotfarmer.json

- added my profile
- `CREATE public/data/carrotfarmer.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/793"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Dhruva Srinivas

---

public/data/thealgorithms.json

- Add The Algorithms as a community profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/797"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add The Algorithms

---

README.md

Closes #787
Replace tall screenshot with short gif
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/796"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: replace screenshot with GIF

---

README.md

Fixes #777 
Added new supported icons to Readme file
--
--
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/795"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: add new icons

---

public/data/AmrMonier.json

added new json file **AmrMonier.json** to the ```/public/data``` 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Amr Monier

---

README.md

Fixes  #798 
- Not neccessary to keep the Hacktoberfest notice on the README during this time of the year
- Shifted the notice to a dropdown
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/803"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: update Hacktoberfest section to a dropdown

---

src/Components/Profile.js

Closes #812
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/817"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: name alignment issue on small screens

---

public/data/Jatinkumar30.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Jatin Kumar

---

README.md

Added Data about types and their suitable values field to README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/821"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: add information about `type` parameter in `README.md`

---

.github/workflows/prettier.yml
public/data/Tejas-Teju.json
public/data/saurabhmehta1601.json
public/data/theriyazo.json

- Earlier the GitHub Action was just used to fix errors in the repository the action was run in.
- Now it shows failing build if you didn't the fix errors in the PR itself
- It will also be using the github annotation feature to tell the PR author, how to fix the changes 🙂 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add fail CI

---

public/data/irusha.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/827"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: avatar

---

src/Components/Icons/GetIcons.js

Closes #227 
Add tiktok icon
Does the README need updating with the icon too?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add TikKok icon

---

generate.js
public/data/nathgoutam93.json
src/Components/Home/Home.css
src/Components/Home/Placeholders.js
src/Components/Home/Users.js
src/Components/Profile.js

Closes #191 
https://user-images.githubusercontent.com/91387097/146555794-46c47df8-5c5f-4e23-8c00-57d75a7ef200.mp4
on small screen sizes it shows by default
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/824"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Number of links appear on homepage when hover

---

src/Components/Home/Searchbar.js
src/Components/Icons/GetIcons.js
src/Components/UserProfile/User.js

closes #840 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix]:added arrow and search icon

---

README.md

- Improve `README.md`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/832"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: improve `README.md`

---

src/Components/Footer.js
src/Components/Icons/GetIcons.js
src/Components/Navbar.js
src/Components/UserProfile/User.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/843"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: code optimization

---

public/data/eddieandsaraexplore.json

New Pic, I like this one the most, can suggest something else in the comments
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/828"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: avatar has wrong aspect-ratio

---

src/config/links.json

Closes #855 
Added tiktok color in the JSON file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/856"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added tiktok color

---

public/data/Aniruddha-Inge.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/864"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Aniruddha Inge

---

README.md

added a missing ```the```.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/869"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: grammar fix in the `README.md` file

---

public/data/kumarsonsoff3.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Profile type

---

public/data/sarahlean.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/876"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Sarah Lean

---

public/data/lakshay-nasa.json

Created profile - Lakshay Nasa
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/882"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add lakshay-nasa

---

public/data/varghesejose2020.json

I have added my social media data to the public folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/885"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Varghese Jose

---

public/data/LokeshDigari.json

my first contribution by adding a file LokeshDigari.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/887"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Lokesh Digari

---

public/data/srkds.json

- add srkds.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/877"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add srkds/Nirav

---

public/data/kishanrajput23.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/894"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add kishanrajput23

---

public/data/Chaitanya7666.json

I have added my social media data to the public folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/881"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Chaitanya

---

public/data/vaishnav-sh.json

Added new vaishnav-sh.json file in `public/data`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/893"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Vaishnav Shyam

---

public/data/sameem420.json

- ### add sameem420
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/879"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Muhammad Sameem

---

package-lock.json
public/data/harshsinghatz.json

Add harshsinghatz.json file with social information in public/data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/889"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Harsh Singh

---

package-lock.json
public/data/wasiqb.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/892"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Wasiq Amjad Bhamla

---

package-lock.json
public/data/MeetMulik.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Meet Mulik

---

public/data/john.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/897"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add john babu's profile

---

public/data/caotanduc.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/907"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add Cao Tan Duc

---

public/data/ankanbag101.json

- Format files/fix CI.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/913"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

style: format files

---

public/data/anishde12020.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/909"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add anish de

---

public/data/ashwinair.json

This is a hot fix, thanks.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/919"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: github username changed

---

public/data/digambar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/918"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Digambar Tupurwadi

---

public/data/Rahulbaran.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/915"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Rahulbaran

---

package-lock.json
public/data/CyberDevv.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/914"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add cyberdevv

---

public/data/Subhojit-Dey1234.json

I have added  Subhojit-Dey1234.json in the public/data folder. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Subhojit Dey

---

src/Components/UserProfile/ErrorPage.js

Closes #923 
Add `align-items-center` to parent div
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/924"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: correct item alignment on "profile not found" page

---

package.json
src/Components/Footer.js
src/Components/ScrollToTopBtn.css
src/Components/ScrollToTopBtn.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Scroll-to-top button

---

README.md

Closes #904 
Add a new line in the `Installation steps` section of the `README.md` file for using the command `npm run generate` to see the newly added profile in the main menu locally.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/920"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: improve documentation

---

public/data/abhishek.json

Adding profile for Abhishek Gite
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/929"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding profile for Abhishek Gite

---

.github/workflows/prettier.yml

closes #932.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ci: update node version

---

README.md

Mentioned it clearly that someone just have to replace its `<yourusername>`  with its **gh username** in the URL to include `avatar`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/930"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: improve  `avatar` section of README.md

---

public/data/lawanu.json

This my profile details. I would love to contribute more to this project and learn more. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/936"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Profile Details

---

public/data/eoinmurphy.json

- Adds `eoinmurphy.json`
Originally included in #944, but split into separate PR. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding personal profile

---

public/data/nhemnt.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/947"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add user: nhemnt

---

public/data/subash.json

added `subash.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/949"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add user : subash

---

public/data/HAT52.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/939"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding my profile on linkfree

---

Contributing.md

Navigate to the project directory before adding upstream

[DOCS] Correction in Contributing.md

---

public/data/nitinkumar30.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/957"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated my profile json

---

CHANGELOG.md
generate.js
package-lock.json
package.json
src/App.js
src/Components/Home/Users.js
src/Components/Home/filterProfileType.js

Closes #822
https://user-images.githubusercontent.com/91387097/148654527-9f41549c-8628-4a8d-b01c-d5cf4e65a729.mp4
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/937"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Filter by profile type

---

public/data/ronenhammnd.json

Added my profile to the LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/958"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Profile to LinkFree

---

public/data/vikasganiga05.json

Updates are done to `public/data/vikasganiga05.json`
- Added LinkedIn to links array.
- Added milestones property.
- New entry to milestones array.
Any suggestions are appreciated :slightly_smiling_face: :pray:  .
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/962"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Chore update vikasganiga05

---

public/data/mansi-binjola.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/979"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add mansi-binjola.json in public/data/ folder

---

package-lock.json
public/data/imlakshay08.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/974"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Lakshay Tyagi

---

public/data/arpanaditya.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/981"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add profile arpanaditya

---

public/data/AntonyKimani.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Profile to Public/data

---

README.md
src/Components/Icons/GetIcons.js
src/config/links.json

Fixes #982 
Add medium as new social icon
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/984"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Add medium as new social icon #982

---

public/data/HAT52.json
public/data/ronenhammnd.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/987"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added portfolio website to profile

---

public/data/Lavakush Biyani.json

Added my file to Linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/986"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add lavakush

---

public/data/shivanshyadav.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/995"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my blogs 😁

---

public/data/amehi0index.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/997"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile for amehi0index

---

public/data/krishguptadev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1000"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update krishguptadev

---

public/data/CeruleanCodersComm.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/953"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add cerulean coders

---

public/data/SarveshLimaye.json

Added my profile json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1004"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add Sarvesh Limaye

---

src/Components/Profile.css
src/Components/ShareIcon.js
src/Components/ShareProfile.js

closes #951
Added Hovering effect to the social media icons
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/952"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added hovering effect to social-icons

---

package-lock.json
public/data/Sagar0-0.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Sagar0-0

---

public/data/MadhaviMandalia.json

- Add profile Madhavi Mandalia
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1020"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Madhavi Mandalia

---

public/data/krshdev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1022"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update krshdev

---

public/data/abhilipsasahoo03.json

• Added my profile. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1033"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add abhilipsasahoo03

---

public/data/Susmita-Dey.json

I have un-forked this repo due to merge conflict issues and forked again and added this file. Kindly merge it to main.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1035"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Susmita-Dey.json

---

public/data/Sangjin.json

- Added My Profile
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://skmn3-linkfree-hrsj900lhm3.ws-us29.gitpod.io)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1036"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Sangjin.json

---

public/data/hailer24.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1034"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added hailer24.json

---

public/data/PhilipBDev.json

Thank you! 😄
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1039"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add PhilipBDev.json to LinkFree directory

---

Contributing.md

It's important that contributors run tests
Possibly before creating a pull request
Updating contribution documentation.
It's not obvious that you need to run the application,
before running the test.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1027"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

(docs) Add info about running automated tests

---

public/data/vasantisuthar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add vasanti suthar

---

public/data/Chaitanya_Sawant.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1046"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Chaitanya_Sawant.json file added

---

public/data/aleemaheer.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1052"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added aleemaheer

---

public/data/saifrahman.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1053"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add saifrahman

---

public/data/jeremythomas.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1063"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my bio into linktree

---

public/data/Mustafiz04.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1064"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Mustafiz04

---

public/data/KendallDoesCoding.json

- Fixes #1060 
- Update my bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1059"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add current project (working on)

---

README.md

- Extra lines in README.md, after gitlab icon to License section
- Remove extra lines
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1068"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

remove extra lines

---

public/data/Pritam1812.json

Added My Profile Data in JSON File.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1086"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding User

---

public/data/vivek.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1080"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add : vivek-kumar-singh

---

public/data/KendallDoesCoding.json

- Uses link icon instead of gitlab icon
- Update icon from link to new gitlab icon
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update icon for gitlab on KendallDoesCoding.json

---

package-lock.json
public/data/Ugoo-Eze.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added new Json data

---

README.md

- In commit [89bf6bb](https://github.com/EddieHubCommunity/LinkFree/commit/89bf6bb5ebf93c982202614417cf3a77b0126345), I updated the name of the contributing guidelines file, forgot to change it in README
- Short form link to call out contributing guidelines
- Update file name
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1082"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update contributing guidelines file in README.MD

---

public/data/DarshanVaishya.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1089"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Added Darshan Vaishya

---

public/data/bisesh.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1090"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Bisesh added information

---

public/data/nazmulhassan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1088"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Nazmul Hassan

---

public/data/digambar.json

@digambar-t7 can you have a look at this? 🙂 
Related #1085 
Added because of username change
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1108"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: issue in pfp

---

public/data/umaresso.json

Added umaresso.json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added umaresso.json file

---

public/data/dmitrii-kilishek.json

Add Dmitrii Kilishek's profile to the project using dmitrii-kilishek.json file.
For me cypress tests were failing even before I touched the code... so most likely I have nothing to do with them. I could run the code and see my profile with no issues nontheless. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Dmitrii Kilishek's profile

---

public/data/aayush89890.json

In the profiles list, everyone's surname is in caps, only for Aayush, it isn't so it looks a little weird, according to me.
Make surname upper-case
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1107"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Make surname capital for aayush89890.json

---

public/data/KendallDoesCoding.json

- Update profile
- Update avatar (may change it back in the future)
- Add icon in milestones section
- Add Youtube
- Color Youtube icon red.
- Remove slash from portfolio link
- Add milestone
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1067"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update KendallDoesCoding profile

---

public/data/massii-nechiche.json

Add Massii Nechiche's profile to the project using massii-nechiche.json file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Massii Nechiche profile

---

public/data/abdussalam_02.json

Closes #1119 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: icon names

---

public/data/viroopaksh-utrayak.json

I'm viroopaksh-utrayak

---

public/data/chimay29hub.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile chinmay29hub

---

public/data/itzwow.json

-> Add a new profile itzwow
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile itzwow

---

public/data/sshiv5768.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1131"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile sshiv5768

---

public/data/aliyanamu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my profile Hana Aliyah Mufidah

---

public/data/Abbhiishek.json

- Added Personal Website Link 
- Happy Saturday 😊
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1134"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

updated the social links with personal website

---

package-lock.json
public/data/amitturare.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1143"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add personal profile - Amit

---

public/data/shafaq-here.json

<p> 
</p>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added shafaq-here.json to public/data

---

public/data/Nnadivictory25.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my linkfree profile links and data

---

public/data/Deeksha1502.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Deeksha

---

public/data/vikasganiga05.json

Updated my profile bio section to match GitHub bio.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update profile bio

---

package-lock.json
public/data/stephanie-kuihg.json

Added my profile page stephanie-kuihg.json in public/data folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add stephanie-kuihg

---

SECURITY.md

- Format SECURITY.md
- Add bullet points/format
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Format security policy a bit

---

CODE_OF_CONDUCT.md

Closes #1158
update CoC email to link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

update CoC email to link

---

public/data/benjaminmichaelis.json

Adding Benjamin Michaelis profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1162"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile benjaminmichaelis.json

---

public/data/dalpatrathore.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Dalpat Rathore

---

public/data/souravsk.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add souravsk

---

public/data/karlGusta.json

- Adding Karlgusta's profile.
Karlgusta's profile addition.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add: Karlgusta's profile

---

public/data/indigo423.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile indigo423

---

.gitpod.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

refactor: removed white spaces

---

public/data/vaibhav.json

Add a file vaibhav.json giving my introduction.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added file vaibhav.json

---

README.md

The url key value is missing in the example given in Readme.md
Therefore, added the URL key
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added URL key and value inside milestones

---

README.md
src/Components/Navbar.css

Closes #866 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

#866-align version and input field on small screen

---

public/data/shivanshyadav.json

- Added LinkedIn profile link.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1187"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added LinkedIn

---

public/data/abh139.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1190"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add abh139.json

---

package-lock.json
public/data/codewithfan.json

- Created codewithfan LinkFree.
Thank you for the opportunity!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created codewithfan LinkFree

---

public/data/saikalyan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add saikalyan15

---

public/data/samchan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Sam Chan

---

public/data/robertusbagaskara.json

adding "robertusbagaskara" profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add robertusbagaskara

---

public/data/mohamed_ah.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add mohamed_ah

---

public/data/Pritam0077.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile in LinkFree/public/data

---

public/data/AlessandroMinoccheri.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my profile to public data

---

public/data/abh139.json

Closes #1219 
Fix the user profile type from **community** to **personal**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1220"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: User profile type

---

public/data/Horlakz.json

nil
This is a pull request for adding my name to the existing data, also code has been tested and all worked with no issues.
will be delighted to be a contributor in this project.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Horlakz

---

public/data/krshdev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: major changes to profile

---

public/data/Jadhielv.json

- Added my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Jadhielv

---

package-lock.json
public/data/akshatmittal61.json

Added linktree for akshatmital61.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1229"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

akshatmittal61

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: consistent profile examples

---

public/data/ezeetester.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

 This is a sample message

---

LICENSE

- Add 2021 - Present on the license.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add: To present on the license

---

public/data/shivanshyadav.json

- blogs link updated 😁
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

update blog link

---

CONTRIBUTING.md

changed the phrasing of the instructions to help make the understanding clearer. lines: 15, 21, 88 & 94
updated a typo line 13
- line 62, the . (dot) and *(asterisk) are not explicitly stated, and are easily lost in the meaning of this sentence. I mistakenly read, (not to run commands 'git add ' ) but then the following command is 'git add public'
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: clearer instructions in CONTRIBUTING.md

---

public/data/donmarvex.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add donmarvex

---

public/data/virajnirbhavane.json

Hi folks, please add my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Viraj's Profile

---

public/data/shivam-sharma7.json

- My Bio Update 
public/data/shivam-sharma7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Bio Update

---

public/data/johan237.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created johan237.json file

---

README.md

A simple gif for a new user to add their profile.
I wanted to add a visual way of seeing how the profile is added for the new users who like visual demos.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1246"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

A simple gif to add profile

---

public/data/vczb.json

chore: Add vczb

---

src/Components/Home/Home.css
src/Components/Home/Searchbar.css
src/Components/Home/Searchbar.js
src/Components/Navbar.css

Closes #1192 
Icons on the navbar to be well-positioned on the right and on the left.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Menubar icons position on mobile

---

CONTRIBUTING.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1278"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: update to make styling more consistent

---

public/data/panam-py.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added json file containing my details

---

public/data/badmus306.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1282"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added info

---

public/data/subhamghimire.json

Updated resume link of mine
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update resume link

---

public/data/heysagnik.json

updated Sagnik's GitHub'susername and profile picture
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Resolves #1232

fix: update devgossips username

---

public/data/davydocsurg.json

add [@davydocsurg](https://github.com/davydocsurg)'s profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1288"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Davydocsurg

---

public/data/prajwalborkar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1292"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile.

---

public/data/sachinparihar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1293"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added profile

---

public/data/ioanat94.json

Added ioanat94's profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added ioanat94's profile

---

public/data/revati-deshmukh.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile under public/data.

---

public/data/sanchitarorra.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

new profile added

---

public/data/l-przybylka.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Lukasz Przybylka profile

---

public/data/darkterminal.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Imam Ali Mustofa Profile

---

public/data/arth2002.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1311"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add-arth-prajapati-profile

---

public/data/Qreamville.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1318"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add Qreamville

---

public/data/shivam-sharma7.json

Update my bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1321"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update my bio

---

public/data/hasnainmakada-99.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1319"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added personal linkfree

---

public/data/ruchiket.json

- Added ruchiket in public/data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add ruchiket

---

public/data/StefanoFrontini.json

Add Stefano Frontini profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1327"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Stefano Frontini profile

---

public/data/nagendradevara.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added nagendra devara profile to link Free

---

public/data/FayasNoushad.json

account deleted
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Remove Facebook

---

public/data/kalijonn.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1332"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add kalijonn profile

---

public/data/eshan-sharma.json

Added eshan-sharma, links to blog pages and socials.
Closes  #1338 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add eshan-sharma.json (resolves #1338)

---

public/data/prasanta10.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1345"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my profile to LinkFree

---

public/data/vedantpople4.json

The previous PR #1333 had problems with package-lock file. This time the file is kept the same from the main EddieHub/Linkfree repo with changes only in 1 file i.e. my profile json file. Hope this solves the previous issues and PR gets merged.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Vedant Pople to LinkFree

---

public/data/Felipeceballos12.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1348"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my links to LinkFree - Felipeceballos12

---

public/data/akhileshthite.json

Added my profile.
NA
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1349"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add akhileshthite

---

public/data/prateek041.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1356"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add prateek041.json

---

public/data/eddejayaklu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added jaya data

---

public/data/Shivam-Katare.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1360"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Shivam-Katare to LinkFree

---

public/data/KartikeyDubeyKD.json

I have reverted the changes and I hope it's right this time @emmalearnscode 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add KartikeyDubeyKD

---

public/data/shoetan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1362"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my name to the profile

---

public/data/Chaudhryna.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1364"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Chaudhryna

---

public/data/srinivaskarnati.json

Signed-off-by: karnatisrinivas <karnatisrinivasulareddy@gmail.com>
- Added my profile to Public data. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1365"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Srinivas Karnati's profile to user data

---

public/data/amelia2802.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1372"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add amelia2802.json

---

public/data/Jai-Solania-29.json

I have added my profile Jai-Solania-29.json 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Jai-Solania-29.json

---

public/data/Kanika637.json

Adding my profile Kanika637.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1379"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Kanika637.json

---

package-lock.json
public/data/bishal7679.json

Added bishal7679.json on public/data directory
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1373"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add bishal7679.json

---

public/data/Sumit.json

Added Sumit.json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1380"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Sumit.json file

---

public/data/shridharkapshikar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1374"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding shridharkapshikar file

---

CONTRIBUTING.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1329"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

improved contributing.md, updated the link which was not working before.

---

public/data/Atharv-777.json

Added Atharv-777.json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Atharv-777

---

public/data/nhcarrigan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1393"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update avatar

---

public/data/PratishShrivastava.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1399"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add my profile pratish shrivastava

---

public/data/joshuaizu.json

Add my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1401"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my profile-joshuaizu

---

public/data/rdegbe.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1402"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my link 

---

public/data/AnshuPathak-88825.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1403"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added username.json

---

public/data/rakeshsangem.json

Add json file to LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1406"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add rakeshsangem.json

---

public/data/enn-dee.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added enn-dee to linkfree

---

cypress/integration/user.feature
public/data/eddiejaoude.json

Updated my profile 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1413"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: update eddiejaoude

---

README.md

Closes #1419 
Added Uptime Badge for LinkFree
This was fun, hope to be able to contribute more!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1422"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Closes #1419 - Add Uptime Badge

---

public/data/mkubdev.json

Add mkubdev.json profile ☀
Hello there 👋
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1427"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

profile: add mkubdev profile

---

public/data/ashmudra.json

thank you for reviewing! 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

creating and adding ashmudra.json

---

public/data/samikshakute.json

Fixes #1410 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1414"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added samikshakute.json file

---

public/data/yogesh.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1433"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added to the file

---

README.md

Closes #955
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1429"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update: Readme (gif)

---

public/data/KapilKumar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Kapil Kumar

---

public/data/aayushd18.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1450"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Aayush Deshmukh Profile

---

public/data/DennisMuiruri.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1461"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add dennis muiruri profile

---

.eslintrc.yml
cypress/integration/common/actions.js
package-lock.json
package.json

Closes #1453 
- Installed [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) package and added suggested options to `eslint` configuration file.
- Added `cypress` folder to `npm run lint` command.
- Ran `npm run lint -- --fix` and saved corrections to `actions.js` file.
- Ran `npm run test:e2e` and all scenarios passed
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1454"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Install eslint-plugin-cypress package

---

public/data/ThiagoTatico.json

Creating a JSON file for the ThiagoTatico Page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1462"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add ThiagoTatico Page

---

public/data/ayushlohmod.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1436"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added ayushlohmod.json

---

public/data/mehakagrawal.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add New Profile

---

.github/workflows/deploy.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: deploy everything

---

public/data/ShreyaPrasad1209.json

Added a new profile by adding my data inside ShreyaPrasad1209.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1469"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: ShreyaPrasad1209.json addition

---

src/Components/Home.js

Closes #1439
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1449"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

(Accessibility): Links need distiguishing

---

public/data/shubhamsigdar1.json
src/config/user.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding profile detail on LinkFree shubhamsigdar1.json

---

public/data/Suman373.json

Created the new json file and added bio info and links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Chore: add profile type

---

public/data/JoBaHP.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1490"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added JoBaHP user

---

public/data/kum9748ar.json

Added profile 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile for kum9748ar

---

public/data/Niravprajapati1.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added Niravprajapati1

---

public/data/leonid066.json

Added my profile to the LinkFree
Thank you for the amazing project!  
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile, ( leonid066 )

---

public/data/yashwanthSRIVAT.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my Profile!!

---

public/data/Maheshpatro.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile Maheshpatro.json

---

public/data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1511"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

podcast link added for Eddie

---

public/data/itsomsarraf_.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

made my profile for Linkfree

---

public/data/Maheshpatro.json

* Add profile Maheshpatro.json
* Update Maheshpatro.json
This PR was merged into an outdated branch, reverting it back to the main! 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add profile Maheshpatro.json (#1510)

---

public/data/scottWil.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: added username scottwil

---

public/data/Bonganibendi.json

I created a new fork for this project.
I fixed the errors from my previous pull request: #1514.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Creating my Profile in Bonganibendi.json

---

src/Components/Search/Searchbar.js

Added autoFocus parameter to the search bar Input. User expects to input after clicking the Search button on the main page.
So it makes the UX more fluent. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1517"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

autoFocus added to the search input

---

CONTRIBUTING.md

Closes #1522 
The opening section of the documentation had a small bug as a result of which some words which were intended to become hyperlinks were actually not hyperlinks
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1523"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Solved a bug in CONTRIBUTING.md

---

public/data/Roshan-Sharma.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1525"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add Roshan-Sharma profile 

---

public/data/Arushay.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1506"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my profile as Arushay

---

public/data/Davidchaudhary.json

Closes #1492 
I have successfully contributed my profile to Linkfree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile successfully

---

public/data/ankushKun.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added myself to link free

---

public/data/ruthiel.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Ruthiel's profile

---

public/data/ghorbani-mohammad.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1529"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add ghorbani-mohammad profile

---

public/data/avie-dev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1533"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add avie-dev.json

---

public/data/Obito9596.json

Added  Profile Obito9596 #1535
- [☑️ ] My code follows the code style of this project.
- [☑️ ] My change requires changes to the documentation.
- [☑️ ] I have updated the documentation accordingly.
- [☑️ ] All new and existing tests passed.
- [☑️ ] This PR does not contain plagiarized content.
- [☑️ ] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Profile Obito9596

---

public/data/imtmh.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1539"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

new profile data addition: imtmh

---

public/data/AyshaHakeem.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1536"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add AyshaHakeem

---

public/data/Harixomxsingh.json

Add Harixomxsingh.json on public/data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1545"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Harixomxsingh.json on public/data

---

package-lock.json
public/data/marcokumu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add marcokumu profile

---

public/data/langnerdavid.json

Added langnerdavid.json file with my personal information inside.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my personal section to the Linkfree page

---

public/data/Njong392.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1562"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile for Njong Emy

---

public/data/jaishbs.json

Add profile

---

public/data/ste001.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add my profile

---

public/data/RayanAbid.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1567"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add RayanAbid.json

---

README.md

- [] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[Add] : Added Version badge and License badge

---

public/data/ibrahimrehman1.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1578"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile to Link Free

---

public/data/zabihhaqqani.json

added my data on linkfree
Please review my pull request. Thank you!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add zabihhaqqani.json

---

public/data/the-lazy-learner.json

Add Sudhansu's user data
Please review and suggest changes. Thank you!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Sudhansu's data

---

public/data/kartikgajjar7.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

update username of github

---

public/data/raiyanmook27.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raiyanmook27.json Added

---

public/data/Anushka-codergirl.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1583"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Update Anushka-codergirl.json

---

public/data/realsollym.json

Closes #1589
Please add RealSollyM profile to LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1590"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add RealSollyM

---

public/data/sadeedpv.json

Add sadeedpv.json

---

public/data/hemantwasthere.json

I have added my profile data in `public/data`  directory in ` hemantwasthere.json` file
Please review my PR and give me feedback for become a good contributor
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added hemantwasthere.json in 'public/data' directory

---

public/data/2802AdityA.json

Added my profile by adding a file 2802AdityA.json in public/data folder.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add 2802AdityA.json

---

package-lock.json
public/data/dunnjacoba.json

Adds dunnjacoba.json
Thank you all for being so inclusive of even beginners like myself! I am so glad to have found this community.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adds dunnjacoba.json

---

public/data/haldaranup.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

My linkfree profile, added json file using my username

---

public/data/AnanjayGurjar.json

Please, Add my profile to the main project. Open for suggestions on how to make it better.
P.S. It's my first contribution to any open source project.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add AnanjayGurjar.json

---

public/data/SaptarshiSarkar12.json

Added milestone in my json file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated my json profile file

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1632"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: migrating to nextjs notice

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: improved formatting

---

public/data/psypher1.json

I added my profile json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1641"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my profile info to the data folder

---

public/data/kumar-kalyan.json

Upadated username
added github and gitlab
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1635"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

udated changes

---

public/data/Nonso.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1637"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Nonso

---

public/data/ShaileshParmar11.json

I have added my profile!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added new profile shaileshparmar11.json

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1642"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

'Adds npm ci remove npm install, `links` README'

---

public/data/Pratikkumare.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1662"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added a "github" Profile

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1663"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: changed the gitpod badge

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs : updated note in README.md

---

public/data/KemiDoyin.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1654"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add KemiDoyin.json

---

public/data/ThePyroTF2.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add ThePyroTF2

---

public/data/paulaxisabel.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1660"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add paulaxisabel

---

public/data/jideabdqudus.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1664"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add JideAbdQudus

---

public/data/dunnjacoba.json

Addition of link https://dunnjacob.vercel.app/ to links page. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update dunnjacoba.json

---

public/data/impranshu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1666"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add IMPranshu 

---

public/data/seths10.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Seth Addo

---

package-lock.json
public/data/mendax0110.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Add mendax0110

---

public/data/chamberezigbo.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1670"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Corrected a typo in bio

---

public/data/Hemantsw.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ADD hemantsw.json

---

public/data/lumary2.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add my profile as json file to public/data

---

public/data/kalyan-vurugonda.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1673"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add kalyan profile to LinkFree

---

.github/workflows/kubescape.yml

fixes #1680
fixes #1682 
```
[warning] current version 'v2.0.161' is not updated to the latest release: 'v2.0.166'
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing local objects
[success] Accessed to local objects
[info] Scanning. cluster: 
[success] Done scanning. cluster: 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Controls: 31 (Failed: 13, Excluded: 0, Skipped: 0)
+----------+----------------------------------------+------------------+--------------------+---------------+--------------+
| SEVERITY |              CONTROL NAME              | FAILED RESOURCES | EXCLUDED RESOURCES | ALL RESOURCES | % RISK-SCORE |
+----------+----------------------------------------+------------------+--------------------+ …
```

feat: kubescape action

---

public/data/devmukhtarr.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1677"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add devmukhtar profile

---

public/data/yiremorlans.json

Thanks for this open source linktree alternative!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1665"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add yire morlans linkfree page

---

public/data/amarjeet.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added  my profile

---

public/data/ben-dh3.json

Added my profile!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1675"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

addProfile

---

public/data/AnuragK.json

Add my profile 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1692"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile (AnuragK.json)

---

.github/workflows/reviewpad.yml
reviewpad.yml

This pull request adds Reviewpad Action to the project. For now, this simply adds a label depending on the size of the pull request.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1700"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adds reviewpad action to the project

---

public/data/SattyamSamania.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1697"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add SattyamSamania.json

---

reviewpad.yml

Closes #1707
This pull request introduces the descriptions for reviewpad labels.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1708"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add description to reviewpad labels

---

public/data/marcelosousa.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1705"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test: add marcelosousa profile

---

public/data/akshithbellare.json

<p align="center">All existing tests passed</p>
<p align="center">My profile page</p>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile (akshithbellare.json)

---

reviewpad.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: removed enforcing lint commits

---

public/data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1701"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: update my profile

---

package-lock.json
package.json

- Added linkfree cli to dev dependency
- Added linkfree cli script to package.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1695"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add linkfree-cli support

---

public/data/BoneNzy.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1714"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my Profile username.BoneNzy

---

public/data/OmAvhad.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created my profile.

---

public/data/SavanSutariya.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1717"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add profile Savan Sutariya

---

.vscode/settings.json
public/data/Aditya-150.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1726"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: added a new profile data

---

reviewpad.yml

fixed the spelling of the label to match the pre-existing label.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1722"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

closes #1721

---

public/data/Ashish-Khanagwal.json

Hey, please review my PR and ping me if any changes are required.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1729"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

profile-tree

---

public/data/mohanthilak.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1733"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

profile added

---

public/data/Aditya-150.json
public/data/ann-design-max.json

Please add my profile: ann-design-max 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1730"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add My Profile: ann-design-max

---

public/data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1725"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: github sponsors

---

public/data/Ayush0054.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1738"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

my contribution in linkfree

---

README.md
public/data/izzarzn.json

I have created my Linkfree Profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

## Created my Linkfree Profile

---

public/data/deepanshu1334.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1741"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

deepanshu profile

---

public/data/Maaz.json

#1745 
Added **Maaz.json** as a new file that has all my links.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1746"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding my Profile to be deployed! [Maaz]

---

public/data/sachdevlaksh.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added sachdevlaksh.json in public data

---

Dockerfile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

modified LABEL as Docker official documentation

---

public/data/rohitdasu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1750"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: added my profile

---

public/data/LinuxGamer.json

- Added my json to the repo
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1749"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added LinuxGamer.json

---

public/data/data2kinyungu.json

Glad to be able to add my Gthub profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Kinyungu added his profile

---

public/data/abhishek67.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1752"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

abhishek added his linkfree

---

public/data/Stevenovak123.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1756"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Profile: Stevenovak123

---

components/user/UserPreview.js

The `UserPreview` component was not responsive and it looked weird on mobile devices, so I added some Tailwind classes to the `UserPreview` to make sure it looks good on smaller screen too.
before changes :
after changes :
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1751"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: made UserPreview repsonsive

---

src/Components/Milestone.css

In this PR I have added the border radius to the milestone card and reduce the width of the card.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

border radius and width of card changed 

---

reviewpad.yml

Add `v2` label if PR is for `nextjs` branch
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1757"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: label PR for nextjs

---

public/data/shivam-sharma7.json

**Update my twitter and blog url.**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1762"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

update my twitter and blog url

---

public/data/michagodfrey.json

Hi EddieHubCommunity, I hope everything is ok with the json file I added to public/data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added michagodfrey.json to public data

---

public/data/sudeepta.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

I have added my profile

---

public/data/haldaranup.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update linkedin username

---

README.md

Merged the 2 different Warnings into 1 and increase the readability of text  
```
A note for Hacktoberfest participants
```
by making it a heading 
```
```
and **making lists** in the inside this heading.
Before 
```
> Pull requests which add or edit your information in a `public/data/${yourname}.json` file will NOT be counted for Hacktoberfest.
>
> Pull requests which improve the codebase, documentation, or other aspects of the project and are in line with the core values of the event will count. Maintainers will opt-in these PRs by applying the `hacktoberfest-accepted` label.
```
After 
```
> - Pull requests which add or edit your information in a `public/data/${yourname}.json` file will NOT be counted for Hacktoberfest.
> - Pull requests which improve the codebase, documentation, or …
```

docs: Improved README

---

public/data/ebenezer-akhonya.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1782"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add ebenezer-akhonya's profile

---

public/data/kanishbodhwani.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added json file with name

---

public/data/ZainMhrez.json

add ZainMhrez.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1771"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add ZainMhrez.json

---

public/data/gentlegiantdev.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1787"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: added public/data file

---

public/data/Yohn.json

This was fun to play with how GitPod works! Super easy to see it built on localhost and make any adjustments that were needed. Let me know if I need to send a pull request in differently, but I believe this should work.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1784"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding Yohn.json

---

src/Components/Profile.js

Closes #1770 
Fixes the share icon alignment on the profile page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1774"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix: share icon not aligned properly

---

public/data/Meyazhagan.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Meyazhagan.json

---

public/data/neutr0n420.json

I am trying to add my profile's JSON file to the webpage
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1797"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding my profile to the project

---

public/data/itsarghyadas.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

update my profile data

---

public/data/shubhambaghel.json

Added my username with JSON file under data folder
Please review and merge PR
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1791"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add shubhambaghel profile

---

public/data/ad3rinto.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1801"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add ad3rinto profile to data

---

public/data/eddiejaoude.json

Updated as part of a YouTube video
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: updated my profile

---

public/data/ShubhraSuman.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1804"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Changes done to add profile details in linkFree

---

public/data/adilwahla.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile 

---

reviewpad.yml

fixes #1811 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1812"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ci: exclude from hacktoberfest

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: highlight warnings

---

public/data/KhairallahA.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1809"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Khairallah AL-Awady

---

public/data/goobric.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1819"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

create goobric.json page

---

public/data/arefathi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1818"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add my link and bio

---

public/data/raeeceip.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1823"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my  profile

---

public/data/ImKunal13z.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1827"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my username

---

public/data/imran1509.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1830"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

 Adding my profile to the the public/data/

---

public/data/mjcoder15.json

- [ ✓] My code follows the code style of this project.
- [✓ ] This PR does not contain plagiarized content.
##Just added a JSON file 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1822"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added mjcoder15.json in public/data folder

---

public/data/krshkodes.json

Added my profile to linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1595"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: Added Krish Gupta

---

public/data/pranay202.json
src/config/user.json

create my linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1780"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add pranay202

---

public/data/Deepanshu0810.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1832"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

New profile

---

public/data/mayo7e.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Create mayo7e.json profile

---

public/data/itsbhavsagar.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Bhavsagar json profile page.

---

public/data/avie-dev.json

Updated my Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated avie-dev json profile 

---

public/data/Anushka-codergirl.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1842"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update changes - Linkfree

---

public/data/vczb.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1859"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add behance to vczb

---

public/data/adityasp1.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1860"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Create adityasp1.json profile

---

public/data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1861"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update eddiejaoude links

---

public/data/devmukhtarr.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added milestones to my profile

---

.dockerignore

closes #1829
- Added more elements to `.dockerignore` to reduce the build size 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1848"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: improved the `.dockerignore`

---

public/data/nicoleww.json

Adds my profile to the public/data folder (nicoleww.json)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add nicoleww.json to public/data

---

public/data/shivam-sharma7.json

Update my bio.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1869"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update my bio.

---

public/data/vinyldavyl.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1868"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add new profile vinyldavyl.json

---

public/data/kartikmehta8.json

Add Profile for **Kartik Mehta** @kartikmehta8
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1880"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Profile kartikmehta8

---

public/data/Amad3eu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1878"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Amad3eu profile 😁😁😁

---

public/data/RedHeadphone.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1875"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added RedHeadphone Profile

---

public/data/KyngCoder.json

Adding name to contribution list.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding name to contribution list

---

public/data/drsimplegraffiti.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1895"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add user profile Abayomi Ogunnusi

---

public/data/Ayush-Kanduri.json

This PR will add the Ayush-Kanduri.json file to the '/public/data' Folder.
Ayush-Kanduri.json file added to the directory '/public/data'.
Kindly Merge my PR. I would be glad.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1892"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add My Profile: Ayush-Kanduri.json

---

public/data/randyh0120.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1891"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Randyh0120

---

public/data/virtual-designer.json

* Added my profile information
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1904"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added new profile

---

public/data/salahawk.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1909"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added new profile - salahawk

---

public/data/CanisCoder.json

Added my profile (CanisCoder) to LinkFree 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1882"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added my profile (CanisCoder) 

---

public/data/Shivam-officials.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1864"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created the Shivam-officials.json file

---

public/data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1923"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: GitHub award

---

.github/workflows/deploy.yml

do not deploy to kubernetes
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1924"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: only publish container

---

public/data/anish27.json

Added anish.json file in public/data/
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added anish.json

---

public/data/aldyadk.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1940"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add My Profile JSON data

---

public/data/Sajal24.json

Name added
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1950"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Sajal24 added

---

components/Footer.js
tests/home.spec.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1967"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: footer test

---

public/data/Atharv181.json

Added my Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1965"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Atharv181.json

---

public/data/denyslins.json

Add data profile for Denys Lins
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1979"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add data profile for Denys Lins

---

public/data/franqsanz.json

Add data profile for Franco Sánchez.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1988"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Franco Sánchez

---

.gitpod.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Gitpod patch

---

.storybook/main.js
stories/components/navbar/Navbar.stories.js

Closes #1955 
Addition of components/navbar/navbar.stories.js
Adds Navbar to StoryBook.
Made Storybook look in ../public for static assets
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1960"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Navbar to Storybook 

---

stories/pages/popular.stories.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1983"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add Popular page to Storybook 

---

public/data/HimanshuSinghNegi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2006"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

HimanshuSinghNegi LinkedFree profile added

---

public/data/Rishav-12.json

Add Rishav-12's profile to public/data directory
_N/A_
_N/A_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2005"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add Rishav-12's profile to public/data directory

---

public/data/Nitesh-thapliyal.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1997"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

create Nitesh-thapliyal.json LinkFree profile

---

docs/contributing/contributing-icons.md

Fixed some grammatical errors and rephrased sentences to enhance the quality of the document.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2011"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Docs(update): Corrected documentation errors

---

pages/api/statistics/[...data].js
pages/api/users/[username].js

The Mongoose Model.update() function is [deprecated](https://mongoosejs.com/docs/api.html#model_Model-update).
This PR replaces it with calls to updateOne().
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2013"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[NextJS] Mongoose - change deprecated update to updateOne

---

README.md

Split line 11 into two parts to make it less wordy. 
Added "your" to line 109
Changed the line "after your PR is merged, the project still needs to be deployed for your profile to be displayed" to "after your PR gets merged, the project still needs to be deployed for your profile to be displayed"
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2010"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Docs(update): Edited grammatical errors in README.md

---

package-lock.json
package.json

Closes #1987 
Update React to version 18,
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2007"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[NextJS] Bump React to 18

---

components/navbar/Navbar.js

Closes #1980 
Added react state to open and close mobile menu on click
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2001"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: mobile menu open and close functionality

---

public/data/virtual-designer.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update profile info

---

components/user/UserLink.js

The UserLink component was using buttons for links.
This has accessibility (a11y) concerns.
You can find more about it by searching "link button a11y"
This PR changes UserLink to use anchor tags.
It also takes advantage of the anchor tag ability to open links in a new tab. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2028"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[NextJS] Change UserLink to use anchor tag instead of button

---

public/data/maemreyo.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

I would like to add my profile to LinkFree

---

.npmrc
components/FallbackImage.js
components/navbar/NavLink.js
components/navbar/Navbar.js
components/user/UserPreview.js
package-lock.json
package.json
pages/index.js

[Next 13](https://nextjs.org/blog/next-13) was just released with the opportunity for many performance improvements.
This PR bumps Next to 13 and handles the breaking changes necessary for migration.
This PR does not take advantage of any new features.
This PR migrates `next/image` to `next/legacy/image` as there is a new Image component with different defaults.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2042"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[NextJS] Migrate to Next 13

---

public/data/eltociear.json

Add my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2046"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add ikko ashimine prof.

---

public/data/BasilMuhammed.json

Adding Basil profile to the link tree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2056"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added basil's profile data

---

src/Components/Search/Search.css

Closes #2027 
- In Dark mode when hovering over the user profile's font color is changed from `white` to `black`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2029"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Changed profile name font color on hovering in Dark mode. #2027

---

pages/popular.js
pages/search.js

Closes #2044 
Removed underline from titles and also made title size bigger
Desktop View:
Mobile View:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2053"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(ui): removed underline from pages title

---

src/Components/Search/filterProfileType.js

Fixes Issue  https://github.com/EddieHubCommunity/LinkFree/issues/2016
aria label was missing for the dropdown in the `search` route. 
Lighthouse audit of the site (before)
Lighthouse audit of the site ( after ) 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(#2016) : dropdown label accesibility issue

---

tests/profile.spec.js

Closes #2031 
I added 2 tests to `./tests/profile.spec.js`  to test what was listed in the comments. 
I believe I mentioned in #2031 that I was getting funky results from the Firefox tests with playwright.
In order to deal with those, I made a conditional to handle the value I was getting back.
If that doesn't work for you, let me know and I can change it so that we can just check to make sure the number is between 3 and 5 views. If it doesn't pass the tests locally for you.
Let me know if you want me to change anything, or have any questions.
Thanks 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2057"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: 2nd and 3rd Playwright tests for profiles

---

NOCODE-CHANGELOG.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2061"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my information.

---

public/data/CBID2.json

Feel free to give me feedback 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2058"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added Linktree profile

---

public/data/RohithJN.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2064"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Create Profile RohithJN.json

---

public/data/Ayush-mega-coder.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2071"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

open source

---

components/Footer.js
components/layouts/MultiLayout.js

Closes #2072 
Footer position is changed to bottom of the page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2073"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: footer position is changed

---

components/Icon.js
components/user/UserLink.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2074"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Feat: link type icons

---

components/user/UserLink.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2076"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: link colors

---

stories/components/navbar/Navlink.stories.js

Closes #2078 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2079"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Storybook component

---

pages/search.js

Need 3 characters before showing results
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2081"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: min 3 search characters

---

NOCODE-CHANGELOG.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2091"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my information

---

public/data/sreejit-sengupto.json

- Created a linkfree for myself.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2075"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created my Linkfree

---

public/data/omk-coder.json
public/data/omkar009.json

Added Profile on LinkFree

---

public/data/SatyasaiNandigam.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2092"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my profile to Public/data/

---

public/data/Akshay-bendadi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: add Akshay-bendadi

---

public/data/krupalitrivedi.json

Add `krupalitrivedi` to LinkFree
Thank you maintainers for looking through my PR! :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add krupalitrivedi

---

public/data/vikalp-tomer.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2111"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add vikalp-tomer

---

src/Components/Search/Searchbar.js

Changed font color to black and improved the box-shadow property and changed the background
color gradient to make the text properly visible.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2094"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Improved dark mode property of the UI

---

src/Components/Footer.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fixed Footer component to open urls externally

---

src/Components/Search/Search.css

Changed font color to black and improved the box-shadow property and changed the background color gradient to make the text properly visible.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2051"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Improved the hover UI part in Dark Mode #2027

---

src/Components/ScrollToTopBtn.css
src/Components/ScrollToTopBtn.js

- Change the color of the scroll to top button on hover.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Chore: change color for scrollToTop

---

src/Components/Footer.js
src/Components/Home.js
src/Components/Navbar.js
src/Components/Search/Search.js

Closes #1972
Align icons vertically in the Home, Navbar, Footer, and Search components.
The issue only refers to some icons not aligned, but I found other icons with the same problem and fixed all of them.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1981"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Align icons in the Home, Navbar, Footer and Search components

---

src/Components/Search/Searchbar.js
src/Components/Search/Users.js
src/Components/Search/filterProfileType.js

Closes #1964
Increase search and profile type input width. Also, add responsive behavior to this section.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1982"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Increase search and profile type input width

---

package-lock.json
package.json
src/Components/Home.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18kM6dW8SNQGZWOuge8WLmVkb3kyHKLK4U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=AxdfnQy)
enhances the webpage
https://user-images.githubusercontent.com/91059418/196380717-a91627c7-188a-4b11-af67-6bab54c26dbe.mp4
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/ …

implemented typewriter effect using typewriter-effect package

---

package.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2047"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

updated v5 to v6

---

src/Components/Links.css
src/Components/Links.js

Closes #2070
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Hover movile fixed

---

data/eddiejaoude.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: markdown in my profile

---

data/CBID2.json

I updated my Milestones Section
Hi Eddie! I finally formatted my JSON file. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated Milestones section

---

reviewpad.yml

- removed v2 lable from `raviewpad.yml`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: remove version 2 labels

---

reviewpad.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Made changes

---

README.md

closes #2147 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[DOCS] remove gif from README.md

---

data/CodingSpecies.json

I updated my profile with milestones and set my public stats to true.
Thank you.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added milestones and public stats to my profile.

---

package-lock.json
package.json

- Added [**LinkFree-CLI**](https://github.com/pradumnasaraf/LinkFree-CLI) support (Now compatible with Next.js)
`package-lock.json` will also be modified as a new dependency has been installed.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Added LinkFree-CLI support

---

data/publikphigor.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Created publikphigor.json to create my LinkFree profile

---

pages/[username].js
pages/api/users/[username].js
pages/search.js
tests/profile.spec.js

fixes #2146
- When a user profile is not found it redirects to the search page with an error message
- Also when searching if no users are found the same error message is displayed
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: user not found

---

data/CBID2.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2161"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Removed 2022 line 28.

---

README.md

Closes #2163 
- Fixes links as marked by @Panquesito7 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix] Update inspiration links

---

data/CBID2.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added to information to line 3.

---

data/philling1.json
public/data/philling1.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2003"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding my profile to the public/data

---

data/abhay-h.json

Changed my twitter && github profiles
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2158"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Profile update ( Twitter & Github)

---

data/panquesito7.json

- Update Panquesito7's profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: update Panquesito7's profile

---

pages/index.js

Closes #2142 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix index image stretching

---

data/fluentmoheshwar.json

Created fluentmoheshwar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added my linkfree

---

components/user/UserPreview.js
package-lock.json
package.json
pages/[username].js
pages/api/statistics/totals.js
pages/index.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Views count

---

public/data/Akshay-bendadi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

bio update Akshay-bendadi

---

pages/index.js

Fixes #2155
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added name LinkFree to the landing page and made it more prominent

---

pages/[username].js

fixes #1366 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: opengraph meta data #1366

---

data/Brian-Nduhiu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update and rename brianNduhiu.json to Brian-Nduhiu.json

---

README.md
pages/[username].js

This PR fixes open issue #1301
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2204"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

profile tag added

---

public/data/Akshay-bendadi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

improved profile Akshay-bendadi

---

data/Ashimdevnath.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Milestone Added

---

data/Sajiyah-Salat

I tried my best understanding the linktree and added my profile if there is any changes required please tell me
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Sajiyah-Salat

---

public/data/Akshay-bendadi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update Akshay-bendadi.json / not able to see previous changes

---

components/Icon.js
components/user/UserLink.js
components/user/UserMilestone.js
components/user/UserSocials.js
package-lock.json
pages/[username].js

https://user-images.githubusercontent.com/85363195/201333068-16c425ff-ce4b-42c6-815e-c1de17244f83.mov
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add User Social Icons

---

data/Akshay-bendadi.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

profile Akshay-bendadi

---

pages/index.js

- Closes #2194 
- Changed index.js file
- ### Before
- ### After
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2219"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Horizontal Scroll Bar fixed #2194

---

README.md

Closes #2226
Update storybook example link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update storybook example link (#2226)

---

data/furkanmutlu.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add furkanmutlu

---

data/abhirk247.json

Add Abhishek Anand to LinkFree
Thank you maintainers for looking through my PR.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2205"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Abhishek Anand profile

---

README.md

- Link to releases for the release badge.

chore: link to releases for the release badge

---

reviewpad.yml

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added removeLabels to remove old labels in reviewpad.yml

---

data/imran1509.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated my linkfree profile

---

README.md

The PR fixes small grammatical issues on README.md 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: fix grammatical errors in `README.md`

---

data/juliafmorgado.json

Add juliafmorgado.json to the data file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add juliafmorgado.json

---

data/zittogustavo.json

Create new linktree data file with my resume
Add my json file to data folder
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2237"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add new profile: Create my data json file

---

data/akshaykumar05.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding my profile to linkfree

---

components/user/UserCard.js
components/user/UserPreview.js
pages/popular.js

Closes #2221  
Changed profiles layout in `popular profile page ` from `horizontal` to `grid` one
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feature : popular page styles

---

data/Pradumnasaraf.json

- Updated Pradumnasaraf's LinkFree profile.

chore: updated Pradumnasaraf's profile

---

components/navbar/Navbar.js
package-lock.json

fixes #2249 
update github text link on desktop and mobile to icon
BEFORE
AFTER
Tests did not pass in gitpod, pushing to see if they pass through gh actions as the failures are due to some configuration issue I have not been able to solve yet.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update GitHub link to icon

---

data/mazahaca.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added profile for mazahaca

---

.github/workflows/build.yml
.github/workflows/community.yml
.github/workflows/deploy.yml
.github/workflows/kubescape.yml
.github/workflows/prettier.yml
.github/workflows/release.yml
.github/workflows/storybook.yml

Closes #2241 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update Action Dependencies to Latest Version

---

data/SaptarshiSarkar12.json

added a milestone which describes my Hacktoberfest participation in short.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added a new milestone in my Linkfree profile

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

doc:fixed spelling error

---

data/shericodes.json

Add new profile for shericodes
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add profile for shericodes

---

pages/api/users/[username].js

Improvements the performance of the profile page
- no need to filter files
- we know the filename

fix: load json file directly

---

data/eddiejaoude/CBID2.json

I tried creating my own testimonial folder, but I felt like I was not doing it like Eddie was in today's video. So, I created a testimonial file to add to Eddie's profile. I'm open to feedback.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2275"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Review for Eddie

---

data/eddiejaoude/Akshu-on-github.json

Linked to PR #2271 
Add my testimonial for Eddie
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[Test] Add testimonial

---

components/Icon.js
pages/index.js

Closes #2281
Added a new help button on the index page. It links to discussions in linkfree repo
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2283"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add help button in home page

---

data/LinuxGamer.json

Fixes Mastodon link not clicking
Changes URL to url.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update LinuxGamer.json - Mastodon link fix
