EddieHubCommunity/BioDrop

data/Yushi5058.json
- Add anilist.co link 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4950"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add anilist profile link

data/vivekyadav19.json
I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4949"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vivekyadav19

data/HIMANSHIKSHARMA.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4953"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data.HIMANSHIKSHARMA

data/dev-rakeshshaw.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4951"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: dev-rakeshshaw

data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: grand-rick001

data/PriyanshShrivastava.json
docs: adding my (Priyansh Shrivastava) data in LinkFree repo.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: PriyanshShrivasatava

components/map/Map.js
Fix #4817 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4873"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added reactmarkdown on user bio in map.js

pages/index.js
added the full stop which was missing from milestone section of index page.
Closes #4838 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4874"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fullstop-missing-fixed

pages/docs/how-to-guides/testimonials.mdx
This pr solves the issue where the symbols such as < and > are being displayed by their entity name .
Closes #4930 
Changed the symbols and used the entity names instead 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Escape special characters

pages/docs/how-to-guides/testimonials.mdx
=> docs: testimonial improvements

data/RobJackTech.json
Thank you for taking the time to review my pull request!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4924"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Rob jack tech patch 1

data/mjosh51.json
Adding personal profile - username: mjosh51, name: Joshua Mayowa, to EddieHubCommunity.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4959"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mjosh51

README.md, data/Yushi5058.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove '-' from docker-compose up command

data/Ajay84sia.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4981"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : Ajay84sia

data/mahfuztbt.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4978"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:mahfuztbt

data/SohamRoy-01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4977"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : SohamRoy-01

components/navbar/Navbar.js, pages/changelog.js
fixes #4727 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4915"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: changelog #4727

pages/index.js
closes: #4962 
Added Map section in Homepage feature.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4991"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add Map section in Homepage feature

pages/docs/index.js, pages/docs/map.mdx
Closes #4956 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4986"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added new page for map docs

config/logger.js, pages/api/events.js
When visiting the `events` page locally an error is shown in the console because the events directory does not exist locally.
I had a conversation with Eddie on Discord about this error. They suggested to change this error into a warning instead. Here's the [link](https://discord.com/channels/699608417039286293/699608417928740944/1074344240756293642) to the conversation and also below are the images of the same for your reference: 
After making the changes these `warnings` will now be shown instead of the `errors` shown earlier
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4913"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Replace error with warning

data/IPratikMali.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4998"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: IPratikMali

data/grand-rick001/events/2023-03-4-apis-101-with-postman.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5011"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Grand rick001 patch 3

components/Testimonials.js, pages/index.js
=> Linkfree testimonials

package-lock.json, package.json, pages/[username].js
closes #3950 
Remove markdown from the description for now. as discussed in the issue. maybe markdown could be added if any new solution is found.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4898"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Markdown not being rendered in the description when sharing profile

data/SubhadeepZilong.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5000"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SubhadeepZilong

data/AdamsGeeky.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5005"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AdamsGeeky

data/ahmedrowaihi.json
- updating my  Ahmed Rowaihi CV link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5016"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updating my  Ahmed Rowaihi CV link

data/rohitt-gupta.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5018"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rohitt-gupta

data/SurajPratap10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SurajPratap10

data/MadhoolikaNagesh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5042"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:MadhoolikaNagesh

data/sachindevs.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5047"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> sachindevs

data/dev-rakeshshaw.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Dev rakeshshaw patch 7

data/Poshith24.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5050"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Poshith24

data/sumitNITS.json
Hi,
I have committed my LinkFree page code for the first time. Please check this and let me know if there is any mistake done by me! Thanks for maintaining this wonderful repo.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5052"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:sumitNITS

data/VarchasvH.json
Added some new links to my LinkFree page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5044"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updating my LinkFree page

data/weilincheng.json
Add new data for weilincheng
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: weilincheng

data/Udayan-Singh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5031"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Udayan-Singh

data/jacksonmathew.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5060"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: jacksonmathew

data/yrncollo.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5037"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added my details on linkFree

Chetax.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5055"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Chetax

data/preshpi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5063"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: preshpi

data/Manishku0722.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5065"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Manishku0722

data/VaibhavSinghDev.json
File name: singh-vaibhav08.json -> VaibhavSinghDev.json
Twitter: singh_vaibhav08 -> VaibhavSinghDev
LinkedIn: singh-vaibhav08 -> vaibhavsinghdev
Github: singh-vaibhav08 -> VaibhavSinghDev
Dev.to : singh_vaibhav08 -> vaibhavsinghdev
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5070"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update filename and profile links

NitishRawat123.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4969"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:NitishRawat123

data/coder-XX04.json
updated the linkedin profile link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5071"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updates coder-XX04.json

data/devjavedmohd.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4866"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: devjavedmohd

data/KellynCodes.json
changed: Made a mistake creating my JSON file in the root directory instead of the /data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5072"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: KellynCodes

data/WillBeebe.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5077"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: WillBeebe

data/edsodz.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5079"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:edsodz

components/event/EventKey.js, components/user/UserEvents.js
Tweaked PR https://github.com/EddieHubCommunity/LinkFree/pull/4574
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Events past

components/user/UserEvents.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5086"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: future events filter

pages/account/statistics.js
Closes #5023 Fixed profile view stats chart not displaying on hover bug 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5092"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Profile view stats hover bug

pages/docs/how-to-guides/editing.mdx
fixes #5066 
Added a video at the top of the editing profile docs page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5093"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add embed youtube video

data/TRohit20.json
The community is awesome and all of you are doing an absolute great job. I would love to have my link free profile created and updated. Thank you :) 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5098"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: TRohit20

data/Hacktinium.json
Create LinkFree JSON file. Add basic info & links.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Hacktinium

data/devjavedmohd.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5089"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:devjavedmohd

data/mustafaansarii.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: mustafaansarii

data/Nikhil26112.json
This is my first pull request.
Added my bio and my socials.
- [✅] My code follows the code style of this project.
- [✅ ] All new and existing tests passed.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.
This is my first pull request.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: NikhilChauhan

data/WillBeebe.json
=> he doesn't need this anymore

data/Judeadeniji.json, data/OluwaFeranmi.json
- [ X ] My code follows the code style of this project.
- [ X ] My change requires changes to the documentation.
- [ X ] I have updated the documentation accordingly.
- [ X ] All new and existing tests passed.
- [ X ] This PR does not contain plagiarized content.
- [ X ] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Judeadeniji patch 3 1

data/WillBeebe.json
=> data: Sydney.json doesn't use spell check

data/JeanFerreira91.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: JeanFerreira91

data/Lakorthus.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5131"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Lakorthus

data/mirazxmondal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Miraz

data/Lakorthus.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Lakorthus youtube link fixed

data/CBID2.json
I changed the information in my bio section 
Feedback on the format is appreciated 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5115"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed my bio

pages/docs/environments/linkfree-cli.mdx
- Improve the steps in LinkFree CLI docs
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update LinkFree CLI steps

pages/docs/how-to-guides/events.mdx
- Add [Unix Timestamp](https://www.unixtimestamp.com/) as a resource.
- At first, I was confused about how to properly use these time things. This could help others with setting the times properly.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5139"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: add Unix Timestamp as a resource

data/0rigin-c0de.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: 0rigin-c0de

pages/docs/environments/gitpod.mdx, pages/docs/environments/local-development-docker-compose.mdx, pages/docs/environments/local-development.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: local dev link to env vars

data/thebarshablog/events/2023-03-15-chaos-carnival.json
Please add chaos carnival to the list of events in my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add Chaos Carnival

data/yrncollo.json
There was some of broken links on my bio. So I have updated them.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated broken links

pages/docs/environments/gitpod.mdx, pages/docs/environments/local-development-docker-compose.mdx, pages/docs/environments/local-development.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: envar link

data/Rishikavishnoi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: RishikaVishnoi

styles/onedark.css
- #5094
Add some padding to the following code.
```css
/* Inline code */
:not(pre) > code[class*="language-"] {
/* padding: 0.1em; */
padding: 0.3em 0.4em;
border-radius: 0.3em;
white-space: normal;
}
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Add padding to inline code block

CONTRIBUTING.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: contributors guide

data/ShivanshPratap.json
You all are doing a great job. I would like my LinkFree profile to be updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ShivanshPratap

data/Ashutosh-s07.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ashutosh-s07

data/SurajPratap10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Update SurajPratap10.json

data/aakashditya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aakashditya

data/rohitverse.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rohitverse

data/Hishammpsnhn.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: hishammpsnhn

data/Gautam-666.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Gautam-666

data/JohnnyLegault.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5188"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: JohnnyLegault

data/leo7736.json
adding data 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:LeoAdd

NOCODE-CHANGELOG.md
Adding the link to my blog upon Eddie's suggestion to help more people get started with open source and get involved in communities
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding the link to my Blog in NOCODE-CHANGELOG.md

data/sahil-sagwekar2652.json
This pull request does not fix anything. It is for my LinkFree page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5220"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sahil-sagwekar2652

data/Gautam-666.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: fix Gautam-666

data/DominicFrei.json, data/dominicfrei.json
Add the file dominicfrei.json for the profile `Dominic Frei`.
~~My change requires changes to the documentation.~~
~~I have updated the documentation accordingly.~~
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: dominicfrei

README.md
=> docs: linked to full documentation

data/atanda0x.json, data/ksen21.json
=> data: remove avatar key

data/imf-ali.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5245"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: Fahad Ali

data/DominicFrei/testimonials/loftwah.json
My mistake from earlier
Updating testimony
Check your work before you submit it haha. My bad. Sorry.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> I messed up my testimony for Dominic

data/J-CODE07.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: J-CODE07

data/mrdanishsaleem.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mrdanishsaleem

data/LaPulgaaa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:LaPulgaaa

data/an4s911.json
Add an4s911
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: an4s911

data/md-abid-hussain.json
added glitch profile link to my linkfree profile and also fixed codepen icon in profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added glitch profile and fixed codepen icon

data/yashpandey002.json
PR for Profile addition
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yashpandey002

data/anuragts.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: anuragts

data/VardaanAggarwal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5267"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: VardaanAggarwal

data/Akash3121.json
Added a new chore: Akash Reddy Jammula
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Akash Reddy Jammula

data/Shivam-Katare.json
- Updated my Linkfree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5275"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update: Shivam-katare.json

data/Gautam-666.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Gautam-666

components/Button.js, components/FallbackImage.js, components/PreviewModal.js, components/form/input.js, components/modals/ProfilePreview.js, components/navbar/Navbar.js, components/user/UserPage.js, components/user/UserProfile.js, components/user/UserTestimonials.js, pages/playground.js, pages/search.js
Issue https://github.com/EddieHubCommunity/LinkFree/issues/2645
Pull Request https://github.com/EddieHubCommunity/LinkFree/pull/4211
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5273"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Playground refactor

pages/changelog.js
=> docs: user changelog

AM, data/AFB-M.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:AFB-M

CONTRIBUTING.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: reviewing pull requests

data/EslemOuederni.json
Added my profile ! 
If there's any edits for me to make please let me know
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: EslemOuederni

data/SageKyle.json
update LinkFree profile by adding a milestones section
I changed the entire data because I used a JSON formater/validator to format the entire data before copying/pasting the formatted data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SageKyle

pages/api/statistics/today.js, pages/api/statistics/totals.js, pages/index.js
Fixes index page for #5069
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Convert fetches to function calls for index page

data/harshit-002.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:harshit-002

data/ZendeAditya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Zende aditya patch 3

data/fatemaker254.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5320"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: fatemaker254

data/ni5arga.json
Added ni5arga.json file!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5326"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added ni5arga.json

data/khushalarora.json
Awesome and easy to understand documentation. Thanks for encourging me for my first PR :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5327"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: khushalarora

data/itsshahinhere.json
Added my profile to the linkfree repo, to showcase my profile link in my accounts! 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: itsshahinhere

data/JohnOkari.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: JohnOkari

data/Uthycloud.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5341"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Uthycloud

data/tenyapious.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: tenyapious

data/coder-chahal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:coder-chahal

data/iAnonymous3000.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5342"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: iAnonymous3000

data/Arindam200.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Add]: YouTube Channel links and Milestone at ```Arindam200.json```

data/AKHIL-GIREESH.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AKHIL-GIREESH

aakshitaa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aakshitaa

data/CodingWithCard.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5368"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: CodingWithCard

data/MadhuSaini22.json
=> add:testimonials on my profile

data/Danypooh.json
profile update
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5391"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Danypooh

data/vprankul0306.json
Added vprankul0306.json to the data folder
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vprankul0306

data/Tejasp2003.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Tejasp2003

data/MahabubArafat.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5383"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: MahabubArafat

data/ArslanYM.json
- [x All new and existing tests passed.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5378"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ArslanYM

data/avnigoyal25.json
contributing to open source
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5361"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : avnigoyal25

data/mdarslan7.json
Started contributing to Open Source!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mdarslan7

data/dfdevaney.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5358"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: dfdevaney

pages/map.js
Closes #5313
How can I write map.spec test? I followed the docs but for some reason the test was not executed. Do I need to execute the tests on docker container env?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5331"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [FEATURE] Tag filter highlight on map page #5313

data/fadebowaley.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5402"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding of json data  fadebowley.json to LinkFree

data/Visakan-official.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5409"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Visakan-official

data/deepakrudrapaul.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: deepakrudrapaul

components/event/EventCard.js, data/eddiejaoude/events/2023-07-27-wearedevelopers.json, data/eddiejaoude/events/2023-09-18-talk-infobip.json, pages/docs/how-to-guides/events.mdx
Refactor of PR https://github.com/EddieHubCommunity/LinkFree/pull/4438
=> Event location

pages/docs/how-to-guides/events.mdx
=> docs: event location

pages/changelog.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5428"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: new domain notes in changelog

pages/docs/index.js
Fixed PR https://github.com/EddieHubCommunity/LinkFree/pull/5125
=> Docs hover

README.md
fixes #5437
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5438"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Links are updated to latest domain

pages/docs/how-to-guides/editing.mdx
Updated link to latest domain in editing.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5444"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update link to latest domain

pages/docs/environments/local-development-docker-compose.mdx
I noticed a few typos on [this page](https://linkfree.eddiehub.io/docs/environments/local-development-docker-compose) while browsing the site and this PR will fix those.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: fix typos on "local development with docker compose" page

data/fabian4.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5431"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: fabian4

data/manishitMani.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5450"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: manishitMani

data/WillBeebe.json
Edits welcome, not expected. If there's a better way to add to links or something. No worries if not. Goodnight and thank you for not telling me to stop. But you can tell me to RTFDA. <3 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5144"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: WillBeebe.json

pages/map.js
Closes #5405
There is a known issue where the tag totals don't match up with the number of users that are on the map page. This will be addressed in #5470.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5471"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Implements total results for map display (#5405)

data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5476"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: grand-rick001 - Added Milestone, updated Bio

NOCODE-CHANGELOG.md
Livestream replay talking about EddieHub, LInkFree, and Open Source
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Livestream link

data/Chintu1509.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Chintu1509 patch 2

data/AryanParashar24.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5479"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AryanParashar24

data/analizzi.json
Thank you ChatGPT for the bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: analizzi

data/Med16-11.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5360"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Med16-11

data/jatin510.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: jatin510

data/bkpecho.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: bkpecho.json

data/Gab-Riel404, data/Gab-Riel404.json
-  Created my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Gab-Riel404

data/Antonio-Riccelli.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5497"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Antonio-Riccelli

data/baruKreddy.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : BaruReddy

data/MAYANKpandey14.json
Added some new links and socials.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: MAYANKpandey14

data/Kgkunal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Kgkunal

data/Abid-dev.json
To add myself to linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5506"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Abid-dev

data/neerajkumar161.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add: data/ennkay161.json

reviewpad.yml
closes #5371 
Add label to PR status: blocked if
- not `chore: profile`
- and issue does not have label `status: ready for dev`
- and there is no issue number
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5394"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: add label `status: blocked` to PR

reviewpad.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: reviewpadreport

.github/workflows/reviewpad.yml
#5511
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: reviewpad run for more events

reviewpad.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: reviewpad block label

reviewpad.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: removed pull request link to issue check

reviewpad.yml
=> fix: reviewpad verbose off

data/alcb1310.json
Added a json data file with my username
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: alcb1310

data/nerdynikhil.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: nerdynikhil

data/aaditya-paul.json
Created aaditya-paul.json in data folder
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created aaditya-paul.json

data/rohit190183107010.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5547"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rohit190183107010

data/keywordvfx.json
Hi everyone, you all are doing great job. I would like to create my profile on LinkFree. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:keywordvfx

data/priyankarpal.json
- added milestones
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: added milestones

data/tanitoluwam.json
#5571 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: move tanitoluwam to data folder

data/sandramsc.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : sandramsc

data/yhuteemoren.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5586"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yhuteemoren

data/STIAANWOL.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: STIAANWOL

data/otnansirk.json
Adding new data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:otnansirk

data/AnshikGupta.json, data/guptaanshik1.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5578"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:AnshikGupta

package-lock.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: high outdated dependencies

data/Engeniusam.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5585"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Engeniusam

data/gambhirsharma.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data gambhirsharma

pages/playground.js
Closes 
- #5337 
1) spacing between label and input
2) json placeholder addition
**Before**
**After**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5554"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed placeholder and spacing between label and input

data/Pushpa-Mali.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5577"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Pushpa-Mali

data/Mohiit70.json
Hi Eddie,
Thank you for taking the time to review my pull request. This is my first contribution to an open-source project, and I'm excited to be a part of this community.
Please let me know if there's anything that needs to be fixed or improved. I'm open to feedback and eager to learn.
Thank you again for your time and guidance.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5568"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Mohiit70

data/Senozoid.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Senozoid

data/SGsubhash77, data/SGsubhash77.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5599"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SGsubhash77

data/karthiknadar1204.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5604"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:karthiknadar1204

data/Hittitech.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Hittitech

data/chirag0002.json
Added my profile to LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: chirag0002

data/Amishapopli1.json
You all are doing a great job.I would like my Linkfree profile to be updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5618"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Amishapopli1

CONTRIBUTING.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: contributing guide labels

data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: grand-rick001 - Update postman badge link

pages/[username].js, pages/account/statistics.js, pages/api/users/[username]/index.js
Closes #5311 
This is not completed. This is a draft pr.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5595"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Account Statictics own visit added after every visit

data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: grand-rick001 -- Add Wakatime link

README.md
I have added a **NOTE block** for the _note_ written in **GitHub UI** section and added _links_ to _specific sections_ of the README file for **better accessibility**.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Formatted some lines of README file

data/utkarshkrishna2004.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5642"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: utkarshkrishna2004

data/yaser-alazm.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5651"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yaser-alazm

data/abrokinla.json
Added new portfolio link
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5645"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: abrokinla

components/Testimonials.js
Closes #5640
Removed extra spaces from Testimonials.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix:Removed extra space from testimonials.js

data/Landouda.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Landouda

data/mrdanishsaleem.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5664"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add showwcase link

data/tarunclub.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5663"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: tarunclub

data/ShubhamMore6688.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5662"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ShubhamMore6688

components/map/Map.js
closes #5635 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5659"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Zoom limit on map is set

data/dineshlalam15.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data dineshlalam15

data/Ellah120.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ellah120

data/geeky-sambhav.json, geeky-sambhav.json
You are doing a great job. I would like my Linkfree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5656"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: geeky-sambhav

components/Badge.js, components/Button.js, components/Tag.js, pages/map.js
- Added disabled effect for clear/reset button when no tags are selected.
- Made some css tweaks for the alignment of tags and it's numbers. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix for the disabled effect of Button component.

components/Badge.js, components/Button.js, pages/map.js
Removed unrequired code changes https://github.com/EddieHubCommunity/LinkFree/pull/5681/files
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5701"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Map clear fix

data/Jahan2003.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Jahan2003

data/Paiman-Rasoli.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5686"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> connect-me-profile-with-linkFree

data/Manoj-71.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5703"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Manoj-71

RamanandThakur.json, data/ramanand-rv.json
Added my profile data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ramanand-rv

data/PetrusHimself.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5692"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Petrushimself

data/dineshlalam15.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5706"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: dineshlalam15

data/roberanegussie.json
Adding my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5689"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: roberanegussie

data/Junnygram.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5704"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Junnygram

data/Anmol-Baranwal.json
I didn't create an issue, since I am just updating a profile.
- I have validated the JSON.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5718"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update Anmol-Baranwal JSON data

data/Nikhilfy.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5717"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Nikhilfy linkfree profile 

README.md
fixes #5730 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: screenshots in readme

data/BenceDv.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: BenceDv

data/B2prakash.json
you'll are doing  a great job . i would like my Linkfree profile to be updated 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:B2prakash

pages/changelog.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5739"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: qr code download user changelog

components/user/UserPage.js, components/user/UserTabs.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5742"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: removed tab sorting

pages/changelog.js
Closes  #5716 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5748"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added a new progress object

data/Poonam1607.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Poonam1607

data/CBID2.json
I improved my Linkfree profile. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Sectioned my Linkfree profile

data/akshatshukla13.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5741"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: akshatshukla13

data/Vishal21121.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5758"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Vishal21121

data/nkitanand.json
Adding my profile to linkfree.io
Accept the PR request if no correction needed.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5750"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:nkitanand

data/Kevinkp09.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5759"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Kevinkp09

pages/docs/environments/linkfree-cli.mdx
Closes #5555  (That's a sweet number (: )
- New demo GIF
- Hyperlinked the text
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5768"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: improve the LinkFree-CLI page

pages/docs/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: community resources link

pages/index.js
Closes #5771
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Homepage]:Statistics screenshot added to features section.

data/AdityaChaudhary3.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:AdityaChaudhary3

data/surajmaity1.json
All of you are doing amazing stuff. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: surajmaity1

pages/search.js
closes #4124
Closes #4124 
Optimised search by adding search by GitHub Username Feature
**Before:** 
Without GitHub Username
With GitHub Username
**After:**
With GitHub Username
Without GitHub Username
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5795"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Optimised search to find by GitHub Username Added

data/Satyxm.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5782"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added LinkFree profile JSON file.

data/prashant235913.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5794"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: prashant235913

pages/docs/faqs.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5800"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Link for Single User Mode 404d, added the missing / and advanced folder

pages/docs/contributing/hacktoberfest.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5799"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Grammar fix on Hacktoberfest page

components/Testimonials.js, components/navbar/Navbar.js, pages/index.js, styles/globals.css, tailwind.config.js
=> added tailwind classes to home page

data/DrVickie8.json
Changed my bio
Added tags to my bio
Edited my links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: DrVickie8

data/Abdullah-moiz.json
Created my profile by following the https://linkfree.io/docs/quickstart
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5802"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data :  Abdullah-moiz

data/dineshlalam15.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5733"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Dineshlalam15 patch 4

public/manifest.json
closes #5751
Correct line sequence.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5752"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> switched line 7 and 8 in public/manifest.json

data/JonVojtush.json, data/JonVojtush/testimonials/bethDubyak.json, data/JonVojtush/testimonials/rickPollick.json
Second attempt at pull request to initailly load a profile page for Jon Vojtsh
=> Create a new repo. add main & supporting files

data/Palakkgoyal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5814"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Palakkgoyal

data/grand-rick001.json, pages/docs/quickstart.mdx
Closes #4999
Added new Screenshots that align with information given in docs , and removed the old screenshots which showed the avatar property .
Had to remove the earlier PR due to some technical issue made this one keeping in mind all the requirement suggested earlier.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated the screenshots for Quickstart guide

components/user/UserTabs.js
* data:dhruvilmehta
* Fix issue #3080 by making changes in UserTabs.js
https://github.com/EddieHubCommunity/LinkFree/pull/5816
* Solved Issue#3080
* Updated UserTabs.js
* Delete dhruvilmehta.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5826"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: removed dropdown if user has only links (#5816)

data/priyanshu096.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5837"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: PriyanshuPatel

data/pushkaraj2007.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: pushkaraj2007

data/priyankarpal.json
- added new link, changed bio, tags
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5848"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> profile: added new link, changed bio, tags

data/ashlab05.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5843"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ashlab05

data/HarshitMahara.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5855"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:HarshitMahara

CONTRIBUTING.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5871"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: multiple assignees and collaborators

data/amandamartin-dev/events/2023-05-23-smashingcon.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5857"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add SmashingCon event to profile

components/Button.js, components/Testimonials.js, pages/index.js, pages/map.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5875"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> dark mode fixes

data/anekemichael.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5838"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: anekemichael

data/ROUSE-prog.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5861"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ROUSE_prog

data/STIAANWOL.json
Updating existing profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5864"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update profile - STIAANWOL

data/nfa1.json
Added my name, bio and 2 social media links (Twitter & GitHub) to this new file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5873"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: nfa1

data/shivamsinghydv.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5879"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shivamsinghydv

data/Pallavi-33.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5886"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Pallavi-33

data/queenstack.json)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5533"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: queenstack

data/queenstack.json, data/queenstack.json)
Fix https://github.com/EddieHubCommunity/LinkFree/pull/5533
=> Fix queenstack

data/StarKnightt.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5892"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: StarKnightt

data/RohanSasne.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5905"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RohanSasne

data/rajaditya06.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5902"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rajaditya06

data/Manazsharma.json
Making my first open-source contribution
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5904"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Manazsharma

data/J-CODE07.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5903"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated the social links

pages/account/statistics.js, pages/changelog.js
Please verify the stats page since I wasn't able to check the links section in my local repo
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Darkmode stats and change log fixes

data/Chandraprakash-Darji.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Chandraprakash-Darji

data/surendhar-palanisamy.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5919"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: surendhar-palanisamy

data/Vikash-8090-Yadav.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5923"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Vikash-8090-Yadav

data/nabadev.json
Added my data on linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5924"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: nabadev

data/Parmesh119.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Parmesh119

data/streetstylecoder.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5939"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: streetstylecoder

data/BeyondEternal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5954"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: BeyondEternal

data/STIAANWOL.json
Fixes incorrect youtube icon 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5961"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> STIAANWOL: Profile Update - Fix youtube icon

data/Parmesh119.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5942"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Parmesh119 patch 1

.storybook/main.js, .storybook/manager.js, .storybook/preview.js, package-lock.json, package.json
With the addition of dark mode, this PR allows components to be tested in both light & dark mode in Storybook.
=> Add dark mode support to storybook

data/Ayaan49.json
1. Updated the bio.
2. Updated tags.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5955"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Ayaan49

components/navbar/Navbar.js
Hover action in the icons and logo of NavBar #5972
fixes #5972 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5974"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> issue #5972 Hover action in the icons and logo of NavBar solved

components/navbar/NavLink.js, components/navbar/Navbar.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5982"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: nav buttons and hover colours

data/thesobercoder.json
- Added JSON for creating my LinkFree profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: thesobercoder.json

data/wrmacdonald.json
Add wrmacdonald info
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5978"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: wrmacdonald

data/Shiva953.json
created Shiva953.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5997"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Shiva953

data/thesobercoder.json
- Updates to my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5987"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data: Update thesobercoder.json

components/mdx/BlockQuote.js, components/mdx/ComponentStyle.js, components/mdx/Strong.js
closes #5922 closes #5926 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6000"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed a, blockquote, strong tags in darkmode

components/mdx/BlockQuote.js, components/mdx/ComponentStyle.js, components/mdx/Strong.js
Tweaking code styling for PR https://github.com/EddieHubCommunity/LinkFree/pull/6000
=> Fix darkmode docs

components/modals/ProfilePreview.js
Reformatted code for PR https://github.com/EddieHubCommunity/LinkFree/pull/5932
=> Fix profile modal

data/zaid-hassan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5988"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Zaid hassan patch 1

data/Cshiva773.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Cshiva773

data/Younus-Saberi.json
Creating my first LinkFree page
- added tags
- added socials icon
- added link to my social
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5950"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Younus-Saberi

components/mdx/ComponentStyle.js, components/mdx/Li.js, components/user/UserProfile.js
fixes #6013 
earlier the code was like this
Now , I have made a separate file for Li component
If there are any suggestions and some other good way to do this, then you can tell me.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6023"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Li component moved to a separate file

data/roy2pushkar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6018"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:roy2pushkar

services/github/getLocationByUsername.js, services/profiles/findAllBasic.js, services/profiles/findOneByUsernameBasic.js, services/profiles/findOneByUsernameFull.js, services/profiles/getLocation.js, services/profiles/loadProfiles.js
=> fix: alias imports in services

pages/docs/contributing/maintainers.mdx
fixed typos from : mofifications tothe to  modification, to the
fixes #6001
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6031"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [DOCS] Typo in the maintainers page #6001 fixed 

components/layouts/BlankLayout.js, components/layouts/MultiLayout.js, package-lock.json, package.json, pages/_app.js
=> fix: google analytics

pages/docs/contributing/labels.mdx
=> fix: story points #5375

data/Akashbobade.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6045"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Akashbobade

data/JackCurragh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6044"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: github and Linkedin

data/thecentrons.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6053"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:thecentrons

data/ThomasCode92.json
Update my profile with milestone
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6055"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ThomasCode92

data/Olwiba.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6060"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Olwiba

data/abhishek-kumaraj.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6058"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: abhishek-kumaraj

data/tejas-gk.json
- Add my profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6065"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: tejas-gk

data/drhayes.json
Adding drhayes, that'sa me!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6070"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: drhayes

pages/playground.js
Closes #6025 
Border radius of both input boxes was different. Added missing class `rounded` to make it consistent.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6056"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix/6025: Make border radius consistent on playground page

data/Ramghimirecr7.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6071"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Ramghimirecr7 patch 1

data/dipankr.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6075"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added dipankr.json

data/Rufji.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6078"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Rufji

tests/map.spec.js
Closes #5767
This pull request adds a new test file for the map page. The tests check for the correct title, marker display after visiting profiles, and WCAG accessibility compliance.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> tests: add map page tests to populate location information (#5767)

data/asenseofpradhyu.json
Here is my first pull request for an open-source project. 
I created my linkfree link in this branch by following the quickstart guide.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6092"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:asenseofpradhyu

data/AkramAzouzi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AkramAzouzi

data/thecentrons.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: thecentrons

data/KaushikKundu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6109"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:KaushikKundu

data/OtomuolaAdebayo.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5882"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: OtomuolaAdebayo

data/vivek839.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5948"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vivek839

data/threesquaree.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5949"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: threesquaree

pages/docs/contributing/maintainers.mdx
closes #6124
https://linkfree.eddiehub.io/docs/contributing/maintainers in this page at last **Json package lock fix** section, updated the file name `package-lock.jsonz` to `package-lock.json`
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [DOCS] fixing documentation

data/sudarshan-doiphode.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changed My LinkedIn Profile

data/a60231023.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6125"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:a60231023

pages/docs/environments/local-development-docker-compose.mdx
- Remove the setting up environment step (2nd). As Compose file auto-generated the `.env` file. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6133"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update docker compose set-up

data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6139"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: grand-rick001 - Remove kaggle link

data/ajhughesdev.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6140"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ajhughesdev

data/luckyklyist.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6107"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:luckyklyist.json

data/Nanak360.json
add my data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Nanak Bandyopadhyay

pages/docs/contributing/automated-tests.mdx
Included dev env variations for running playwright tests
Example: Closes #6154 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update automated tests with dev env

data/anamika133m.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : anamika133m

data/sandramsc.json
fixed date in milestone
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6160"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sandramsc

data/Ramghimirecr7/events/2023-04-20-DevopsDay-Birmingham.json, pages/events.js
If an event has an invalid date, it breaks the whole event page, not it will be ignored
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: ignore bad event dates

.github/workflows/issue-lock.yml
fixes #6142
Example repo https://github.com/eddiejaoude/hello-world/issues
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: lock issue during triage #6142

.github/workflows/issue-lock.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: issue-lock ignore testimonial label

data/NimishKashyap.json
- Added profile for Nimish Kashyap
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:NimishKashyap

data/saikumarb12345.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:saikumarb12345

data/Shauryagulati.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Shauryagulati

data/Ratangulati.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Ratangulati patch 4

data/Nikhil202003.json
You'll  are doing a grate job. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Nikhil202003

data/RushikeshGandhmal.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: RushikeshGandhmal

data/Gauthamprasath.json
Profile update
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Gauthamprasath

data/Himanshuch8055.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add more links in Profile.

pages/account/statistics.js
Closes #5202 
Faded deleted links in statistics page 
**Before Changes**
Dark mode
Light mode
**After Changes**
Dark mode
Light mode
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6095"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: fade deleted links #5202

pages/account/statistics.js
https://github.com/EddieHubCommunity/LinkFree/pull/6095
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix dashboard old links

data/amanpreet-dev.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:amanpreet-dev

data/imvedanshmehra.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: imvedanshmehra

data/MonicaFidalgo.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:MonicaFidalgo

data/Sankhadip-Roy.json
Data for my LinkFree proflle.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sankhadip-Roy

data/vikaswakde.json
Thank you all, you all are doing awesome job, I would like my Linkfree profile to be updated. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vikaswakde

data/utkarshkrishna2004.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6237"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated the link for my Hashnode profile

data/bkpecho.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: bkpecho

data/sirine707.json
looking forward to contributing in such great project
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sirine707

data/AnanyaNagar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AnanyaNagar

data/chiomavera.json
-  Created my profile which entails: name, tags, bio, type, socials and links.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6243"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: chiomavera

data/Lebecode.json
Updated Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5957"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Data : Create Lebecode.json

data/Himanshuch8055.json
Correct URLs.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update Himanshuch8055.json (Correct URLs)

data/patrickloeber.json
Adds patrickloeber to Linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: patrickloeber

data/harshit-paneri.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : harshit-paneri

.github/workflows/vercel.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6267"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: vercel deploy on release

.github/ISSUE_TEMPLATE/other.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: issue template

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: release to include app version

.github/workflows/release.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: release to include app version config

data/ibilalkayy.json, data/ibilalkayy/events/2022-10-24-kubecon.json
Reverts EddieHubCommunity/LinkFree#6261
Invalid events json @ibilalkayy please only use 1 event per json file and javascript date format
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6291"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Revert "Added the KubeCon event in my profile I recently attended"

data/vaibhav-xt.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vaibhav-xt

data/sunilsinghrana.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6289"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: sunilsinghrana

data/ArslanYM.json
Added data to my Linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6295"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ArslanYM

data/CornelWeb3.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: CornelWeb3

data/sabrinalzbh.json
Just adding my profile. <3
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sabrinalzbh

.github/workflows/events.yml
If a user adds an event with bad data, it not only breaks their profile, but the events page.
This PR runs the playwright events tests on all profile events changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add test for events data change

package.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6318"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: package homepage

package-lock.json, package.json, pages/_app.js
fixes #6326 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: vercel analytics

.github/workflows/vercel.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6323"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: deploy data files on merge

data/thatmitchcanter.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:thatmitchcanter

data/KyloRen04.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6322"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added KyloRen04.json in data directory

data/WasiqB.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated profile with YouTube links

pages/docs/environments/environment-variables.mdx, pages/docs/environments/gitpod.mdx
Closes #6332 
added additional information abotu required setup for oauth app when working in gitpod
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added additional information for gitpod to authenticate for oauth

data/Deveesh-Shetty.json
Adds my profile in LinkFree Community :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6352"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ADD: Deveesh Shetty Profile

data/panthsolanki.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: PanthSolanki

components/Button.js
=> Added transition to buttons

data/Aniket1026.json
Updating the LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6348"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Aniket1026

data/Parthmandale.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Parthmandale

data/cheehieu.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: cheehieu

config/mongo.js, models/Link.js, models/Profile.js, models/ProfileStats.js
fixes #6345
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6368"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: mongo indexes #6345

models/Link.js, models/LinkStats.js, models/Stats.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6373"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: improve mongo indexes

pages/index.js
Closes #6333 
Cropped the images having extra right margin and also cropped navbar.
Before: 
After:
Please give me feedback of my work, thank you!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6370"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Screenshots on landing page need to be cropped (#6333)

data/akhil3shh.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6367"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:akhil3shh

data/Mayank-Sharma17.json
I love the community, you all are doing great.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Mayank-Sharma17

data/rupeshexe.json
Updated my linkfree profile.
Hey, can you tell me how I can add events on my linkfree profile?
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6395"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated rupeshexe.json

pages/account/no-profile.js, pages/account/statistics.js, pages/api/account/statistics.js, pages/api/users/[username]/index.js
unstable_getServerSession was renamed to getServerSession
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> remove unstable prefix from getServerSession

data/Amishapopli1.json, data/Chintu1509.json, data/Nikhilfy.json, data/fadebowaley.json, data/streetstylecoder.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6409"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: profiles with invalid property

data/anunayandkumar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6406"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: anunayandkumar

.github/workflows/issue-lock.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6413"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: improve issue lock message

data/Madanraj0519.json
You'll are doing a great job. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6410"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Madanraj0519.json

data/Soyeb01.json
Added my data for creating my account in LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6423"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Soyeb01

data/chirag4242.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6417"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: chirag4242

data/ElizabethOgbee.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6424"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ElizabethOgbee

data/Harshaljain04.json
Trial of making a Linktree.io page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Harshaljain04.json

data/HimanshiPrajapat.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6456"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create data: Himanshi Prajapat

data/Vansh41104.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6476"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Vansh41104.json

data/lebe24.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6497"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update : data profile features updates

data/imsp18.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:imsp18

DiggajUpadhyay.json
DiggajUpadhyay-patch-1
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:DiggajUpadhyay

kumarankit999.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6188"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: kumarankit999

data/rohitagr0310.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: rohitagr0310

data/prakashvishal93.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6511"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: prakashvishal93

data/shubhsh19.json
Added my data to LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shubhsh19

data/vishal126.json
- My change requires changes to the documentation.
- I have updated the documentation accordingly.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6514"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vishal126

data/AsmitKumar321.json
You'll are doing a great job. I would like my LinkFree profile to be updated
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AsmitKumar321

data/Akashraj161.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Akashraj161

docker-compose.yml, mongo-compose.yml
- Version the `mongo` image in `mongo-compose.yml`, otherwise, users may have different versions of the image, which could lead to errors.
- Update the `docker-compose.yml` to 6.0.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: update docker image version

data/Dhirendra17.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6533"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Dhirendra17

data/curi-adi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:curi-adi

data/Het-Joshi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update existing profile data Het-Joshi.json

pages/docs/environments/linkfree-cli.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: linkfree cli

data/mnik7044.json
Added my data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6546"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Mnik7044 patch 1

data/Eric-Obeng.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6567"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Eric obeng patch 2

data/amanpreet-dev/events/2023-05-01-hashnode-bootcamp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6564"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: amanpreet-dev

.github/workflows/events.yml
fixed failing GitHub Action https://github.com/EddieHubCommunity/LinkFree/actions/runs/4860204691/jobs/8671482953
=> fix: events gh action

data/xp-vit.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6583"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Add Viktar Patotski aka xp-vit

data/gekkowrld.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6585"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gekkowrld

README.md
=> docs: GitHub Accelerator announcement

data/xp-vit.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6593"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Update xp-vit profile

components/Button.js, pages/api/auth/[...nextauth].js, pages/auth/signin.js
fixed PR https://github.com/EddieHubCommunity/LinkFree/pull/6016
**light mode**
**dark mode**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6578"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix login page

pages/changelog.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: changelog custom login page

data/SanskritiGupta05.json
Excited to make this open-source contribution via EddieHub Community. Great Project!!!
=> data: SanskritiGupta05

data/pranshuj73.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6611"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: pranshuj73

components/GitHubAccelerator.js, components/Testimonials.js, pages/index.js
=> GitHub accelerator

data/Webdevava.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Webdevava

data/Panth1823.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Panth1823

data/Sid-Lais.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Sid-Lais

.github/workflows/deploy.yml
Since we are currently not using the docker build of LinkFree for deployment, this PR will stop building it on each release
=> stop running deploy on releases

data/priyankarpal/events/2023-05-07-GoogleCloudCommunityDays.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Create 2023-05-07-GoogleCloudCommunityDays.json

components/user/UserLink.js
Closes #6609
clicks states is no longer required, as the clicks are not longer displayed on the profile page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: remove clicks states (#6609)

components/map/Map.js
Closes #5867
The issue gets resolved if we remove the Highlighted part as shown in the image.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix duplicate in map

data/C0dewordSky.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6651"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: C0dewordSky

data/HassanTanveer.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6645"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: HassanTanveer

data/sarthakroy2002.json
Update my data in LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Update sarthakroy2002 data

data/SarthakNegi.json, data/sarthaksarthak9.json
You Guys are doing amazing work!! keep it up.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:SarthakNegi

bakar-dev.json, data/bakar-dev.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6653"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: bakar-dev

data/zheroin.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6654"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:zheroin

data/OmkarBorhade98.json
Added my LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6641"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: OmkarBorhade98 LinkFree Profile

components/PageHead.js
closes #6657 
* remove if statement
* add default values for props
* update components/PageHead.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6670"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Remove if statement & add default values for props

components/navbar/NavLink.js
=> fix: highlight nav page in lightmode

data/SAD0XER.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6679"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SAD0XER

data/ismail-benlaredj.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6682"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ismail-benlaredj

data/mpotane.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6685"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> DATA:MPOTANE change bio

data/Bikramjit21.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6686"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Bikramjit21

data/RohanSasne.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6688"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Rohan Sasne

data/oyepriyansh.json
removing some links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6689"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: update oyepriyansh

components/Button.js, components/Footer.js, pages/premium.js, pages/terms.js, tests/events.spec.js, tests/icon.spec.js, tests/playground.spec.js, tests/search.spec.js
changes and fixes talked in #6637
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6687"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Footer premium terms fix

pages/docs/environments/local-with-atlas.mdx, pages/docs/index.js
Closes #6354 
This PR addresses the issue of the missing MongoDB Atlas setup guide for LinkFree local development.
Adds a new page for the MongoDB Atlas setup guide for LinkFree local development.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6690"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: update MongoDB Atlas setup guide for local development (#6354)

components/Button.js, components/Footer.js, components/GitHubAccelerator.js, pages/changelog.js, pages/premium.js, pages/terms.js, tests/events.spec.js, tests/icon.spec.js, tests/playground.spec.js, tests/search.spec.js
**FOOTER**
**PREMIUM PAGE**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6637"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: footer, premium, terms

pages/docs/contributing/reviewers.mdx, pages/docs/index.js, pages/docs/maintainers.mdx
=> docs: maintainers guide

data/DrVickie8.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6708"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: DrVickie8.json

pages/account/statistics.js
Fixes PR https://github.com/EddieHubCommunity/LinkFree/pull/6596
=> fix: add a link to your profile in the account tab

data/Skyhero-alt.json, package-lock.json
Fixing PR https://github.com/EddieHubCommunity/LinkFree/pull/6668
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6716"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: changed the user 'Skyhero-admin' to 'Skyhero-alt' (#6668)

data/SurajPratap10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SurajPratap10 (milestone update)

data/PratyayDhond.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6712"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added userdata file to 'data:PratyayDhond.json'

data/Harsh2920.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Harsh2920

data/PratyayDhond.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Data:PratyayDhond.json

pages/docs/maintainers.mdx
=> docs: fix maintainers channel

bhavyamehta4439.json, bhavyamehta4439.json{   "name": "Sara Jaoude",   "type": "personal",   "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado" }
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6492"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bhavya Mehta

data/avionmission.json
Added my data to data.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6725"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: avionmission.json

data/Tanvi-shah02.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6736"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed issues mentioned

components/Footer.js, components/navbar/Navbar.js, pages/roadmap.js, tailwind.config.js
closes #6734 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: roadmap

data/ujjwalkirti.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6742"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:ujjwalkirti

data/rep-pierce.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data rep-pierce

data/1Shubham7.json
You people are awesome. Love the work you do.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> 1 shubham7 linkfree profile

data/bishalbera.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6755"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: bishalbera

components/GitHubAccelerator.js, components/navbar/Navbar.js, pages/account/no-profile.js, pages/roadmap.js
fixes #6759 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6760"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: links to use component

package-lock.json, package.json
fix PR https://github.com/EddieHubCommunity/LinkFree/pull/6707
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix postinstall script

data/manojsai1.json, manojsai1.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: manojsai1

data/kirtankp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6803"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:kirtankp.json

pages/docs/community-resources.mdx
Added links to my blog articles that might be helpful for open source newbies and those who want to learn about LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: added blog resources

data/adisuyash.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6768"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: adisuyash

data/adreeja06.json
- [x ] My change requires changes to the documentation.
- [x ] I have updated the documentation accordingly.
- [x
] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6764"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: adreeja06

data/avionmission.json
Updated my data.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: avionmission

data/KQuiggins.json
- Update LinkFree Bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: KQuiggins

data/mnvsk97.json
Adds `mnvsk97` profile to the LinkFree Database
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: mnvsk97.json

pages/roadmap.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6822"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: internal/external roadmap links

package-lock.json, package.json, pages/_app.js
closes #6747 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Removed google analytics

data/usmangt.json
An excellent Open Source app I need to start for my personal work instead using Linktree. I really appreciate your hard work on this. Great job!! 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6837"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: usmangt

data/Chandraprakash-Darji.json
No issue fixed just added testimonial username
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6847"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add testimonial username to my profile

data/kdteraiya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6849"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: kdteraiya

data/Shreypatel911.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6856"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Shreypatel911

pages/playground.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6863"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: playground footer info

pages/404.js, pages/[username].js, tests/404.spec.js
fix PR https://github.com/EddieHubCommunity/LinkFree/pull/6814 and closes #6721 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6865"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix PR custom error page 404

data/thehashmap.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6868"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Thehashmap patch 1

data/shoebilyas123.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: shoebilyas123

data/Abheekrishna.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6878"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Abhee Krishna

data/CBID2.json
I updated my Milestones section
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6883"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [feat] updated Milestones section

data/hebypaul.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6898"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: hebypaul

data/gouravmohanty7070.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gouravmohanty7070

pages/docs/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: contributing style guide location

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6907"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: small change to test code owners

data/kiyoshi-87.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6903"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: kiyoshi-87

pages/docs/docs-style-guide.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6910"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: updated style guide

data/praveenpy273.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6917"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Praveenpy273 patch 2

data/Deerah1234.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6918"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Deerah1234

data/GrahamTheDevRel.json
Added "loftwah" to testimonials section
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: GrahamTheDevRel

components/mdx/Li.js
Closes #6709
Removed "break-all"
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6923"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: word-wrap

data/Lalman888.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6926"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Lalman888

data/munish-on-git.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6927"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:munish-on-git.json

data/vjsinsights.json
Just creating my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6928"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Vjsinsights patch 1

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6932"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: removed competitor comparison

data/kirtankp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added Tags and Social icons

data/SagarSharma2809.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SagarSharma2809

data/yashhhh04.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6949"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: yashhhh04

pages/docs/quickstart.mdx
Fixes #6911  
Changed the wording of point number 7 of quickstart documentation for better clarity.
**Before**
**After**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6935"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: quickstart filename capitalisation not clear

components/IconCard.js, components/Notification.js, pages/playground.js
Closes #6681 
1) Moved Notification logic out of IconCard.js to the Notification.js
2) Replaced Alert component uses in playground.js with Notification component
Behavior on Icons page remains same:
Error scenario in playground page show error notification:
Success scenario in playground page show success notification:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6938"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Toast Error on playground page

components/IconCard.js, components/Notification.js, pages/playground.js
Fix formatting of PR https://github.com/EddieHubCommunity/LinkFree/pull/6938
closes #6681 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6963"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Notifications on playground and icons page

data/vishnu-mouli-102408.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6966"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data updated : vishnu-mouli-102408.json

data/sajjadrahman56.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6974"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> sajjadrahman56-patch-01

data/kirtankp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6972"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added new Tag, divided links based on the type and added project

data/wasimreja.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: wasimreja

config/mongo.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/6885
closes #6885 
* refined the mongo config file
* minor changes for #6855
---------
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6977"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: mongo config file (#6885)

pages/search.js
Closes #6824 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6846"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6960"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: display random profiles on search page

data/gowthae.json
creating new profile : gowthae
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6973"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: gowthae

data/alamzia23.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6981"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: alamzia23

pages/search.js, tests/icon.spec.js, tests/search.spec.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/6960
closes #6824 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6979"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: display random profiles on search page (#6960)

data/ToshitaSingh.json
Created my new profile on LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6986"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ToshitaSingh

.github/workflows/vercel.yml, data/eddiejaoude.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: gh action for load data

.github/workflows/publish-ghcr.yml
- Removed remove artifact and k8s config
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7004"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: remove artifact and k8s config

data/kirtankp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6990"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> removed duplicate tags

data/Rimpyyadav.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7000"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : Rimpyyadav

data/jfmartinz.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7007"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: jfmartinz.json

data/harmeetsingh11.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7008"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: harmeetsingh11

data/AliMora83.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Ali mora83 patch 3

data/NonsoBarn.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7009"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:NonsoBarn

data/vishnuhari17.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7023"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated the file name as per the naming convention

data/NonsoBarn.json, data/vishnuhari17.json
- removed `type` key from recently merged profiles, as it's no longer being used.
=> fix: remove type key from profile json

pages/account/statistics.js, pages/api/account/statistics.js
=> Convert fetch to function call on account stats page

.github/workflows/build.yml
Add the following files to list that runs test suite
- tailwind.config.js
- package.json
- next.config.mjs
=> run test suite on changes to config files

data/Dheerajjha451.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7050"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Dheerajjha451

data/Saikatssd.json
Please merge my pull request. This will allow me to proceed with contributing and collaborating with LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7058"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:Saikatssd

data/piaseckijulian.json, piaseckijulian.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7061"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Piaseckijulian patch 2

models/Profile.js, pages/api/events.js, pages/api/system/reload.js, pages/api/users/[username]/index.js, pages/api/users/index.js
Profiles in DB with no json file should be disabled unless they are using the forms (`source` property)
closes #7066
=> fix: enable/disable profiles #7066

pages/api/system/reload.js
=> fix: removed debug code

pages/docs/environments/local-development.mdx
=> docs: how to load the data in dev mode

components/user/UserPage.js
Closes #6951 
* remove multiple `tabs` find calls.
* use optional chaining (`?.`) to access `current` property.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7055"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: remove extra tabs find check from user page

data/praduman8435.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7083"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: praduman8435

data/Rohanfulzele.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7085"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Rohanfulzele

pages/docs/quickstart.mdx
=> docs: updated example profiles

pages/api/system/reload.js
fixes #7100 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: reload duplicate socials

pages/api/system/reload.js
=> fix: reload property exists

data/poorvijn.json
Added a new link to my Github profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: poorvijn

data/Chandraprakash-Darji.json
_No issues fixed_
Update discord link in bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7099"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update discord link in profile

components/GitHubAccelerator.js
#7033
I have changed the heading to a paragraph and nothing else I have changed.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bug fix change heading to Paragraph 

data/chaddyc.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: chaddyc

data/amandamartin-dev.json, data/amandamartin-dev/events/2023-05-23-smashingcon.json, data/amandamartin-dev/events/2023-05-31-render-atl.json, data/amandamartin-dev/events/2023-08-04-beer-city-code.json
Updates to personal profile including links and new events
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7114"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Amanda profile updates

data/Emmanuel-Adom.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: Emmanuel-Adom

components/user/UserMilestones.js
Closes #5945 
1) Used javascript sort method to sort milestones based on date
2) Valid dates will be sorted in descending order
3) While comparing invalid date with invalid date or comparing invalid date with valid date, both the values will be considered equal and hence order will not be changed.
4) Let me know if we require to add invalid dates in the beginning or at end. It can be easily done but most of the profiles are already having them in order and few profiles are using combination of both valid/invalid dates and if we make invalid dates at beginning/end then it will change the order provided by user.
5) try catch is not required as it will not throw exception instead it will treat it as NaN and will work as mentioned in point no. 3
Before ordering:
After ordering:
<a …
=> feat: order milestones descending (5945)

data/VikeCode.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:VikeCode

data/itsaakashpatel.json
- Adding a new profile to LinkFree. Let's geek out with open source community 🥳
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7161"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: itsaakashpatel

data/HiLakshya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: HiLakshya

components/Tag.js, pages/search.js
[BUG] The tags on the search page should be buttons #7037
- Tags on the search page added as div now replaced with button
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [BUG] fix added buttons

data/SaarthakMaini.json
Add Testimonial
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Testimonial

pages/docs/environments/gitpod.mdx
added a note about how to load the data for dev locally - no open issue (convo in discord)
=> Update gitpod docs with local data load instruction

components/navbar/Navbar.js
[BUG] Github navbar logo needs more padding and less margin. (Especially when tabbing) 
closes #7034
- Adds padding to Github icon in Navbar.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7097"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [BUG] Added padding to Github icon

components/navbar/Navbar.js
Fixed PR https://github.com/EddieHubCommunity/LinkFree/pull/7097
=> GitHub icon padding in main navbar 

data/ONYEDI.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: ONYEDI

data/markodenic.json
Woohoo! Added my links!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:markodenic

data/SxxAq.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:SxxAq

data/ujjwalkirti.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding more details in ujjwalkirti.json

pages/docs/index.js
=> making documentation consistent

data/joshjgomes.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: joshjgomes

data/EmaniAditya.json
Hello there, My name is Aditya Reddy. I am creating a new account on LinkFree.
I have checked my json and it's a valid one.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: EmaniAditya

data/Pritam1136.json
**Add Pritam1136.json**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7212"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Pritam1136.json

config/app.json, pages/search.js
Adding the random users to the search page cause mobile performance issues.
This PR will generate the random users list during isr & reduce the time between isr builds.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix search page load on mobile

data/raviraj-github.json
Adding details to be published in LinkFree.
GitHub User: raviraj-github
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:raviraj-github

README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> loading data into the db added to readme 

data/vrishti29.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: vrishti29

components/event/EventCard.js, components/event/EventKey.js, components/user/UserEvents.js, pages/api/events.js, pages/api/users/[username]/index.js, pages/events.js
Because events requires a lot of date manipulation, this causes hydration errors.
In order to fix this, most of the date manipulation is done on the server.
useEffect is used on the client side to fix the shown dates to the local time zone.
=> Fix event date hydration issues

data/ibilalkayy.json
I updated the bio and the milestone section
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> updated the bio and the milestone section

data/jugaaadd.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7250"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: jugaaadd

data/runelk.json
This PR will add a very nice and friendly JSON file that I made following the [quickstart](https://linkfree.io/docs/quickstart).
Thank you for reviewing my json file. Have a fantastic day or night, wherever you are!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:runelk.json

data/aarpardev.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7255"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: aarpardev

data/PriyansuMaurya.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7268"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data : PriyansuMaurya

data/AndrewJesse.json
New profile request. Thank you!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AndrewJesse

data/SoNiC-HeRE.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: SoNiC-HeRE

pages/docs/how-to-guides/events.mdx
Example: Closes #7139
If I did something wrong, please guide me through that. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add the for example to 2nd line and remove the blank line and ;

pages/docs/how-to-guides/events.mdx
fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7234
=> Fix pr 7234 events doc

data/ishxn69.json
Added my details such as name, bio, icons, tags, and social links. Validated JSON on JSON Lint.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7285"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Created ishxn69.json; added data for my LinkFree page.

data/yashrajjain726.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Profile Added - Yashraj Jain [yashrajjain726]

pages/api/statistics/totals.js
Closes #7284 
Changed total.js to load app stats from Database instead of counting the jsons.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7294"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> refactored total.js to load app stats from DB

data/chaitanyakatore.json
thanks for providing amazing platform for open source community it's my first open source contribution
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7293"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: chaitanyakatore

data/AbhayaShankar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data: AbhayaShankar

data/heyrishabh13.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7299"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> data:heyrishabh13

data/pankajktech.json
Updated My Links and Added Socials
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Patch 2: pankajktech.json
