- data/CYBWEBALI.json
Created profile by adding json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: CYBWEBALI

- data/rishu6263.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data :rishu6263

- data/Rahulbaran.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7321"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update data of my profile

- data/homelyseven250.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: homelyseven250

- data/katzjeff.json
Please review my created profile of LinkFree .
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7331"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: katzjeff

- data/l-legren.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: l-legren

- data/Amit-45.json
Added links to other socials
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:Amit-45

- data/Jacques-Murray.json
Created my LinkFree profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7338"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:Jacques-Murray

- data/SaumyaBhushan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:SaumyaBhushan

- pages/docs/environments/gitpod.mdx
- pages/docs/environments/local-development.mdx
- pages/docs/quickstart.mdx
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7074
> Docs alert boxes

- data/bansaltushar014.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:bansaltushar014

- data/shreyas0924.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data : shreyas0924

- pages/index.js
closes #7297
BEFORE
AFTER
increases the font size without affecting the mobile view
also opened an issue for color contrast for better visibility and accessibility 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7367"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> increses the font size

- pages/api/events.js
Closes #7341
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7372"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix the TODOs of api/event.js #7341

- data/SudarshanSirsi.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7370"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:SudarshanSirsi

- data/rudra016.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: rudra016

- data/Alkaison.json
- Only updated the JSON code under `alkaison.json` file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7382"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update: 'Alkaison' profile details. Its my profile.

- data/aarushiksk.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7391"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: aarushiksk

- components/user/UserMilestone.js
- pages/docs/how-to-guides/events.mdx
fixes #7047
_changed the multicolor lines to light-gray_
_Before_
_After_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7395"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a
>
> Update UserMilestone.js line color from multicolor to light gray.

- components/user/UserMilestones.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7395
[ ] - Not correct; marked as **not** done
-->
> fix: milestone border color

- data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: grand-rick001 - Add milestone

- data/preethi1915.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: preethi1915.json

- data/mallyapravin.json
Added my profile json to LinkFree.
My PR is valid json.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7421"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: mallyapravin

- data/SaraviaMartin.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7423"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: SaraviaMartin

- pages/index.js
closes #7373 
changes the font size of feature description
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7425"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> changes the font size of future description

- components/map/Map.js
Closes #7358 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7436"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Changed Scroll Wheel Zoom

- components/user/UserProfile.js
- tests/profile.spec.js
Closes #7340 
1. Go to a profile
2. Select any tag.
3. Try de-selecting it and it should work.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7384"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix: Cannot de-select tag/skill in search page when coming from profile.

- data/BatuhanOnge.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7453"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: BatuhanOnge

- data/MohdTanzeel.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7455"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: MohdTanzeel

- data/SiddheshBangar.json
Updated the content for SiddheshBangar.json file 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7457"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update : SiddheshBangar.json

- data/Devansh-Singh-Parmar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Devansh-Singh-Parmar

- pages/docs/quickstart.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: quickstart copy non json

- pages/search.js
Closes #6872 
[video preview](https://imgur.com/a/VdW8o3S)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7392"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve user search experience #6872

- data/chaitali-khangar.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: chaitali-khangar

- components/user/UserTabs.js
Fix PR #7473
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: profile tab font size #7049

- components/user/UserProfile.js
- tests/profile.spec.js
Example: Closes #7463 
- Remove the Link tag and add useRourter hook to handle navigation.
- Updated the test to use button instead of link .
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7475"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: double tabbable tags

- Omcodes23.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Data: Omcodes23

- .github/workflows/issue-lock-unlock.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: gh action lock/unlock

- pages/[username].js
- pages/index.js
Closes #7464 
- Shifted the `position:absolute` to `<a/>` with a few other styles
- Added `focus-visible` related styles
**How it looks now**
See the floating buttons at the bottom right corner of your screen
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: floating button focus issue

- models/Account.js
- models/Link.js
- models/LinkStats.js
- models/Profile.js
- models/ProfileStats.js
- models/Session.js
- models/Stats.js
- models/User.js
- models/VerificationToken.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Timestamps added to all db models

- .github/workflows/vercel.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: deployment trigger for releases

- data/Soumava-221B.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7500"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Soumava-221B

- data/Soham-glitch.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Soham-glitch

- .github/workflows/release.yml
- .github/workflows/vercel.yml
Uses the correct token in the release action to allow triggering other actions on release
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix release action token

- .github/workflows/build.yml
- models/Account.js
- models/Link.js
- models/LinkStats.js
- models/Profile.js
- models/ProfileStats.js
- models/Session.js
- models/Stats.js
- models/User.js
- models/VerificationToken.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7503
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: timestamps to all db models (#7503)

- data/arshidte.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7523"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: arshidte

- data/jfmartinz.json
Updated existing profile in linkfree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7539"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: jfmartinz

- data/thisisdishang.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Thisisdishang patch 1

- data/zaktech96.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: zaktech96

- data/Tanmay-Joshi73.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7545"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:Tanmay-Joshi73

- data/helloakash1701.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7546"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: helloakash1701

- data/Sugamgoel28.json
Thank you for this wonderful learning opportunity for beginners
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Sugam Goel

- data/AbrarAlHasan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:AbrarAlHasan.json

- data/Sugamgoel28.json
- data/thisisdishang.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7551"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Sugamgoel28 patch 2

- data/jegrami.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7566"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: jegrami

- pages/api/events.js
Recent PRs do not match our formatting style
> fix: formatting

- components/user/UserLink.js
Closes #7042  -->
Could you please suggest an alternative background color for both light and dark themes? I have currently used a secondary-low color, as I find it more prominent than other colors. I would appreciate any suggestions you may have. Thank you!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: Profile page links shows background color on hover

- data/Rohit312001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7572"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Rohit312001

- data/programmer765.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:programmer765

- data/ChavvaNarayana.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: ChavvaNarayana

- data/CBID2.json
I added another achievement to the Milestones section.
I previewed my profile's JSON file on Playground and the new milestone did not show(see the above screenshot for reference), so assistance on this would be great! :) 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7587"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: add new milestone

- data/CBID2.json
I fixed the date of my new milestone 
Hi @SaraJaoude! I just realized that I had an error in my recent pull request, so I created a new one. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7589"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: revise date of new milestone

- data/Pradumnasaraf/testimonials/iam-Rps.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Testimonial for 'Pradumnasaraf' by 'iam-Rps'

- pages/[username].js
Closes issue #7604
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7609"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> updated profile link to preview correctly on share

- data/austincomer.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: austincomer

- data/vigdisha.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7603"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: vigdisha

- components/PageHead.js
- pages/[username].js
> fix: social og description

- data/DevasyaRajguru.json
- data/devasyarajguu.json
Added name and social media handles to get my LinkFree account
None
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7578"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:DevasyaRajguru

- data/iam-Rps.json
Testimonial is updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7596"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: iam-Rps

- data/Pravesh-Sudha.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Pravesh-Sudha 

- data/BDFL669.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7626"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: BDFL669.json

- data/shadrack-mwelwa.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: shadrack-mwelwa

- data/nabin47.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: nabin47

- data/CBID2.json
I added my freeCodeCamp Writer profile to My Links section
Since I don't own freeCodeCamp's news site, do you recommend that I label it "Blogs Primary" or something else?  I'm open to suggestions. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: CBID2

- data/kunal00000.json
Added Milestones to my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7641"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  updated my profile with milestone

- data/Shiva953.json
Edited Shiva953.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7646"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Shiva953.json

- data/Franklyn883.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7656"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:Franklyn883

- components/Alert.js
Closes #7623 
1. removed animate-pulse from case "warning " div in components/alert.js , to remove animation in notes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7639"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> remove animate-pulse from component/Alert.js

- components/Alert.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7639
> fix: remove alert animation

- data/yassineatik.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:yassineatik

- data/Luwore.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7675"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> New branch

- data/shubhamku044.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: shubhamku044

- data/joelchully.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: joelchully

- components/Footer.js
close #7678 
solve the issue of overlapping in footer.
Please review it.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7702"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fixed issue #7678

- components/form/Select.js
- pages/account/statistics.js
Dark/light mode for `manage-forms` https://github.com/EddieHubCommunity/LinkFree/issues/5575
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7699"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add theme colours to forms

- data/varad-kulkarni172.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: varad-kulkarni172

- data/sandramsc.json
- updated tags
- added twitter blog account
- updated links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7706"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: sandramsc.json

- data/Naresh-chandanbatve.json
[x] - Added data for Naresh Chandanbatve
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7709"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added Naresh Chandanbatve

- components/Modal.js
Closes #7637
Changes was proposed to fix modal design issue and make it scrollable in playground page.
@eddiejaoude as you suggested to make full modal scrollable in PR number: #7669. Here is updated PR.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7712"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Modal bug fixed in playground page

- components/Newsletter.js
Closes #7591
Changes was proposed that the news letter should be center in small device.
Here is my new pr with more cleaner way.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed design issue in newsLetter

- data/vishnu-31.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: vishnu-31

- data/one2code.json
Linkfree profile submission for one2code's bio & links
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7726"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: one2code

- pages/docs/how-to-guides/links.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7730"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix docs for links

- .github/workflows/vercel.yml
Add file count to production vercel deploy to compare with forms branch
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7736"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add file count diagnostics to vercel deploy

- data/Viveksati5143.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7739"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Viveksati5143

- data/shreyanshs31.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7740"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:shreyanshs31

- data/Pravesh-Sudha.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Pravesh-Sudha.json

- data/DaminiM-23.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7745"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data : DaminiM-23

- components/user/UserProfile.js
The UserProfile component was using `useRouter` from `next/navigation`
This is designed for use with `/app` and broke Storybook.
Switching this import to `next/router` fixes Storybook.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7757"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix UserPage in Storybook

- data/MamunVerse.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7756"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: MamunVerse

- pages/docs/quickstart.mdx
Closes #7476 
In quickstart guide which is inside docs, the link to LinkFree repo open in same page. It is made to open in new tab and this will help user to follow the guide and contribute to their profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix:linkfree repo open in new link

- package-lock.json
- package.json
Update LinkFree CLI version to 2.5.1
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: update Linkfree CLI version

- data/tdogubo.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: tdogubo

- data/VarunJoshi10.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7772"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: VarunJoshi10

- pages/[username].js
- pages/changelog.js
- pages/index.js
- pages/newsletter.js
- pages/playground.js
- pages/premium.js
- pages/roadmap.js
- pages/terms.js
- stories/components/user/UserMilestone.stories.js
Discussed in live stream and GitHub Discussion https://github.com/EddieHubCommunity/LinkFree/discussions/7770
- `text-gray-400` (any color or value after the color is incorrect way and should be using text-primary-medium )
- same with` bg-white` (using the color is incorrect)
- the available colors in our project are here in the **tailwind config** under colors https://github.com/EddieHubCommunity/LinkFree/blob/main/tailwind.config.js 
-  we should not use any of these text-[color] or text-[color]-[value] or with bg also like bg-[color] or bg-[color]-[value]
-------------------------------------------------------------------------------------
**Pages changed**:
username.js
changelog.js
index.js
newsletter.js
playground.js
premium.js
roadmap.js
terms.js
<a …
> Manage forms - pages to tailwind config colors

- pages/search.js
- tests/search.spec.js
fixes #7585
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7790"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  FEATURE] Search to display 10 random profiles this is issue is relat… #7585

- pages/search.js
Closes #7751 
1 Add space after the comma
2 Check if there is no keyword between 2 commas and removes the second comma
3 Check if the input starts with comma and removes it
After change:
https://github.com/EddieHubCommunity/LinkFree/assets/128586019/a7762ec8-c171-4283-83c7-85b30ff0b1f4
> Improved readability of search input #7751

- data/arifaisal123.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7785"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: arifaisal123

- data/LVSMix.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7797"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: LVSMix

- pages/docs/contributing/automated-tests.mdx
Closes #7766 
Completed the command to run docker for mongo only in order to run automated tests
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7804"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: command to start docker for mongo for testing

- data/priyanshugarg1010.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7806"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: priyanshugarg1010

- components/event/EventTabs.js
fixes #7792 
Before:-
Now:-
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7803"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: fixed the color of EventTab on Dark Mode

- data/KingshukBansal.json
I am making a profile in LinkFree
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: KingshukBansal

- data/thisisdishang.json
- diksha1159.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Profile Creation 

- data/gethushan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7816"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Data: gethushan

- data/vamsikurimeti.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7825"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Vamsikurimeti patch 2

- data/LinuxGamer.json
- Update profile description to a newer one.
- Update Fediverse link to my new main account.
- Add new milestone.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7828"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update links, tags, description and milestones on my Profile

- data/Swapnil-11-04-01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7830"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Swapnil-11-04-01

- .github/workflows/vercel-preview.yml
- pages/account/manage/link/[[...data]].js
- pages/api/account/manage/link/[[...data]].js
> feat: delete links and related data

- data/hzpeng57.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: hzpeng57

- data/BurakTaner.json
I changed my Github username and ı should change my LinkFree names to in my data file. 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7836"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: update Ertan222 to BurakTaner

- data/grand-rick001/events/2023-06-28-developer-workflows-and-trends-students-can-use.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7848"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: grand-rick001 - edit event

- data/aj11anuj.json
PR for creating my LinkFree profile
Added my data, required for my profile
I think there is no need of it
Have a nice day :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7849"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: aj11anuj.json

- README.md
- components/Footer.js
- pages/docs/environments/gitpod.mdx
- pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7862"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix quickstart links

- pages/events.js
> fix: events help link

- components/ConfirmDialog.js
> fix: dark mode for confirm dialog

- pages/docs/quickstart-json.mdx
- remove the Github json examples from the inspiration section of quickstart json. 
- Add a link to the full profile example.
> fix: modify inspiration section in quickstart json

- data/kirtankp.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7879"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Todo project added

- .github/config/reviewpad.yml
> fix: profile auto label

- pages/account/no-profile.js
> fix: dark mode for no profile

- data.jainam-r.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7881"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: jainam-r

- .github/workflows/vercel-preview.yml
- config/logger.js
Revert PR as broke `production` (note: tested locally in prod mode and worked fine, needs more investigation)
https://github.com/EddieHubCommunity/LinkFree/pull/7562
> Revert logger

- components/user/UserMini.js
- pages/index.js
> fix: random profile text

- pages/api/profiles/[username]/index.js
Error
```
{"level":30,"time":1688220066883,"pid":8,"hostname":"169.254.49.181","msg":"profile location not expired for username: loftwah"}
TypeError: getProfile.events is not iterable
at getUserApi (/var/task/.next/server/chunks/3526.js:215:36)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async getServerSideProps (/var/task/.next/server/pages/[username].js:119:33) {
page: '/en/loftwah'
}
RequestId: 4f262684-10e0-48e9-8868-c410f292a21f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
> fix: profiles with no events

- pages/docs/index.js
> docs: fix broken link

- data/Parvej2001.json
Created my linkfree portfolio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7910"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Parvej2001

- data/KrownWealth.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7925"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:KrownWealth

- pages/docs/environments/environment-variables.mdx
> docs: fix missing next auth url

- data/paaggeli.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7930"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: paaggeli

- pages/account/manage/testimonials.js
> fix: manage testimonial dark mode

- docker-compose.yml
- next.config.mjs
… docker compose up
Closes #7102 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix:7102 - Added config to enable hot reload when project started with docker compose up

- pages/account/manage/profile.js
> fix: responsive background color for mange profile

- data/nikitakoselev.json
nikitakoselev-patch-1
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7946"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: nikitakoselev

- data/Collins-Omariba.json
- tags and bio update
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7954"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update profile Collins-Omariba.json

- pages/docs/index.js
> fix: popular docs link

- pages/account/manage/profile.js
- pages/account/statistics.js
Closes #7875
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Bug fix]: move tab nav to the top #7875

- pages/api/system/reload.js
> Handle milestones w/ non-Date info in date field

- data/Alexxanderr20.json
added data: Alexxanderr20
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7919"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Alexxanderr20

- components/Testimonials.js
Closes #7860 
Fixes margin issue of testimonials section in homeoage.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7947"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: margin issue in homepage

- data/vamsikurimeti.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7990"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Update vamsikurimeti.json

- data/danishhansari.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7992"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added my Data

- pages/docs/contributing/reviewers.mdx
- pages/docs/environments/gitpod.mdx
- pages/docs/full-profile-example.mdx
- pages/docs/how-to-guides/bio-json.mdx
- pages/docs/how-to-guides/events-json.mdx
- pages/docs/how-to-guides/links-json.mdx
- pages/docs/how-to-guides/milestones-json.mdx
- pages/docs/how-to-guides/socials-shortcuts-json.mdx
- pages/docs/how-to-guides/tags-json.mdx
- pages/docs/profile-tips.mdx
- fix all the broken 404 links in the `json` docs.
- remove the color key from the docs, since it is no longer required.
- Changes the old domain to linkfree.io in `reviewer` docs.
> fix: improve docs & broken links

- components/user/UserLink.js
- components/user/UserLinks.js
- pages/account/manage/links.js
- pages/api/account/manage/links.js
- pages/api/profiles/[username]/index.js
> fix: sort links when managing

- pages/changelog.js
> fix: user changelog update

- pages/account/manage/testimonials.js
Closes #7920 
Added an indicator when in reorder mode when managing testimonials
[Issue#7920.webm](https://github.com/EddieHubCommunity/LinkFree/assets/83803257/48568501-98a3-4aa6-8f81-700b9dda626c)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7994"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Closes #7920 

- pages/account/manage/event/[[...data]].js
- pages/account/manage/milestone/[[...data]].js
The input fields had values instead of placeholders , I have deleted these values and replace them with placeHolders , without affecting the functionality of changing their value
Closes #7962 
Replace the input values with placeholders in adding [Events](https://linkfree.io/account/manage/events) / [Milestones](https://linkfree.io/account/manage/milestones) Sections
**Before**:
**After**  : 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7985"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix : Inputs Values Bug #7962

- pages/account/manage/event/[[...data]].js
- pages/account/manage/milestone/[[...data]].js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7985
> Fix pr 7985 for default form values

- data/Kishore-r-77.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7991"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Kishore-r-77

- data/itssouray.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:itssouray

- pages/docs/environments/environment-variables.mdx
> docs: alert to restart for envar changes

- components/user/UserProfile.js
- pages/api/account/manage/profile.js
If no tags then 1 empty tag appears, but now empty tags are removed
BEFORE
> fix: no tags on profile then hide

- pages/roadmap.js
> fix: roadmap responsive wit badge

- pages/account/manage/event/[[...data]].js
- pages/account/manage/link/[[...data]].js
- pages/account/manage/links.js
- pages/account/manage/milestone/[[...data]].js
- pages/account/manage/profile.js
- pages/account/manage/testimonials.js
> fix: use zod config

- data/Mohd-Wamid.json
Added Mohd Wamid
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8037"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Mohd Wamid

- data/Viveksati5143/events/2023-06-17-first-in-person-meetup.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: added events to Viveksati5143

- pages/newsletter.js
Closes #7693
- Showing the NewsLetter form below the text in mobile view for NewsLetter page.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7976"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [fix]: NewsLetter form position in mobile view

- components/Alert.js
Closes #7983
Following best practices for code: `Alert` Component starts with capital letter.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8026"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(): Alert components should start with capital letter

- data/beherabikram.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8063"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: beherabikram

- data/Viveksati5143/events/2023-06-08-AWSOME-DAY-Conference.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8064"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Create 2023-06-08-AWSOME-DAY-Conference.json

- data/TusharPaul01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8067"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data TusharPaul01

- data/Sudarshan-t-1999.json
Added a json file for my profile to be added to linkfree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Sudarshan-t-1999

- data/AbhishekSharma.json
- data/AbhishekSharma6903.json
Added My profile to LinkFree :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8065"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: AbhishekSharma

- data/PandeyHarsh433.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8086"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: PandeyHarsh433

- data/Dhruv-Sood.json
> Dhruv sood patch 1

- data/money8203.json
Updated my profile!
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: money8203.json

- components/Badge.js
- components/user/UserProfile.js
Closes #8053
> Before
> After Changes
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8099"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  FEAT: Social Share Button improved

- tests/404.spec.js
- tests/changelog.spec.js
- tests/docs/docs.spec.js
- tests/events.spec.js
- tests/home.spec.js
- tests/map.spec.js
- tests/playground.spec.js
- tests/profile.spec.js
- tests/search.spec.js
Switch from require to import for AxeBuilder to be consistent with other imports.
Cleanup lint errors.
> cleanup AxeBuilder imports

- pages/docs/environments/environment-variables.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: more info on gh token

- data/Chavda-Mitul.json
added my json file
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> added my json file to create profile

- components/GitHubAccelerator.js
Closes #8080
Before
After
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix image overflow 

- data/Viveksati5143.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8115"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Update Viveksati5143.json

- pages/docs/community-resources.mdx
Added my blog Maximising Your Job Prospects in Tech with LinkFree to the list of community resources for LinkFree.
I thought I'd have more but most of my blogs are about EddieHub rather than LinkFree.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add my blog to LinkFree community resources

- pages/changelog.js
> docs: share with social media

- .github/workflows/release.yml
- .github/workflows/vercel.yml
This reverts commit 781021620e5dfbd76db07debf664fbf0646c7ed7.
> Revert "fix: releases to skip if empty (#7496) (#7747)"

- .github/workflows/release.yml
- .github/workflows/vercel.yml
> fix: release action skip on empty

- pages/docs/how-to-guides/json-to-forms.mdx
> docs: json to forms

- models/Stats.js
- pages/api/system/stats.js
- vercel.json
Record daily app stats
- total profiles
- total json profiles
- total form profiles
- total disabled profiles
> feat: daily app stats

- data/CodeKisku.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8133"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:CodeKisku

- data/shubhampatil9500.json
data
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: shubhampatil9500

- components/form/DropDown.js
- components/form/Select.js
- stories/components/form/DropDown.stories.js
- stories/components/form/Select.stories.js
Improve forms Select & DropDown in dark mode (some additions are progressive enhancement for some browsers).
Add form Select & DropDown stories in Storybook
> Improve forms Select & DropDown in dark mode

- components/ConfirmDialog.js
Closes #8029 
Previously, when a link was deleted in dark mode, the text colour of the delete button used to be black. This was not visually appealing. But now, the text colour of the delete button has been updated and changed to white, which is a more suitable and visually pleasing colour choice.
before
after
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: The delete button's text color has been changed from black to white

- data/manishd17.json
You all are doing an awesome work! Just love this community
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8162"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:manishd17

- data/abhijeetgauravm.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Created abhijeetgauravm.json

- components/user/UserEvents.js
- components/user/UserLinks.js
- components/user/UserMilestones.js
- components/user/UserTestimonials.js
- pages/account/manage/links.js
- pages/account/manage/testimonials.js
fix PR https://github.com/EddieHubCommunity/LinkFree/pull/7960 for issue https://github.com/EddieHubCommunity/LinkFree/issues/7945
> Fix PR 7960 for milestone alert consistency

- data/iamfasal.json
Hello EddieHubCommunity maintainers, my name is Fasal. This is my first time contributing to this project and I think I've followed all the steps correctly to contribute to this project. I will be so glad if it gets merged. Thanks :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: iamfasal

- data/flexzy2011.json
Hello EddieHubCommunity maintainers, my name is Felix. This is my first time contributing to this project and I think I've followed the required steps needed to contribute to this project.  I will be so glad if it gets merged. Thanks
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: flexzy2011

- components/user/UserPage.js
Closes #8193
Removed unnecessary Console.log() in UserPage
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8203"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Removed unnecessary Console.log()

- data/DavidRaigozaJ.json
Fixed syntax errors and added milestones tabs.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: DavidRaigozaJ

- pages/docs/environments/environment-variables.mdx
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: missing docs in envar for admin users

- data/Ananya2001-an.json
Added milestones and socials :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8229"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: update profile with milestones

- data/theanantchoubey.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8233"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: theanantchoubey

- data/Viveksati5143/events/13-07-2023-AWS-Builders-Online-Series.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Create 13-07-2023-AWS-Builders-Online-Series.json

- data/biswabaibhab007.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: biswabaibhab007

- data/minnypatel.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8268"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: minnypatel.json

- .github/workflows/codeql.yml
- pages/api/search/index.js
- pages/search.js
Add CodeQL checking
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8228"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Setup codeql checking

- .github/workflows/vercel.yml
Add a Job Summary on the Vercel deploy to show the file usage percentage
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Monitor vercel file usage percentage

- pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8287"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: text consistency

- .github/workflows/release.yml
Create release for `chore` commits from Dependabot
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8291"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: don't skip chore for releases

- pages/docs/environments/gitpod.mdx
Fox PR https://github.com/EddieHubCommunity/LinkFree/pull/7689
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8295"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Gitpod docs - fix pr 7689

- .github/dependabot.yml
- .github/workflows/release.yml
Configure dependabot to use a prefix that will create a release
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Setup dependabot to create releases

- .github/workflows/publish-ghcr.yml
This reverts commit 29cb2bf7616577abd5375ada7b2c158d309d05b5.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert "fix: GHCR workflow command (#8304)"

- Dockerfile.dev
- compose.yml
- package.json
- Change script name
- Optimized the RUN command in Dockerfile
- Now we don't need to check `development` ARG in Dockerfile because we now have separate files for prod (GHCR) and local dev.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8311"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: optimize docker development

- models/Account.js
- pages/account/statistics.js
- pages/api/account/account.js
Closes #7065
I have used info log for account js but that could be changed to debug once the logging issue PR merged. 
I have also fixed the comment given by all reviewers in PR https://github.com/EddieHubCommunity/LinkFree/pull/7721
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Associate profile to logged in user 

- models/Account.js
- models/Profile.js
- pages/account/statistics.js
- pages/api/account/account.js
- pages/api/account/manage/profile.js
- pages/api/auth/[...nextauth].js
- tests/manage/profile.spec.js
- tests/setup/auth.js
Fix PR https://github.com/EddieHubCommunity/LinkFree/pull/8232
Account json with new `github` and `profiles`...
```js
{
"_id": {
"$oid": "64bbe06a071fa9053f8db5f1"
},
"userId": "64bbe06a071fa9053f8db5ef",
"type": "oauth",
"provider": "github",
"providerAccountId": "624760",
"access_token": "xxxxxxxx",
"token_type": "bearer",
"scope": "read:user,user:email",
"profiles": [
{
"$oid": "648adbf91068a61d6e588560"
}
],
"createdAt": {
"$date": "2023-07-22T13:58:02.275Z"
},
"updatedAt": {
"$date": "2023-07-22T14:45:53.948Z"
},
"__v": 1,
"github": {
"company": "Open Source Engineer",
"publicRepos": 258,
"followers": 7255,
"following": 63
}
}
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: link profile to account

- data/Singh26Nitish.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8309"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:Singh26Nitish

- data/abdurrakib01.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: abdurrakib01

- pages/docs/environments/environment-variables.mdx
Closes #6912 
- Update docs related to gitpod environment variables
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8327"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: updating gitpod env variable docs

- data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: grand-rick001 - Add new milestones

- data/Eric-Obeng.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8332"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Eric-Obeng

- pages/_app.js
Closes #8326 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: page navigate old cache issue by adding key to page layout

- components/user/UserEvents.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: profile events to show future by default

- data/MeenuyD.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:MeenuyD

- data/ahamedbasha-n.json
Added my LinkFree Profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added data/ahamedbasha-n.json

- components/user/UserEvents.js
- pages/account/manage/events.js
- Manage events list show all
- Profile events default to future
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8361"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: manage events list

- pages/api/events.js
People are adding incorrect events, this allows admin to hide these events from the main events page - events still appears on their profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8363"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: hide disabled events on the main events list

- data/AdrianAcostaPR.json
Created AdrianAcostaPR.json file with information about my social media links and bio.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8356"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: AdrianAcostaPR

- data/RishikeshYadav95.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8365"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: RishikeshYadav95

- README.md
- pages/index.js
Update @Pradumnasaraf's bio on `Index.js` and `README.md` page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8366"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: update Pradumnasaraf's bio

- components/admin/Navigation.js
- models/Profile/Event.js
- pages/admin/events.js
- pages/admin/statistics.js
- pages/api/admin/events.js
- pages/api/admin/events/[...id].js
- tests/admin/events.js
- tests/admin/statistics.spec.js
Events list had some tests in there and also had people linking to their socials - admin needs to be able to disable these from the main list but still appears on their profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8371"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: admin toggle events

- components/admin/Navigation.js
- pages/admin/users.js
- pages/api/admin/users.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Admin user list

- pages/admin/profiles.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: more profile data for admin

- data/Viveksati5143/events/03-10-2023-DockerCon-2023.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8412"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Create 03-10-2023-DockerCon-2023.json

- components/event/EventCard.js
- pages/account/statistics.js
- pages/api/events.js
- pages/api/profiles/[username]/index.js
- services/utils/dateFormat.js
fixes #7650 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8380"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: date format helper

- pages/api/profiles/[username]/index.js
- services/github/getLocation.js
Do not update profile `updatedAt` date time on stats view increment
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: profile updated datetime on stats

- .github/config/labeler.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: gh action labeler

- pages/admin/profiles.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8439"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: admin users list inc repos

- components/layouts/DocsLayout.js
- components/navbar/Navbar.js
- components/user/UserRepos.js
- pages/api/repos.js
- pages/docs/how-to-guides/repos-forms.mdx
- pages/docs/profile-tips.mdx
- pages/events.js
- pages/repos.js
- tests/events.spec.js
- tests/repos.spec.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8446"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: global repos list

- data/henilGondalia.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8456"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data : henilGondalia

- .github/config/labeler.yml
- .github/workflows/labels.yml
Use the GitHub managed action to label PRs
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8466"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> switch to GitHub labeler action

- .github/workflows/labels.yml
Use `pull_request_target` as it is the only way to work with PRs from forks
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8469"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> handle labeling PRs from forks

- data/AyushRay06.json
You'll are doing a great job. I would like my LinkFree profile to be updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8465"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: AyushRay06

- pages/api/admin/events.js
- pages/api/discover/tags.js
- pages/api/events.js
- pages/api/repos.js
- pages/api/search/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8477"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: db connection

- data/ElianCodes.json
Adds ElianCodes LinkFree profile
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8480"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: ElianCodes profile

- pages/admin/profiles.js
Use full import of heroicons to avoid tree shaking issue
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8487"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix heroicons import

- components/account/manage/Delete.js
- components/user/UserRepos.js
- pages/account/manage/repos.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: delete repo

- components/user/UserRepos.js
- pages/admin/events.js
- pages/admin/profiles.js
fixes #8441 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8492"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add tailwind variables to styles in repos, admin page

- data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
- data/SandipPalit/events/2023-08-05-Nomoskar-Kolkata.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Sandip palit patch 2 1

- pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8442"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: prompt dev to load data

- data/debadityasingh8972.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: debadityasingh8972

- data/Sagar0-0.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Sagar0-0

- pages/roadmap.js
https://github.com/EddieHubCommunity/LinkFree/commit/9fed57a817251651e8dfd5a8f3b4f10c0547f2bb
Fixes #8512 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8499"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improved Wording

- pages/docs/environments/environment-variables.mdx
- pages/docs/environments/local-development.mdx
fixes #8503 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8517"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: docs github oauth local dev

- data/okrupesh.json
Minor changes in the bio and tags
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8519"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor changes in the bio and tags

- pages/api/profiles/index.js
- pages/api/search/index.js
- pages/map.js
- pages/search.js
fixes #7648
The function `getUsers` was renamed to `getProfiles`.
Subsequent changes made to:
`pages/api/profiles/index.js`
`pages/map.js`
`pages/search.js`
`pages/api/search/index.js`
I am new to open source contributions... So if i have missed anything, I am more than ready to fix it.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8518"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixes Consistency Issue:  getUsers renamed to getProfiles

- data/mhgolestan.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: mhgolestan

- components/event/EventCard.js
- pages/account/manage/event/[[...data]].js
- pages/api/events.js
fixes #7854
Tweaks to PR https://github.com/EddieHubCommunity/LinkFree/pull/8056
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8531"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: event price

- data/Sahilll15.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Sahilll15

- data/Akash-vadakkeveetil.json
So this will be my first open source contribution and thanks for the great opportunity Eddie and the team looking forward to contributing more to the community
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Akash-vadakkeveetil

- pages/api/repos.js
- Update mongo query in `pages/api/repos.js` to filter repos where `repos.dates.pushedAt` > the last 30 days.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: update mongo query to show active repos

- .github/config/labeler.yml
Add dependencies label for package changes
Add CI/CD label for changes in the .github directory
Add docs label for changes to the docs pages
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8563"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add additional labels for pull requests

- components/Button.js
Closes #8186 
The button is now visible in light mode 
No issues in dark mode - 👍 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8568"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Fixed] : Button visibility on light mode 

- components/account/manage/Edit.js
- components/user/UserMilestone.js
fixes #8507
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed the z-index of edit icon in link

- data/JulieB16.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: JulieB16

- .github/workflows/labels.yml
Add code to automate `issue linked ` label to the labeler action
See this repo for my testing:
https://github.com/dan-mba/label-test
This will only work if the issue is mentioned correctly so that GitHub displays it here:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> automate issue linked label

- pages/icons.js
Closes #8424
- Add background color class for input box to fix text not visible in dark theme.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [fix]: search input background-color in icons page for dark theme

- pages/account/statistics.js
Missing sections info overflows Profile Completion component
Closes #8564 
Fixed the missing sections info text overflowing profile completion component by adding `flex-wrap`.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8584"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed profile completion component text overflow

- components/Markdown.js
- components/event/EventCard.js
- components/form/Textarea.js
- components/map/UserMarker.js
- components/user/UserHorizontal.js
- components/user/UserMilestone.js
- components/user/UserMini.js
- components/user/UserProfile.js
- components/user/UserTestimonials.js
- pages/account/manage/event/[[...data]].js
- pages/account/manage/milestone/[[...data]].js
- pages/account/manage/profile.js
fixes #7970
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: markdown multi lines

- data/ralphsulit.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8601"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: ralphsulit

- components/navbar/Navbar.js
- pages/admin/profiles.js
- pages/api/discover/profiles.js
- pages/discover.js
- tests/discover.spec.js
closes #8613
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: discover page for recently updated profiles

- data/Siwi0w0.json
- Create my profile.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8626"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Siwi0w0

- data/Yashwanth.json
- data/yashwanth-3000
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: yashwanth-3000

- data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
- data/SandipPalit/events/2022-11-13-DevFest-2022-Kolkata.json
- data/SandipPalit/events/2023-02-11-TFUG-Kolkata-Reboot.json
- data/SandipPalit/events/2023-03-04-Being-Women-IWD-Celebration.json
- data/SandipPalit/events/2023-03-11-Dare-To-Be-an-Entrepreneur-IWD-2023.json
- data/SandipPalit/events/2023-05-07-Cloud-Community-Day-Kolkata-2023-Kolkata.json
- data/SandipPalit/events/2023-08-19-Google-IO-Extended-2023.json
- data/SandipPalit/events/2023-08-27-Keras-Community-Day-2023.json
Added new events.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Sandip palit patch 3

- pages/404.js
fixes #8616 
- Centered the mascot using mx-auto using tailwind css
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8623"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Centered mascot on 404 page

- README.md
Expanded the docker compose instructions and details
The steps and options to use the project locally were expanded for clarity
We added git as a requirement. 
We included docker desktop as an option because it's installable on all OS's.
We expanded the the details of the steps to make them more clear.
We included an optional drop down option which covers the steps needed to run the next.js app
locally and a mongoDB instance in docker  when Mongo Compass is needed as it won't work
with Docker compose.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8608"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Documentation:Expanded the docker compose instructions and details

- data/grand-rick001.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8649"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: grand-rick001 - Update twitter link

- components/user/UserProfile.js
- components/user/UserTestimonials.js
Edit:
fixes #8642 
This PR apply the changes proposed in Issue/Bug by @xkrishguptaa.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed: [BUG] The Profile Pictures On Testimonials And Profiles Don't Match #8642

- models/Profile.js
- models/ProfileStats.js
- pages/[username].js
- pages/api/profiles/[username]/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8654"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: store profile referrer

- pages/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: homepage repo feature

- data/ElianCodes.json
Update ElianCodes bio
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Data: ElianCodes update bio

- pages/account/manage/profile.js
Fix the profile layouts select to avoid a missing keys warning
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8668"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix profile layout select

- data/Viveksati5143.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8673"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Added Quine

- models/Profile.js
- models/ProfileStats.js
- package-lock.json
- package.json
- pages/[username].js
- pages/api/profiles/[username]/index.js
This will allow us to list the top locations and display a pie chart of locations
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8677"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: count profile visitors ip

- pages/api/profiles/[username]/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8679"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: replace on profile extra stats

- models/Profile.js
- models/ProfileStats.js
- pages/api/profiles/[username]/index.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: store country instead of ip

- data/BSatishSutar.json
Made minor changes to my Bio
- [* ] My code follows the code style of this project.
- [ *] All new and existing tests passed.
- [ *] This PR does not contain plagiarized content.
- [ *] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8693"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: BSatishSutar

- pages/changelog.js
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8705"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: changelog for discover, animate links

- README.md
- tests/search.spec.js
Closes issue [8699](https://github.com/EddieHubCommunity/LinkFree/issues/8699)
``test("After search click profile", async ({ page }) => {
// 1. Perform search
await page.goto("/search");
const input = page.locator("[name='keyword']");
await input.type("eddiejaoude");
// 2. Click on the searched profile
const profileLinkSelector = 'a[href="/eddiejaoude"]';
const profileLink = page.locator(profileLinkSelector);
await profileLink.click();
await page.waitForLoadState("networkidle");
// 3. Check if the profile is displayed
const profileHeader = page.locator("h1");
const profileHeaderText = await profileHeader.innerText();
await expect(profileHeaderText).toContain("Eddie Jaoude");
});``
Automated test report shows test is working
<a …
> Updating ./tests/search.spec.js automated test

- components/form/Input.js
Closes #8661
Stop keydown event propagation on input component
after made changes
https://github.com/EddieHubCommunity/LinkFree/assets/73095526/42b1ffe3-c8ed-405f-bf6c-e2370885e4d9
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8685"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: stop keydown event propagation on input

- data/sumitbhanushali.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: sumitbhanushali

- data/CRAZy-Monk3Y.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8726"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: CRAZy-Monk3Y

- data/sree-hari-s.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: sree-hari-s.json

- data/CRAZy-Monk3Y.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8732"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: CRAZy-Monk3Y.json

- .github/config/labeler.yml
add a label for updates to the DB models
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add label for models updates

- tests/events.spec.js
Edit: 
Fixes #8670
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8708"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed: [OTHER] <Test error for "event listed" test on the /events end point> #8670 

- pages/account/statistics.js
Closes #8433 
Modified the .join function to add a comma and a space instead of just a comma
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8676"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Spaces in Missing Section

- README.md
- compose.yml
- pages/docs/environments/local-development.mdx
Closes #8716 
I exposed compose mongodb container 27017 port to be able use MongoDB Compass and updated readme.md accordingly
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8718"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Expose compose mongodb container port && update readme.md

- package-lock.json
- pages/docs/index.js
Adjusted Gaps between Horizontal line and hover line of pages
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Adjusted padding between section and pages

- pages/account/manage/repos.js
Closes #8606
Add margin to form component
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8694"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix: spacing between add repo form and repo list.

- data/Harshitahusts.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8729"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: Harshitahusts

- data/NiikNiik.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8739"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Data: NiikNiik

- data/SohaMubashir.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8755"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: SohaMubashir

- data/MaorBemdoo.json
Added my profile to data/MaorBemdoo.json as followed all rules as staed on my checklist
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8758"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data: MaorBemdoo

- README.md
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: explaining rename

- README.md
> fix: rename description

- README.md
> fix: rename local git clone info

- README.md
> fix: formatting rename info

- pages/changelog.js
> fix: user changelog for rename

- pages/docs/terms.mdx
> fix: terms date

- package-lock.json
It updated the project name (from linkfree to BioDrop and updated with the latest format. 
Process: I deleted the file and installed the deps again.
> fix: update package-lock file

- CONTRIBUTING.md
- components/PageHead.js
- constants/index.js
- pages/[username].js
- pages/account/no-profile.js
- pages/docs/map.mdx
- pages/docs/quickstart-json.mdx
- stories/components/navbar/Navlink.stories.js
- stories/components/user/UserPage.stories.js
- stories/components/user/UserTestimonials.stories.js
- stories/components/user/profile.json
> fix: subdomain to domain

- README.md
- pages/index.js
Bump the BioDrop V2, i.e v2.0.0
> BREAKING CHANGE: v2

- config/app.json
- package-lock.json
- package.json
Update the BioDrop version to v2.0.1 (with this PR)
> fix: BioDrop app version

- README.md
> fix: uptime badge

- pages/docs/environments/gitpod.mdx
> docs: gitpod environment variable

- components/Footer.js
- components/navbar/NavLink.js
- pages/index.js
> fix: link vercel analytics

- README.md
- components/user/UserMini.js
- pages/account/statistics.js
- pages/api/account/statistics.js
Closes #7892 
The rank feature is solely based on profile views
```$setWindowFields``` was introduced on Mongo 5.0.
MongoDB required version: 5.0 or above.
Before changes:
After changes:
> feat: profile rank

- components/CallToAction.js
- components/ThemedImage.js
- components/statistics/BasicCards.js
- pages/index.js
> feat: improved landing page

- data/kush6291.json
> data: kush6291.json

- data/avinashharesh.json
It will create a new json file called "avinashharesh.json" in data folder
This is creation of a profile in BioDrop
> data: avinashharesh

- data/RutikaW1155
You'll are doing a great job . I would like my LinkFree profile to be updated.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8701"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> data:  RutikaW1155

- components/form/Toggle.js
- components/user/UserProfile.js
- models/Profile.js
- pages/[username].js
- pages/account/manage/profile.js
- pages/api/account/manage/profile.js
closes #8835 
When show stats is disabled in profile page:
When show stats is enabled in profile page:
```Account/manage/profile```
> feat: Show profile stats publicly.

- .github/workflows/vercel-pr-preview.yml
- .github/workflows/vercel-preview.yml
- .github/workflows/vercel.yml
> fix: curl command to follow redirects

- pages/admin/profiles.js
- pages/api/admin/profiles.js
> feat: admin filter profiles

- components/form/Select.js
- pages/api/repos.js
- pages/repos.js
closes #8582 
Sort feature:
- sort by stars
- sort by forks
- sort by push date
- sort by created date
> feat: Sort repo page

- README.md
> docs: logo on sticker in readme

- components/Button.js
- components/user/UserRepos.js
- pages/account/manage/links.js
- pages/account/manage/repos.js
This reverts commit b6bf65493844c74dc7bf85ef4f651cd6605dc529.
Reverting button changes as breaks other areas
> Revert "fix: margin to manage pages (#8855)"

- components/map/Map.js
- pages/map.js
closes #8558
Issue https://github.com/EddieHubCommunity/BioDrop/issues/8558
Pull Request https://github.com/EddieHubCommunity/BioDrop/pull/8583
> fix: map height

- components/user/UserEvents.js
- pages/account/manage/events.js
- pages/api/account/manage/events.js
closes #8321 
filter option for event section
* past events
* future events
* all events
* paid events
> feat: filter options for event section

- pages/api/repos.js
#8867 
Repos will only be shown in the repo page if repo contains a minimum of 100 stars and 10 forks.
* 100+ stars
* 10+ forks
* Recent commit in the last 30 days
Had to put these 3 checks but the last one was already there in the code.
> minimum forks and stars criteria in repo page

- data/Sreejit-Sengupto.json
- data/sreejit-sengupto.json
> data: SreejitSengupta

- data/StarKnightt.json
> data:StarKnightt

- components/Footer.js
> feat: blog and newsletter

- pages/account/manage/testimonials.js
closes #7846 
Added image tag that will show the profile picture.
Before Changes:
After Changes:
> feat: added profile picture on manage testimonials

- components/user/UserProfile.js
adds start for issue #8848.
Keep open for additional features of the star
> add star - premium indicator

- data/p1kalys.json
You're all doing a great job. I would like my BioDrop profile to be updated.
> data: p1kalys

- pages/api/account/manage/link/[[...data]].js
> fix: delete link

- data/Sxamoecode.json
> data:Sxamoecode

- data/Nwakaego-Ego.json
> data: Nwakaego-Ego.json

- components/Testimonials.js
- components/layouts/MultiLayout.js
- pages/docs/index.js
- pages/index.js
- pages/roadmap.js
- tailwind.config.js
issue: 8847
- Added `dark-2` color which represents `#121212` in tailwind config file.
- Replaced `dark` class to `dark-2`.
> [FEATURE] (changed bg): changed bg from #000000 to #121212 in dark mode

- data/natlmartin.json
> data: natlmartin

- data/UlbertAO.json
> data : created UlbertAO json

- package-lock.json
- package.json
- Change the linkfree-cli package to biodrop-cli
> fix: update the biodrop-cli

- components/Bulb.js
- components/user/UserLink.js
- pages/admin/events.js
- pages/api/admin/events.js
> feat: highlight profile status

- data/Harsh-Trivedi03.json
> data: Harsh-Trivedi03

- pages/search.js
fixes #8980 
URL parameter gets updated when search bar becomes empty
https://github.com/EddieHubCommunity/BioDrop/assets/68022411/2e3079bd-3bfe-4a7b-84b4-dbd0f14c7128
> URL parameter update when search bar becomes empty

- components/user/UserRepos.js
- pages/account/manage/repos.js
Closes #8763
Added a confirmation dialog to prevent accidental repository deletions.
https://github.com/EddieHubCommunity/BioDrop/assets/96465597/cec459bd-a2e5-4751-81e6-10c93dd44cf3
Please review and provide your feedback or suggestions. Thank you
> [Feature] Added Confirmation Dialog for Repo Deletion

- pages/account/statistics.js
> fix: rename icon for premium stats

- components/tag/TagsInput.js
- pages/account/manage/profile.js
Closes #8766 
* Created a new **`TagsInput`** component for inputting and displaying tags
* Implement a  **`handleKeyUp`** event handler for separate tags, when the **`COMMA`** key presses. If the input field is not empty, tags will be added and displayed as individual elements.
* Implement a **`handleKeyDown`** event handler for the **`BACKSPACE`** key when the input field is focused. Check if the input field is empty and the user presses **`BACKSPACE`**. If the conditions are met, remove the last tag from the state and update the input field to display the removed tag
* Attach an **`onClick`** event handler to each rendered tag element, when a tag is clicked, call a function to remove the clicked tag from the state.
dark mode:
> feat: add Tags Input feature

- pages/admin/statistics.js
- pages/api/admin/stats.js
> feat: admin stats of premium users

- data/indigo423.json
Added a publication in my milestone data set.
> data: indigo423 adding publication in milestones

- components/Footer.js
changed old twitter icon to new x icon in footer section of landing page.
> fix update twitter icon in footer

- data/J-CODE07.json
> data: LinkedIn Profile

- components/DataList.js
- components/Footer.js
- components/layouts/DocsLayout.js
- pages/docs/open-source-roadmap/checks.js
- pages/docs/open-source-roadmap/glossary.js
- pages/docs/open-source-roadmap/how-to-contribute.js
- pages/docs/open-source-roadmap/index.js
- pages/docs/open-source-roadmap/running-the-project-locally.js
- pages/docs/open-source-roadmap/what-next.js
- pages/docs/open-source-roadmap/what-to-contribute.js
- pages/docs/open-source-roadmap/what-why.js
- pages/docs/open-source-roadmap/where.js
> Docs open source roadmap

- tests/search.spec.js
Closes: #9081
- added logic to start test from homepage ("/")
- added logic to select the approrpiate a tag for navigation
- used `input.fill` instead of `input.type` as the latter has been deprecated
> Test: find the profile after providing concise name - Closes #9081

- components/ThemedImage.js
- pages/index.js
- styles/globals.css
Set homepage hero image priority to true
fix hydration issue for themed image in dark mode.
> Improve homepage hero image priority

- data/allexgut.json
> data:allexgut

- pages/index.js
Use `strategy="lazyOnload"` for video script to improve performance.
> Delay video script loading for performance

- data/Gabriel-Giani.json
> data: Gabriel-Giani

- components/tag/TagsInput.js
Closes #9094 
add a conditional check in the `handleKeyDown` event handler for the `BACKSPACE` key to prevent the 
input field from becoming `undefined` when there are no tags.
> fix: backspace key handling with no tags

- data/Andrewyithub.json
> data: Andrewyithub

- pages/api/profiles/[username]/index.js
Set up more async functions to run concurrently.
Hoping to improve server response time
> Improve profile async data gathering

- tests/search.spec.js
fixes #9090 
Added a new test for search persistence check
> Test: search persistence

- config/community-resources.json
> Kim's Community Resource

- .github/workflows/vercel-pr-preview.yml
- .github/workflows/vercel-preview.yml
- .github/workflows/vercel.yml
- pages/api/system/testimonials-forms.js
> fix: testimonials for profiles with forms

- pages/api/system/testimonials-forms.js
> fix: improved testimonial importing output

- data/Viveksati5143.json
> data: Added testimonial section

- data/bL34cHig0.json
> data: bL34cHig0

- components/Tabs.js
- components/user/themes/UserTabs.js
- pages/changelog.js
- tests/profile.spec.js
Fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9007
closes #8969
> feat: add tabs to url (Fix pr 9007)

- components/user/UserProfile.js
- pages/[username].js
fixes #9144
fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9154
Desktop no changes...
Mobile tags, stats, add testimonial are hidden...
> Fix pr 9154

- components/user/UserEvents.js
closes #8964
Added warning "No Events found" when there are no events.
> [Fix] : added warning to manage event page

- components/event/EventCard.js
Fixes #9149
added a standard placement to the price on events
> feat: added a standard placement of price on events

- .github/workflows/release.yml
fixes #9192 
Changes `merge` flag to `squash` to stop merge commits from creating and keeping a linear commit history using squash method
GitHub CLI docs for reference: https://cli.github.com/manual/gh_pr_merge
> ci(release): squash merge release details

- components/Button.js
- components/account/manage/Delete.js
> fix: button classes

- config/schemas/jsonProfileSchemas.js
closes #9200 
Optional zod schema from name and bio has been removed.
> fix: removed optional zod schema from name and bio

- components/user/UserRepos.js
- pages/api/repos.js
- pages/repos.js
> feat: dedup repos page

- pages/api/repos.js
- pages/repos.js
> fix: repo dedup

- components/user/UserRepos.js
- pages/repos.js
> fix: repo usernames

- vercel.json
Fixes #9135 
Increase execution time for loading JSON files.
> feat: Increase execution time for loading json files

- vercel.json
> fix: max func duration

- pages/api/system/reload.js
- vercel.json
> fix: max func duration move to file

- .github/ISSUE_TEMPLATE/feature_request.yml
> fix: default issue template dropdown to no

- .github/config/labeler.yml
> fix: hacktoberfest ignore label for profiles

- README.md
> docs: hacktobefest notes to readme

- README.md
> docs: hacktoberfest issue to be a link

- data/Viveksati5143.json
Added dev.to link & minor changes
> data: Added dev.to link & minor changes

- config/app.json
Closes #9219 
Removed app alert for new files from app.json
> feat: remove app alert for new icons

- pages/account/manage/event/[[...data]].js
Closes #9119
I have added marginBottom 1.5 rem through inline style element
> fix: Add more space between buttons and event card (#9119)

- components/layouts/Alert.js
- components/layouts/MultiLayout.js
> feat: alert to star out github repo

- components/admin/Navigation.js
- pages/admin/changelog.js
- pages/api/account/manage/event/[[...data]].js
- pages/api/account/manage/link/[[...data]].js
- pages/api/account/manage/milestone/[[...data]].js
- pages/api/account/manage/profile.js
- pages/api/account/manage/repo/[[...data]].js
- pages/api/account/manage/settings.js
- pages/api/admin/changelog.js
> feat: admin view changelog

- pages/admin/statistics.js
- pages/api/admin/stats.js
> feat: admin stats for changelog

- pages/api/profiles/[username]/index.js
> fix: remove github cache update

- data/Ssaava.json
Excited to make my first contribution to the repository.
Hello,
I'm delighted to have the opportunity to contribute to this exceptional repository. Special thanks to EddieHub for providing this platform for collaboration and contribution. Your feedback and guidance are greatly appreciated as we work together to enhance this project.
Best regards,
**Ssaava Emmanuel**
> data: Ssaava

- data/Judge-Paul.json
> data:Judge-Paul

- pages/api/account/manage/repo/[[...data]].js
- pages/api/profiles/[username]/index.js
- pages/api/system/github.js
- services/github/getRepo.js
- vercel.json
> fix: profile repos + update cache

- data/Bishwajit-2810.json
> data Bishwajit-2810.json

- data/theCephas.json
> data: theCephas

- data/realdezzy.json
> data: realdezzy

- pages/events.js
Closes #9275
- Removing help badge on the events page
before:
after
> feat: removing help badge on events page

- data/marameref.json
> data: marameref

- data/shubhalgupta.json
> data: shubhalgupta

- data/itsayopapi.json
> data: itsayopapi

- data/DonGuillotine.json
> data: DonGuillotine

- pages/api/system/stripe.js
Log more information about Stripe upgrade/downgrade to the LogChange db collection.
> feat: logchange on free/premium

- pages/api/system/stripe.js
> fix: stripe hook username

- pages/api/system/stripe.js
> fix: stripe webhook downgrade log

- data/rossana87.json
> data: rossana87

- data/Luwa-Tech.json
> data: Luwa-Tech

- data/YanaGorina-alt.json
> data: YanaGorina-alt

- data/D4-Community.json
> data: Update D4-Community.json

- pages/docs/open-source-roadmap/index.js
Closes #9298 
Add SideNav in Open Source Roadmap
- Before
- After
> Fix: Docs page missing nav

- pages/api/account/statistics/link/[id].js
- pages/pricing.js
> fix: limit daily stats click to 30d

- pages/index.js
Edit: 
Fixes #9291 
fixed issue #9291 
now if a user click on the help button it will redirect to the faqs page
> feat: help now redirect to docs/faqs

- pages/account/manage/links.js
Fixes #9221 
- Added condition to disable/enable the reorder button depending on number of links added.
https://github.com/EddieHubCommunity/BioDrop/assets/68698332/5b7eff77-7c92-4b2c-a24a-800559e962ff
_(attached video instead of screenshot)_
> fix: disable the reorder button unless there is more than one link added

- .github/workflows/release.yml
> fix: changelog and version bump

- pages/index.js
> fix: help link to faq

- data/stenwire.json
> Add `data/stenwire.json`

- pages/docs/faqs.mdx
Closes #9374 
Before: 
After:
Please let me know if you have any feedback.
> Fixed typos in Faq's section.

- data/WassCodeur.json
Hello, I've just added the WassCodeur.json in data folder
> add WassCodeur.json i

- components/statistics/PieGraph.js
- pages/account/statistics/index.js
- pages/account/statistics/locations.js
- pages/account/statistics/referers.js
- tests/account/stats/location.spec.js
- tests/account/stats/referer.spec.js
- tests/setup/global-setup.js
> feat: location stats details

- pages/account/statistics/referers.js
> fix: url display in referrers page

- data/mehra-sourav.json
Just adding my profile to BioDrop.
> data: mehra-sourav

- components/form/Label.js
- components/form/Select.js
- components/user/UserProfile.js
> feat: display pronoun

- pages/changelog.js
> fix: latest features added to changelog

- components/Tabs.js
> fix: tabs on mobile no label

- data/Nuellity.json
> data: Nuellity

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> fix: issue template bug and feature

- .github/ISSUE_TEMPLATE/bug.yml
> fix: bug issue template for environments

- .github/ISSUE_TEMPLATE/bug.yml
> fix: bug issue template environment to input

- .github/ISSUE_TEMPLATE/feature_request.yml
Updated description field to a more descriptive title
no open issue - discussed in Discord
Updated the required description field to reflect that this area is for a proposed solution
> Update feature_request template

- pages/docs/how-to-guides/links-forms.mdx
Closes #9432 
Made following changes in Links section of documentation
- Changed 'these will shown here' to 'they will be shown here' (looks grammatically correct)
- Changed  'please refer to Edit a Link below' to 'please refer to Edit a Link section below'  (sounds better as it refers to the section below)
Before : 
After:
Please let me know if you have any feedback
> Updated links-forms.mdx

- pages/docs/open-source-roadmap/checks.js
Closes #9433
1) Modify "estiablished" to "established"
2) Modify  "issuses" to "issues"
3) Modify "On the top tab, go to Insights, then down the left go to Community. Check they have a code of conduct and a contributing guide." 
to 
"On the top tab, go to Insights, then scroll down the left side to go to Community. Check if they have a code of conduct and a contributing guide."
> Fixed : <A typographical error> #9433

- data/waellerbe.json
Original version for my BioDrop JSON file
> data: waellerbe.json

- pages/search.js
Closes #9349 
As specified in the issue, I increased the number of user profiles displayed on the search page by one to fill the empty space at the bottom. Please refer to the attached screenshots.
> feat: Increase profile count in search page

- data/kahmed-stack.json
> data:kahmed-stack

- pages/admin/profiles.js
- pages/api/admin/profiles.js
- tests/profile.spec.js
> feat: admin list premium users

- pages/admin/changelog.js
- pages/api/admin/changelog.js
> feat: admin changelog filter user

- data/vanshiz.json
> data: vanshiz

- components/user/themes/UserTabs.js
Fix empty tabs bug giving `500` exception from PR https://github.com/EddieHubCommunity/BioDrop/pull/9380
> fix: hide tabs with no data

- components/event/EventCard.js
- models/Profile/Event.js
- pages/account/manage/event/[[...data]].js
- pages/api/account/manage/event/[[...data]].js
- pages/api/events.js
Fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9276
closes #5832
> feat: tags to events

- pages/account/onboarding/index.js
Closes #9294
Fixes issue of low contrast text on https://www.biodrop.io/account/onboarding.
Used the `dark` class in the element and set to change font color.
> Fixes #9294 Low contrast color change on the onboarding page.

- data/harohar13.json
> data: harohar13

- pages/docs/contributing/commits.mdx
> ## Fixes Issue
> Closes #9525
> 
> ## Changes propose
Modify "Continious " to "Continuous"
> fixed typo #9525

- data/YashSalunke12.json
> data:YashSalunke12

- pages/account/onboarding/index.js
> fix: Typo mistake in Testimonials section on the onboarding screen (#9519)

- components/event/EventCard.js
Closes #9277 
This PR basically does, if some of the events are free it will show `Free` text.
I ran this locally this works fine also doesn't break any existing code, please have a look once.
> [Feature]: will show `Free` text if event is free

- data/AnikethDeb2004.json
> data:AnikethDeb2004

- data/AloisSeckar.json
> data: AloisSeckar

- pages/api/profiles/[username]/index.js
Events on profile page are not displayed in sooner events first
> fix: events asc order on profile

- components/user/UserProfile.js
- pages/[username].js
- pages/api/account/statistics/index.js
> feat: public stats reduce space

- pages/[username].js
> fix: profile views badge abbreviation

- pages/[username].js
- shows on profile only if:
- user is not logged in
- profile is not premium
> feat: create profile button

- data/Bratajit-03.json
> Data: Bratajit-03

- pages/api/account/statistics/index.js
> fix: last 30 days views

- pages/docs/environments/gitpod.mdx
This PR changes horizonal to horizontal on page https://www.biodrop.io/docs/environments/gitpod
Closes #9540 
Fixes Issue #9540
> Fixes Typographical error docs/environments/gitpod page

- components/Footer.js
updated footer.js
Closes #9293 
Roadmap to BioDrop Roadmap
> improvement : footer text update

- pages/docs/environments/local-development.mdx
Closes #9507 
I changed the command "docker rmi BioDrop-app" to "docker rmi biodrop-app" because the image name needs to be all in lowercase.
> docs: Update docker rmi command

- pages/api/auth/[...nextauth].js
- pages/docs/quickstart-forms.mdx
There are empty profiles, so this should help people get started
- If the profile is new use GitHub name to create a basic profile
- If the profile has no links, add their GitHub link
> feat: populate basic profile on login

- pages/docs/how-to-guides/milestones-json.mdx
> docs: add correct date format to clipboards of Milestones-json

- pages/roadmap.js
> fix: updated app roadmap

- README.md
> fix: mongo docs minimum version

- pages/api/profiles/[username]/index.js
> Fixes Issue:  #8533 [BUG] The order of pinned icons doesn't change

- .github/workflows/check-assignee.yml
> fix: update assign comment check

- .github/workflows/check-assignee.yml
- .github/workflows/codeql.yml
> ci: action comment text

- data/Akshat171.json
> Akshat171 patch 2

- .github/workflows/check-assignee.yml
> ci: assigned issue check filter repo

- CONTRIBUTING.md
> docs: contributing issue assignment

- pages/account/statistics/index.js
> fix: url wrap in stats list

- components/Tabs.js
closes #9521 
Removed a unnecessary label on ```Tab``` component
The ```Tab``` component is used on two places ```SubNav```  and ```UserTabs``` component
Before changes: 
After changes:
> removed unnecessary label on Tab component

- data/waellerbe.json
Updates for my JSON file
- BioDrop profile updates
> data: waellerbe

- components/statistics/StatsChart.js
- pages/account/statistics/index.js
- pages/account/statistics/link/[id].js
Closes #9408 
Rename StatsChart to BarGraph in [BioDrop/components/statistics/StatsChart.js](https://github.com/EddieHubCommunity/BioDrop/blob/ba441accc667ea26060d268c214b29977301aa38/components/statistics/StatsChart.js#L21).
And updated its usage in  BioDrop/pages/account/statistics/index.js
and  BioDrop/pages/account/statistics/index.js
> FIx: Renamed the StatsChart to BarGraph and updated its usage

- components/user/UserMini.js
Closes #9504 
The 'View Profile' button was not aligned properly, so I applied the `min-w-fit` property of Tailwind CSS.
- Before Changes
- After Changes
> fix: view Profile Button not align properly.

- data/Vidip-Ghosh.json
- data/VidipGhosh.json
> data: VidipGhosh

- pages/index.js
Fixes #9608 
Change border color on light theme
> style: fix light theme border issue

- .github/workflows/check-profile.yml
If profile not found, skip gh action (404)
> fix: github action skip on profile not found

- .github/workflows/check-profile.yml
> fix: gh action profile status code type

- .github/workflows/check-profile.yml
> fix: gh action profile check method

- .github/workflows/check-profile.yml
> fix: gh action profile check flag

- .github/workflows/check-profile.yml
> fix: gh action profile check ignore 404

- data/SAD0XER.json
> data:SAD0XER

- pages/api/admin/profiles.js
> fix: admin profile limit increased

- data/Jagan-07.json
> Update and rename J-CODE07.json to Jagan-07.json

- pages/icons.js
Closed #9636 
Fixed by replacing the default input with Input from components
NA
> fix: double border on input field in icons page

- pages/admin/profiles.js
- pages/api/admin/profiles.js
> feat: admin list not enabled proiles

- data/issamahwach.json
> data: issamahwach.json

- pages/index.js
Closes #9712 
Updated BioDrop Map Screenshot in the features section.
> Updated BioDrop Map Image

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> chore: improve feature issue template

- pages/api/account/manage/settings.js
> fix: check custom domain first

- pages/api/account/manage/settings.js
Domain should only be updated if there are changes
> fix: profile settings domain

- pages/icons.js
- tests/icon.spec.js
Fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9655
> Icon search page improvements

- .github/workflows/vercel-preview.yml
- pages/[username].js
> Feat reload pwa

- components/PageHead.js
- next.config.mjs
> fix: disable pwa due to caching errors

- components/PageHead.js
- next.config.mjs
- package-lock.json
> fix: pwa fix cache

- data/kshitij9896.json
Hey @amandamartin-dev.
Thank You For The Guidance  
This PR Have The Updated File
Old PR is Closed
> Updated kshitij9896.json

- CONTRIBUTING.md
> docs: do not force push

- pages/index.js
> fix: homepage video

- pages/pricing.js
> fix: pricing premium text

- models/Link.js
- pages/account/manage/link/[[...data]].js
> fix: reduce link name length to min 1

- pages/admin/statistics.js
- pages/api/admin/stats.js
> feat: admin stats for custom domains

- pages/account/manage/event/[[...data]].js
- pages/account/manage/profile.js
closes #9706 
* replaced the standard array used for storing tags with a `Set` constructor.
* updated the documentation.
current:
https://github.com/EddieHubCommunity/BioDrop/assets/73095526/e2adb37f-f7e5-47a1-aab4-02f6a1ec65a2
after changes:
https://github.com/EddieHubCommunity/BioDrop/assets/73095526/bdf752dd-73cb-41fe-b37c-eaa026c51112
> fix: duplicate tags issue using set constructor

- data/Arturo23FJ.json
> data:Arturo23FJ

- data/shaileshthakur1.json
> data: shaileshthakur1

- pages/api/icons.js
- pages/icons.js
fixes #9230 
Reformat code from PR https://github.com/EddieHubCommunity/BioDrop/pull/9819
> Icon search to have badge counter from DB

- pages/icons.js
> fix: popular icon search

- components/Icon.js
- pages/api/icons.js
- tests/icon.spec.js
> fix: null icons

- data/mjr2595.json
> data: mjr2595

- components/tag/TagsInput.js
closes #9840 
* replaced instances of `event.keyCode` with appropriate usage of `event.key`
> fix: replace deprecated key code

- pages/changelog.js
- pages/roadmap.js
> fix: changelog update

- data/mikebochenek.json
> data: mikebochenek

- pages/admin/statistics.js
- pages/api/admin/stats.js
> feat: admin stats active users

- components/statistics/ProgressBar.js
Closes #9892 
Added background to the progressbar.
> Fix: progressbar background

- data/ibilalkayy.json
I made some modifications in my profile and updated it with new data
> made some changes in my biodrop profile

- data/khaymanii.json
> data: khaymanii

- data/iSubhamMani.json
> data: iSubhamMani

- data/MutiatBash.json
> data:MutiatBash

- data/Vince-arch.json
> added Vince-arch's data

- pages/docs/maintainers.mdx
> fix: maintainers docs

- data/Olyray.json
> data: Olyray

- data/Megagig.json
> data:Megagig

- data/phatwillis.json
> data: phatwillis.json

- data/njogued.json
> data: njogued

- data/de-marauder.json
- data/phatwillis.json
> data: de-maruader profile

- pages/admin/profiles.js
- pages/api/admin/profiles.js
> feat: admin list new profiles

- pages/api/admin/profiles.js
> fix: new profiles less than 10

- data/MuthoniMN.json
> data: MuthoniMN

- data/josuembuyu.json
> data:josuembuyu

- data/Olusoji01.json
> data: Olusoji01

- data/tuhamworld.json
> data: tuhamworld

- data/Odo-Peter.json
> data: Odo-Peter

- data/emmyVon.json
> data:emmyVon

- data/tuhamworld.json
> Tuhamworld patch 1

- data/joelnyongesa.json
> data: joelnyongesa.json

- data/JustFelix-Dev.json
> data: JustFelix-Dev

- data/davidemusi.json
> data: davidemusi.

- data/Peter-TMK.json
> data: Peter-TMK

- data/dirwolf.json
> data: dirwolf

- data/adetyaz.json
> Created new biodrop profile

- data/gokul8747.json
> data: gokul8747

- .github/workflows/check-profile.yml
> fix: json profile source action

- data/Olumarshal.json
> data: Olumarshal

- data/codeInn001.json
> data: codeInn001

- data/henrychris.json
- upload henrychris.json to create a biodrop profile.
> upload henrychris.json

- data/iamaamunir.json
> data: iamaamunir

- data/Aditya-76.json
PR to add json data into BioDrop
> data: Aditya-76

- data/Riteshrajcloud.json
> data: Riteshrajcloud

- data/254guru.json
> add new BioDrop user profile

- data/ibilalkayy.json
I have added another service link to my profile.
> added another service link

- data/Mykelz.json
> data: Mykelz

- components/layouts/Alert.js
> fix: cta from star to rate

- README.md
> docs: repo rater badge

- .github/workflows/build.yml
- .github/workflows/check-assignee.yml
- .github/workflows/check-profile.yml
- .github/workflows/codeql.yml
- .github/workflows/data-filenames.yml
- .github/workflows/events.yml
- .github/workflows/json-check.yml
- .github/workflows/labels.yml
- .github/workflows/prettier.yml
- .github/workflows/release.yml
- .github/workflows/storybook.yml
- .github/workflows/testimonial.yml
- .github/workflows/vercel-preview.yml
- .github/workflows/vercel.yml
Update GitHub provided action dependencies to current version
> Update action dependencies

- components/Alert.js
Closes #9890 
- made changes in components/Alert.js type info
- Added different bg color and text color for Alert box in dark mode
> [Fix]: Modified Alert.js for Alert-info in dark mode

- data/sandramsc.json
- added link to YouTube channel
- added a new milestone
- edited description
> [Update data:sandramsc] Added and edited content

- data/jiafie7.json
> add jiafie7

- data/sawlew.json
> data: sawlew

- data/Kessi-ux.json
> data: Kessi-ux

- data/uuvedant4.json
> data: uuvedant4

- data/yobuir.json
> Created yobuir.json

- data/Limebee.json
> data: Limebee

- data/Shukazuby.json
> data: Shukazuby

- data/nnodim.json
> data: nnodim

- data/Ousman37.json
> data: Ousman37

- data/jonasermert.json
Thanks in advance for processing my pull request.
> data: jonasermert

- package-lock.json
- package.json
> fix: rolled back mongoose version

- package-lock.json
- package.json
- pages/api/account/manage/link/[[...data]].js
Re-update Mongoose to v8
Handle `Model.Validate()` errors with try / catch in all cases.
> Handle Mongoose Validate error with try/catch

- data/lambeboluwatife.json
> data: lambeboluwatife

- .github/ISSUE_TEMPLATE/bug.yml
Closes #9946 
Adjusted the BioDrop version location in the footer from 'lower right' to 'lower left' in the bug.yml issue template. 
Also proposed a clearer sentence structure for better understanding.
> fix: update version location in bug.yml

- data/eugene4545.json
> data: eugene4545

- components/event/EventTabs.js
- components/user/UserEvents.js
- pages/events.js
- services/utils/event/filterEvent.js
Closes #9877 
* created a new file `filterEvent.js` to store re-usable filtering logic
* added a new state variable `eventsToShow` and `eventsOptions`
* implemented `useMemo` hook to avoid redundant computations and enhance overall performance
> fix: optimized event filtering

- components/navbar/Navbar.js
- Fix login link in the navbar.
I don't think this applies here.
None.
> fix: login link in the navbar

- data/ibilalkayy.json
In this PR, I added some more information in my profile.
> added more data into my profile

- data/ibilalkayy.json
added the business information in my  profile
> added the business information in my  profile

- components/user/UserProfile.js
> fix: quality of profile main picture

- data/Adarsh-619.json
> data: Adarsh-619

- components/user/UserLink.js
- pages/account/manage/link/[[...data]].js
> fix: manage link preview click

- components/user/UserEvents.js
> fix: show events select

- pages/docs/how-to-guides/testimonials-json.mdx
Closes #10135 
Updated the Testimonial Issue Template image at [Testimonials with JSON](https://www.biodrop.io/docs/how-to-guides/testimonials-json) to reflect the new name - BioDrop
> fix(docs): Update Testimonial Issue Template Image

- data/TobySolutions/testimonials/loftwah.json
> fix: delete data/TobySolutions directory

- .github/workflows/prettier.yml
- .github/workflows/testimonial.yml
Update `stefanzweifel/git-auto-commit-action` to v5 for Node compatability
> Update git-auto-commit-action to v5

- data/mikejw.json
> data: updates to links and milestones

- CODE_OF_CONDUCT.md
> fix: CoC contact link

- data/aniketkumar7.json
> data: aniketkumar7

- data/Justice-Udehegbunam.json
> data: Justice-Udehegbunam

- data/ayodejiades.json
> data: ayodejiades

- data/SasankTanikella99.json
> data: SasankTanikella99

- data/MukulGupta005.json
- mukulgupta.json
> data:MukulGupta005

- data/faarish.json
2 days ago I had tried creating this. But the PR was closed because I had deleted the completed database. Now I have done PR according the document provided. I am requesting you to merge. Thank you
> data: faarish

- README.md
> docs: archiving repo

- README.md
> docs: db deletion message

- config/app.json
> fix: archive website message about db deletion

- pages/[username].js
> fix: remove create profile button

- .github/workflows/build.yml
- playwright.config.js
Use playwright `github` reporter on CI
remove `test-summary/action` action to remove Node deprecation warning
> Switch playwright to github reporter on CI

- .github/workflows/issue-lock-unlock.yml
Update `dessant/label-actions` to v4 for Node compatibility.
> Update dessant/label-actions to v4

- pages/account/manage/profile.js
closes #10291 
adding the tag will trigger the handleSubmit function and we are returing early so the setIsDisabled(false) will never get called that's why the button will be remain disabled
> fix: Manage profile page button is disabled while adding new tags

- .github/workflows/labels.yml
Update the version of `actions/labeler` to the latest which supports node 20.
> update actions/labeler to Node 20 compatable version

- components/navbar/Navbar.js
Closes #10332
- remove class `md:hidden`
> fix: Navbar hidden when toggled on medium screen size
